# -*- coding: utf-8 -*-
"""DataScienceProyecto_ModeloUnificado_beta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v1--AyC_nTTpHapHIlglp7L0jLDUw3VV

# Análisis del desempeño académico SIMCE mediante IDPS y variables contextuales

### Problema

El rendimiento académico de los establecimientos educacionales en Chile es medido, entre otros instrumentos, mediante los puntajes SIMCE. Sin embargo, estos resultados no dependen únicamente de factores académicos, sino que también pueden estar asociados a variables socioemocionales y contextuales del establecimiento.

En este proyecto se busca analizar la relación entre los Indicadores de Desarrollo Personal y Social (IDPS), variables contextuales como nivel socioeconómico, dependencia administrativa y ruralidad, y los puntajes SIMCE de Matemática y Lectura.

### Objetivo general

Analizar la relación entre los Indicadores de Desarrollo Personal y Social (IDPS), las variables contextuales de los establecimientos y el rendimiento académico SIMCE, con el fin de identificar qué variables se asocian con mayores o menores puntajes en Matemática y Lectura.

#### Pregunta de investigación

¿Qué relación existe entre los Indicadores de Desarrollo Personal y Social (IDPS), las variables contextuales de los establecimientos y los puntajes SIMCE de Matemática y Lectura?

### Objetivos específicos

- Describir el comportamiento de los puntajes SIMCE de Matemática y Lectura según variables contextuales: nivel socioeconómico (NSE), dependencia administrativa y ruralidad.
- Analizar la relación entre los indicadores IDPS y los puntajes SIMCE.
- Comparar la importancia relativa de variables socioemocionales y contextuales dentro del rendimiento académico observado.
- Interpretar los resultados obtenidos desde una perspectiva educativa, evitando presentar el modelo como una predicción de resultados futuros.

---

## Enfoque del proyecto: análisis descriptivo-explicativo

El enfoque del proyecto se orienta a realizar un análisis descriptivo-explicativo en lugar de un análisis predictivo.

Esta decisión se debe a que, para el contexto educativo, resulta especialmente útil comprender qué variables socioemocionales y contextuales se asocian con mejores o peores resultados SIMCE. Este tipo de análisis puede aportar información relevante para orientar decisiones educativas, identificar áreas de mejora y apoyar la discusión sobre dónde poner mayor atención al momento de diseñar estrategias o políticas públicas educacionales.

En esta etapa, el dataset contiene variables socioemocionales, contextuales y puntajes SIMCE correspondientes al mismo período temporal. Por lo tanto, el análisis permite estudiar relaciones contemporáneas entre variables, pero no permite afirmar que el modelo predice resultados SIMCE de años posteriores.

El proyecto no busca responder “cuánto puntaje tendrá un establecimiento en el futuro”, sino responder preguntas como:

- ¿Qué variables socioemocionales se asocian con mejores o peores resultados SIMCE?
- ¿Qué peso tienen las variables contextuales como NSE, dependencia y ruralidad?
- ¿Las relaciones observadas son similares en Matemática y Lectura?
- ¿Qué variables parecen ser más relevantes para comprender las diferencias de rendimiento entre establecimientos?

### Modelo: regresión lineal múltiple con Matemática + Lectura

El modelo de regresión lineal múltiple se utiliza como una herramienta metodológica para estimar asociaciones entre variables explicativas y puntajes SIMCE, a partir de las cuales se pueda obtener una interpretación educativa.

Para trabajar Matemática y Lectura dentro del mismo análisis, el dataset se reorganiza en formato largo. En este formato, ambos puntajes se integran en una sola variable objetivo llamada `puntaje_simce`, mientras que la variable `tipo_prueba` indica si cada registro corresponde a Matemática o Lectura.

Esto permite analizar ambos resultados SIMCE dentro de una misma estructura de datos y observar si las asociaciones entre variables socioemocionales, contextuales y rendimiento académico se comportan de forma similar entre ambas pruebas.

**Variable objetivo (Y):** puntaje SIMCE por establecimiento.

**Variables explicativas (X):** indicadores IDPS, NSE, dependencia administrativa, ruralidad y tipo de prueba.

**Tipo de prueba:** variable categórica que indica si el puntaje corresponde a Matemática o Lectura.

En este enfoque, el modelo no busca predecir resultados futuros, sino analizar qué variables se asocian con mayores o menores puntajes SIMCE dentro del período observado.

### Significado de variables

- **ind_am = Autoestima Académica y Motivación:** índice alto = colegio con estudiantes que se sienten capaces y motivados.
- **ind_cc = Clima de Convivencia Escolar:** percepción de seguridad, respeto y organización dentro del establecimiento.
- **ind_hv = Hábitos de Vida Saludable:** actitudes relacionadas con bienestar físico, actividad física y autocuidado.
- **ind_pf = Participación y Formación Ciudadana:** sentido de pertenencia al colegio y fomento de valores democráticos y participación estudiantil.
- **Info extra:** todas las variables `ind_` van de 0 a 100, donde un valor mayor representa mejor resultado en el indicador.
- **NSE = Nivel Socioeconómico del Establecimiento = cod_grupo:** Bajo, Medio bajo, Medio, Medio alto y Alto.
- **dependencia = Tipo de Establecimiento = cod_depe2:** Municipal, Particular subvencionado, Particular pagado o SLEP.
- **ruralidad = Zona del establecimiento = cod_rural_rbd:** Urbano o Rural.

### Metodología: Framework OSEMN

Obtain → Scrub → Explore → Model → iNterpret

------------------

## 1) OBTAIN:

**Fuente:** [Agencia de Calidad de la Educación](https://informacionestadistica.agenciaeducacion.cl/#/bases),
la cual posee registros históricos de establecimientos educacionales chilenos:
- SIMCE
- Indicadores de Desarrollo Personal y Social (IDPS)
"""

# 1) OBTAIN: Carga y revisión inicial del dataset

from google.colab import files
import pandas as pd
import numpy as np

uploaded = files.upload()  # Sube dataset

df = pd.read_csv("dataset_historico_final.csv")

print(f"Dimensiones del dataset: {df.shape[0]} filas × {df.shape[1]} columnas")
print(f"Años disponibles: {sorted(df['agno'].unique())}")
print(f"\nPrimeras filas:")
df.head()

"""## 2) SCRUB:
En esta sección se realizaron 3 operaciones:
  1) **Estandarizar las variables categóricas:** algunas variables utilizan códigos
   numéricos (1, 2, 3, ...) que no tienen significado real, por lo que se convierten a etiquetas de texto descriptivas para facilitar la interpretación
  2) **Valores Nulos:** Se eliminan las filas con datos nulos (dropna)
  3) **Outliers:** Se aplica IQR (rango intercuartil) sobre los puntajes SIMCE ya que se asume que no hay una distribución normal en los datos

"""

# Valores ANTES de estandarizar
print("NSE (cod_grupo):", df['cod_grupo'].unique())
print("Dependencia (cod_depe2):", df['cod_depe2'].unique())
print("Ruralidad (cod_rural_rbd):", df['cod_rural_rbd'].unique())

# 2) SCRUB: Limpieza de dataset


nse_map = {'1.0': 'Bajo', '2.0': 'Medio bajo', '3.0': 'Medio',
           '4.0': 'Medio alto', '5.0': 'Alto'}
depe_map = {'1': 'Municipal', '2': 'Particular subvencionado',
            '3': 'Particular pagado', '4': 'SLEP'}
rural_map = {'1': 'Urbano', '2': 'Rural'}

df['cod_grupo']     = df['cod_grupo'].replace(nse_map)
df['cod_depe2']     = df['cod_depe2'].replace(depe_map)
df['cod_rural_rbd'] = df['cod_rural_rbd'].replace(rural_map)

print("Resultados de la estandarización de las var. categóricas:")
print("Categorías NSE:", df['cod_grupo'].unique())
print("Categorías dependencia:", df['cod_depe2'].unique())
print("Categorías ruralidad:", df['cod_rural_rbd'].unique())

#nulos
print(f"\nValores nulos por columna:")
print(df.isnull().sum())
df = df.dropna()
print(f"Filas después de dropna: {len(df)}")

# Detección y eliminación de Outliers en SIMCE
for col in ['prom_mate2m_rbd', 'prom_lect2m_rbd']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    antes = len(df)
    df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]
    print(f"Outliers eliminados en {col}: {antes - len(df)}")

print(f"\nDataset final: {df.shape[0]} filas")

"""## Resultados del SCRUB
- No se encontraron valores nulos en el dataset
- La detección de outliers usando IQR no eliminó registros, ya que el dataset de prueba fue procesado previamente
  - Sin embargo, como a futuro se tiene pensado utilizar un dataset más grande, se aplica IQR igualmente
- Las variables categóricas NSE, dependenciay ruralidad pasaron de códigos numéricos a etiquetas de texto descriptivas

## 3) EXPLORE:

Se explora la distribución de las variables objetivo y su relación con las variables explicativas, a través de estadísticas descriptivas y visualizaciones.
"""

# 3) EXPLORE: Estadísticas descriptivas

import matplotlib.pyplot as plt
import seaborn as sns

print(" -- Estadísticas descriptivas --")
cols_interes = ['prom_mate2m_rbd', 'prom_lect2m_rbd',
                'ind_am', 'ind_cc', 'ind_hv', 'ind_pf']
print(df[cols_interes].describe().round(2))

"""## Distribución de puntajes SIMCE: Matemática y Lectura

A continuación se visualizan, en una misma celda, las distribuciones de puntajes SIMCE de Matemática y Lectura por establecimiento. Esto permite comparar rápidamente el comportamiento general de ambas pruebas.
"""

# 3.1) EXPLORE: Distribución SIMCE Matemática y Lectura

fig, axes = plt.subplots(1, 2, figsize=(14, 4), sharey=True)

df['prom_mate2m_rbd'].hist(bins=40, ax=axes[0], color='steelblue')
axes[0].set_title("Distribución SIMCE Matemática")
axes[0].set_xlabel("Puntaje")
axes[0].set_ylabel("Frecuencia")

df['prom_lect2m_rbd'].hist(bins=40, ax=axes[1], color='coral')
axes[1].set_title("Distribución SIMCE Lectura")
axes[1].set_xlabel("Puntaje")

plt.suptitle("Distribución de puntajes SIMCE por prueba", fontsize=13)
plt.tight_layout()
plt.show()

"""## Puntaje SIMCE según nivel socioeconómico (NSE)

Los siguientes gráficos comparan la distribución de puntajes SIMCE de Matemática y Lectura según el nivel socioeconómico del establecimiento. Al ubicarlos lado a lado, se puede observar si el patrón por NSE se mantiene de forma similar en ambas pruebas.
"""

# 3.2) EXPLORE: SIMCE Matemática y Lectura por NSE

orden_nse = ['Bajo', 'Medio bajo', 'Medio', 'Medio alto', 'Alto']
fig, axes = plt.subplots(1, 2, figsize=(16, 5), sharey=True)

sns.boxplot(data=df, x='cod_grupo', y='prom_mate2m_rbd',
            order=orden_nse, ax=axes[0], palette='Blues',
            hue='cod_grupo', legend=False)
axes[0].set_title("SIMCE Matemática por NSE")
axes[0].set_xlabel("NSE")
axes[0].set_ylabel("Puntaje SIMCE")

sns.boxplot(data=df, x='cod_grupo', y='prom_lect2m_rbd',
            order=orden_nse, ax=axes[1], palette='Oranges',
            hue='cod_grupo', legend=False)
axes[1].set_title("SIMCE Lectura por NSE")
axes[1].set_xlabel("NSE")
axes[1].set_ylabel("")

plt.suptitle("Puntajes SIMCE por nivel socioeconómico", fontsize=13)
plt.tight_layout()
plt.show()

"""## Puntaje SIMCE según dependencia administrativa

Esta visualización permite analizar diferencias en el rendimiento académico según el tipo de establecimiento educacional, comparando Matemática y Lectura dentro de la misma celda.
"""

# 3.3) EXPLORE: SIMCE Matemática y Lectura por dependencia

fig, axes = plt.subplots(1, 2, figsize=(18, 5), sharey=True)

sns.boxplot(data=df, x='cod_depe2', y='prom_mate2m_rbd',
            palette='Set2', ax=axes[0],
            hue='cod_depe2', legend=False)
axes[0].set_title("SIMCE Matemática por dependencia")
axes[0].set_xlabel("Dependencia")
axes[0].set_ylabel("Puntaje SIMCE")
axes[0].tick_params(axis='x', rotation=30)

sns.boxplot(data=df, x='cod_depe2', y='prom_lect2m_rbd',
            palette='Set2', ax=axes[1],
            hue='cod_depe2', legend=False)
axes[1].set_title("SIMCE Lectura por dependencia")
axes[1].set_xlabel("Dependencia")
axes[1].set_ylabel("")
axes[1].tick_params(axis='x', rotation=30)

plt.suptitle("Puntajes SIMCE por dependencia administrativa", fontsize=13)
plt.tight_layout()
plt.show()

"""## Puntaje SIMCE según ruralidad

Esta visualización permite comparar el comportamiento de Matemática y Lectura según si el establecimiento se encuentra en una zona urbana o rural.
"""

# 3.4) EXPLORE: SIMCE Matemática y Lectura por ruralidad

fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

sns.boxplot(data=df, x='cod_rural_rbd', y='prom_mate2m_rbd',
            palette='Set3', ax=axes[0],
            hue='cod_rural_rbd', legend=False)
axes[0].set_title("SIMCE Matemática por ruralidad")
axes[0].set_xlabel("Ruralidad")
axes[0].set_ylabel("Puntaje SIMCE")

sns.boxplot(data=df, x='cod_rural_rbd', y='prom_lect2m_rbd',
            palette='Set3', ax=axes[1],
            hue='cod_rural_rbd', legend=False)
axes[1].set_title("SIMCE Lectura por ruralidad")
axes[1].set_xlabel("Ruralidad")
axes[1].set_ylabel("")

plt.suptitle("Puntajes SIMCE por ruralidad", fontsize=13)
plt.tight_layout()
plt.show()

"""## Matriz de correlaciones

La matriz de correlación permite observar la intensidad y dirección de las relaciones lineales entre los indicadores IDPS y los puntajes SIMCE de Matemática y Lectura.
"""

# 3.5) EXPLORE: Matriz de Correlaciones

corr = df[cols_interes].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0)
plt.title("Matriz de correlación: IDPS y puntajes SIMCE")
plt.tight_layout()
plt.show()

"""## Relación entre indicadores IDPS y puntajes SIMCE

Los siguientes gráficos de dispersión permiten visualizar la relación entre cada indicador IDPS y los puntajes SIMCE de Matemática y Lectura. Cada fila corresponde a un indicador IDPS, dejando Matemática a la izquierda y Lectura a la derecha.
"""

# 3.6) EXPLORE: Scatter IDPS vs SIMCE Matemática y Lectura

idps = [
    ('ind_am', 'Autoestima Académica'),
    ('ind_cc', 'Clima de Convivencia'),
    ('ind_hv', 'Hábitos Saludables'),
    ('ind_pf', 'Participación Ciudadana')
]

fig, axes = plt.subplots(len(idps), 2, figsize=(14, 18), sharey='row')

for i, (col, nombre) in enumerate(idps):
    axes[i, 0].scatter(df[col], df['prom_mate2m_rbd'], alpha=0.2, s=10, color='steelblue')
    axes[i, 0].set_title(f"{nombre} vs SIMCE Matemática")
    axes[i, 0].set_xlabel(nombre)
    axes[i, 0].set_ylabel("SIMCE Matemática")

    axes[i, 1].scatter(df[col], df['prom_lect2m_rbd'], alpha=0.2, s=10, color='coral')
    axes[i, 1].set_title(f"{nombre} vs SIMCE Lectura")
    axes[i, 1].set_xlabel(nombre)
    axes[i, 1].set_ylabel("SIMCE Lectura")

plt.suptitle("Relación entre IDPS y puntajes SIMCE por prueba", fontsize=14)
plt.tight_layout()
plt.show()

"""## Conclusiones del análisis exploratorio

- El NSE muestra una relación progresiva y clara con los puntajes SIMCE: a mayor nivel socioeconómico, se observan mayores puntajes en ambas pruebas.
- La comparación lado a lado permite observar si los patrones de Matemática y Lectura son similares o si existen diferencias relevantes entre ambas pruebas.
- La dependencia administrativa también muestra diferencias en la distribución de puntajes, especialmente al comparar establecimientos municipales, particulares subvencionados, particulares pagados y SLEP.
- La matriz de correlación permite observar que los puntajes de Matemática y Lectura están fuertemente relacionados entre sí, lo que justifica analizarlos dentro de una misma estructura de datos.
- Los indicadores IDPS presentan relaciones positivas con los puntajes SIMCE, aunque la intensidad de esa relación puede variar según el indicador y la prueba.
- Las correlaciones y gráficos deben interpretarse como asociaciones, no como causalidad directa.

-----------------

## 4) MODEL: Regresión lineal múltiple con Matemática + Lectura

En esta sección se implementa una regresión lineal múltiple utilizando Matemática y Lectura dentro de una misma estructura de datos. Para ello, el dataset se reorganiza desde un formato ancho, donde Matemática y Lectura aparecen en columnas separadas, hacia un formato largo, donde ambos puntajes quedan en una sola variable objetivo llamada `puntaje_simce`.

La variable `tipo_prueba` permite distinguir si cada observación corresponde a Matemática o Lectura. De esta forma, el modelo analiza ambos resultados SIMCE dentro del mismo marco de análisis.

El modelo considera:

- Variables numéricas asociadas a los indicadores IDPS.
- Variables categóricas asociadas al contexto escolar.
- La variable categórica `tipo_prueba`.
- Estandarización de variables numéricas.
- Codificación One-Hot para variables categóricas.
- Separación train/test y validación cruzada para evaluar estabilidad.

> Importante: aunque se usan métricas típicas de modelos supervisados, la interpretación del proyecto sigue siendo descriptivo-explicativa. Es decir, el modelo se usa para estimar asociaciones, no para afirmar predicción futura.
"""

# 4.1) Preparación del dataset en formato largo

# Se crea un identificador de fila para evitar que Matemática y Lectura del mismo establecimiento
# queden separadas entre train y test después de transformar el dataset.
df_model = df.reset_index().rename(columns={"index": "id_registro"})

id_vars = [
    "id_registro",
    "ind_am", "ind_cc", "ind_hv", "ind_pf",
    "cod_grupo", "cod_depe2", "cod_rural_rbd"
]

# Se conservan columnas de identificación si existen en el dataset
for col in ["agno", "rbd"]:
    if col in df_model.columns and col not in id_vars:
        id_vars.append(col)

df_long = df_model.melt(
    id_vars=id_vars,
    value_vars=["prom_mate2m_rbd", "prom_lect2m_rbd"],
    var_name="tipo_prueba",
    value_name="puntaje_simce"
)

df_long["tipo_prueba"] = df_long["tipo_prueba"].map({
    "prom_mate2m_rbd": "Matemática",
    "prom_lect2m_rbd": "Lectura"
})

df_long = df_long.dropna(subset=["puntaje_simce"]).copy()

print(f"Dataset original: {df.shape[0]} filas")
print(f"Dataset largo: {df_long.shape[0]} filas")
print("\nDistribución por tipo de prueba:")
print(df_long["tipo_prueba"].value_counts())

df_long.head()

# 4.2) Entrenamiento del modelo unificado

from sklearn.model_selection import train_test_split, cross_val_score, GroupShuffleSplit, GroupKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

target = "puntaje_simce"

features_num = ["ind_am", "ind_cc", "ind_hv", "ind_pf"]
features_cat = ["cod_grupo", "cod_rural_rbd", "cod_depe2", "tipo_prueba"]

X = df_long[features_num + features_cat]
y = df_long[target]

# Se agrupa por id_registro para que Matemática y Lectura del mismo establecimiento
# queden juntas en train o juntas en test.
groups = df_long["id_registro"]

gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train = X.iloc[train_idx]
X_test = X.iloc[test_idx]
y_train = y.iloc[train_idx]
y_test = y.iloc[test_idx]

print(f"Train: {len(X_train)} registros | Test: {len(X_test)} registros")

# Pipeline de preprocesamiento + modelo
preprocessor_unificado = ColumnTransformer(transformers=[
    ("num", StandardScaler(), features_num),
    ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat)
])

model_unificado = Pipeline(steps=[
    ("preprocessor", preprocessor_unificado),
    ("regressor", LinearRegression())
])

# Entrenamiento
model_unificado.fit(X_train, y_train)

# Estimaciones
y_pred_train = model_unificado.predict(X_train)
y_pred_test = model_unificado.predict(X_test)

# 4.3) Evaluación Train vs Test + Validación Cruzada

def calcular_metricas(y_real, y_estimado):
    return {
        "MAE": mean_absolute_error(y_real, y_estimado),
        "RMSE": np.sqrt(mean_squared_error(y_real, y_estimado)),
        "R2": r2_score(y_real, y_estimado)
    }

metricas_train = calcular_metricas(y_train, y_pred_train)
metricas_test = calcular_metricas(y_test, y_pred_test)

resultados_modelo = pd.DataFrame([
    {"Dataset": "Train", **metricas_train},
    {"Dataset": "Test", **metricas_test}
])

# Validación cruzada agrupada para mantener juntas las dos pruebas de un mismo registro
n_groups = groups.nunique()
n_splits = min(5, n_groups)

if n_splits >= 2:
    cv = GroupKFold(n_splits=n_splits)
    cv_scores = cross_val_score(
        model_unificado,
        X,
        y,
        cv=cv,
        groups=groups,
        scoring="r2"
    )
    r2_cv_mean = cv_scores.mean()
    r2_cv_std = cv_scores.std()
else:
    cv_scores = np.array([np.nan])
    r2_cv_mean = np.nan
    r2_cv_std = np.nan

display(resultados_modelo.round(3))

print(f"R² validación cruzada: {np.round(cv_scores, 3)}")
print(f"R² promedio CV: {r2_cv_mean:.3f} ± {r2_cv_std:.3f}")

"""### Interpretación de métricas

- **MAE:** se utiliza porque expresa el error promedio directamente en puntos SIMCE, lo que facilita la interpretación educativa.
- **RMSE:** se reporta como complemento, ya que penaliza con mayor fuerza los errores grandes.
- **R²:** permite observar qué proporción de la variabilidad del puntaje SIMCE es explicada por el modelo.
- **R² CV:** permite evaluar si el desempeño del modelo se mantiene estable al cambiar las particiones de los datos.

En este proyecto no se prioriza MAPE porque los puntajes SIMCE no son una variable porcentual ni tienen un cero interpretativo natural.

"""

# 5) iNTERPRET: Valores reales vs estimados - Modelo unificado

import matplotlib.pyplot as plt

plt.figure(figsize=(7, 7))
plt.scatter(y_test, y_pred_test, alpha=0.3, s=15)
min_val = min(y_test.min(), y_pred_test.min())
max_val = max(y_test.max(), y_pred_test.max())
plt.plot([min_val, max_val], [min_val, max_val], "r--", label="Estimación exacta")
plt.xlabel("Valores reales SIMCE")
plt.ylabel("Valores estimados por el modelo")
plt.title("Modelo unificado: valores reales vs estimados")
plt.legend()
plt.tight_layout()
plt.show()

# 5.1) iNTERPRET: Distribución de residuos - Modelo unificado

residuals = y_test - y_pred_test

plt.figure(figsize=(8, 4))
plt.hist(residuals, bins=40, edgecolor="white")
plt.axvline(0, color="black", linestyle="--")
plt.xlabel("Residuo (Real − Estimado)")
plt.ylabel("Frecuencia")
plt.title("Distribución de residuos — Modelo unificado")
plt.tight_layout()
plt.show()

print(f"Media de residuos: {residuals.mean():.2f}")
print(f"Desviación estándar de residuos: {residuals.std():.2f}")

"""## Importancia relativa de variables

A continuación se analizan los coeficientes del modelo. Estos coeficientes permiten observar qué variables presentan mayor asociación con el puntaje SIMCE dentro del modelo.

Los coeficientes positivos indican asociación con puntajes más altos, mientras que los negativos indican asociación con puntajes más bajos, manteniendo constantes las demás variables incluidas.

Como las variables numéricas fueron estandarizadas, sus coeficientes representan cambios asociados a una desviación estándar de la variable, no a un punto exacto del indicador.

Importante: los coeficientes deben interpretarse como asociaciones y no como efectos causales directos.

"""

# 5.2) iNTERPRET: Coeficientes del modelo unificado

feature_names = (
    model_unificado.named_steps["preprocessor"]
    .named_transformers_["num"]
    .get_feature_names_out(features_num).tolist()
    +
    model_unificado.named_steps["preprocessor"]
    .named_transformers_["cat"]
    .get_feature_names_out(features_cat).tolist()
)

coefs = model_unificado.named_steps["regressor"].coef_

coef_df = pd.DataFrame({
    "Variable": feature_names,
    "Coeficiente": coefs
})

coef_df = coef_df.reindex(
    coef_df["Coeficiente"].abs().sort_values(ascending=False).index
)

display(coef_df.round(3).head(15))

plt.figure(figsize=(10, 6))
plt.barh(coef_df["Variable"].head(15), coef_df["Coeficiente"].head(15))
plt.axvline(0, color="black", linewidth=0.8)
plt.xlabel("Coeficiente")
plt.title("Variables con mayor asociación — Modelo unificado")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

print("\nCategoría base usada por OneHotEncoder en variables categóricas:")
encoder_cat = model_unificado.named_steps["preprocessor"].named_transformers_["cat"]
for variable, categorias in zip(features_cat, encoder_cat.categories_):
    print(f"- {variable}: categoría base = {categorias[0]}")

"""## Síntesis del modelo

El modelo de regresión lineal múltiple se implementa con Matemática y Lectura integradas en una sola variable objetivo (`puntaje_simce`) y diferenciadas mediante la variable `tipo_prueba`.

Esta estructura permite analizar ambos resultados SIMCE dentro del mismo marco metodológico, manteniendo una interpretación descriptivo-explicativa. Por lo tanto, el foco del análisis está en identificar qué variables socioemocionales y contextuales se asocian con mayores o menores puntajes SIMCE, sin afirmar causalidad directa ni predicción de resultados futuros.
"""