# -*- coding: utf-8 -*-
"""DataScienceProyecto_ModeloFinal_beta2 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sPixcC48qqULFSAfLt_kNFGOmWdMT80

# Análisis del desempeño académico SIMCE mediante IDPS y variables contextuales
## Modelo final beta - Presentación 2
### Versión beta2: metodología del notebook con visualización estilo GitHub

Este notebook corresponde a la evolución técnica del proyecto para la **Presentación 2**. Toma como base el trabajo del primer notebook y del `ModeloUnificado_beta`, pero adapta el análisis al dataset final consolidado en GitHub.

El objetivo es **comprender cómo se asocian los Indicadores de Desarrollo Personal y Social (IDPS), junto con variables contextuales, con los resultados SIMCE de Matemática y Lectura según el nivel educativo evaluado**.

## Evolución metodológica respecto a la Presentación 1

En la Presentación 1 se utilizó un primer notebook (`DataScienceProyecto1`) con regresión lineal múltiple sobre un dataset provisorio. Ese modelo ya separaba Matemática y Lectura, pero todavía no incorporaba el dataset final ni distinguía los cursos evaluados.

A partir del feedback del profesor se realizaron ajustes importantes:

- Se reformuló el enfoque para evitar presentar el modelo como predicción futura cuando las variables IDPS y SIMCE pertenecen al mismo período.
- Se probó una iteración intermedia (`ModeloUnificado_beta`) que integraba Matemática y Lectura en una sola variable objetivo, usando `tipo_prueba` como variable explicativa.
- Se mejoró la narrativa hacia un análisis descriptivo-explicativo, centrado en asociaciones y no en causalidad.
- Se incorporó la necesidad de comparar resultados, validar train/test y justificar métricas como MAE, RMSE y R².

Para esta entrega final se adopta el enfoque del GitHub: **modelos separados por curso y asignatura**. Esta decisión permite comparar de forma más clara si los IDPS se asocian de manera distinta con SIMCE según el nivel escolar y según Matemática o Lectura.

## Pregunta de investigación

¿Qué relación existe entre los Indicadores de Desarrollo Personal y Social (IDPS), las variables contextuales de los establecimientos y los puntajes SIMCE de Matemática y Lectura, considerando diferencias entre cursos evaluados?

## Objetivo general

Analizar la asociación entre IDPS, variables contextuales y resultados SIMCE por establecimiento, diferenciando por curso y asignatura, para identificar qué variables se relacionan con mayores o menores puntajes en Matemática y Lectura.

## Enfoque

Se mantiene la metodología **OSEMN**:

1. **Obtain:** carga del dataset final por curso.
2. **Scrub:** revisión de nulos, categorías, rangos y outliers por curso.
3. **Explore:** análisis descriptivo y correlaciones.
4. **Model:** regresión lineal múltiple por curso y asignatura.
5. **iNterpret:** comparación de métricas, coeficientes e interpretación educativa.

> Importante: el enfoque principal es contemporáneo. El modelo estudia asociaciones en el mismo período, no afirma causalidad ni predicción futura. Para predicción futura real se requeriría un dataset con desfase temporal explícito entre IDPS y SIMCE.

---
# 1) OBTAIN: Carga de datos finales

Se utilizan los cuatro datasets por curso generados desde el pipeline del GitHub:

- `dataset_historico_4b.csv`
- `dataset_historico_6b.csv`
- `dataset_historico_8b.csv`
- `dataset_historico_2m.csv`

Cada archivo contiene puntajes SIMCE, IDPS y variables contextuales por establecimiento (`rbd`), año (`agno`) y curso (`curso`).

El archivo `dataset_historico_completo.csv` puede quedar disponible en la carpeta como respaldo para análisis global, pero no se usa en el flujo principal de este notebook.
"""

# 1.1) Imports y configuración general

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display

from sklearn.model_selection import GroupShuffleSplit, GroupKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

sns.set_theme(style="whitegrid", context="notebook")
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 120)

CURSOS_ORDEN = ["4b", "6b", "8b", "2m"]
CURSO_NOMBRE = {
    "4b": "4° básico",
    "6b": "6° básico",
    "8b": "8° básico",
    "2m": "II medio",
}

IDPS_NOMBRE = {
    "ind_am": "Autoestima académica y motivación",
    "ind_cc": "Clima de convivencia escolar",
    "ind_hv": "Hábitos de vida saludable",
    "ind_pf": "Participación y formación ciudadana",
}

ASIGNATURAS = [
    ("prom_mate2m_rbd", "Matemática", "steelblue"),
    ("prom_lect2m_rbd", "Lectura", "coral"),
]

PALETA_ASIGNATURA = {"Matemática": "steelblue", "Lectura": "coral"}
HUE_ASIGNATURA = ["Matemática", "Lectura"]

features_idps = ["ind_am", "ind_cc", "ind_hv", "ind_pf"]
features_contexto = ["cod_grupo", "cod_rural_rbd", "cod_depe2"]
targets = ["prom_mate2m_rbd", "prom_lect2m_rbd"]

# 1.2) Ubicación de los CSV

# Si estás en Google Colab y subiste los CSV a /content, deja DATA_DIR = None.
# Si están en Google Drive, monta Drive y define DATA_DIR manualmente, por ejemplo:
#from google.colab import drive
#drive.mount('/content/drive')
#DATA_DIR = "/content/drive/MyDrive/ProyectoDataScience/presentacion2"

DATA_DIR = "/content/"

REQUIRED_FILES = [
    "dataset_historico_4b.csv",
    "dataset_historico_6b.csv",
    "dataset_historico_8b.csv",
    "dataset_historico_2m.csv",
]


def encontrar_carpeta_datos(data_dir=None):
    """Busca la carpeta que contiene los cuatro CSV por curso."""
    candidates = []
    if data_dir is not None:
        candidates.append(Path(data_dir))

    cwd = Path.cwd()
    candidates.extend([
        cwd,
        cwd / "presentacion2",
        cwd / "data" / "processed" / "por_curso",
        cwd / "por_curso",
        Path("/content"),
        Path("/content/presentacion2"),
        Path("/content/data/processed/por_curso"),
    ])

    for candidate in candidates:
        if candidate.exists() and all((candidate / f).exists() for f in REQUIRED_FILES):
            return candidate

    # Fallback liviano para Colab: buscar solo dentro de /content y el directorio actual.
    search_roots = [cwd]
    if Path("/content").exists():
        search_roots.append(Path("/content"))

    for root in search_roots:
        for hit in root.rglob("dataset_historico_4b.csv"):
            candidate = hit.parent
            if all((candidate / f).exists() for f in REQUIRED_FILES):
                return candidate

    raise FileNotFoundError(
        "No encontré los cuatro CSV por curso. En Colab puedes subirlos directamente a /content "
        "o definir DATA_DIR con la ruta de la carpeta que los contiene."
    )

DATA_PATH = encontrar_carpeta_datos(DATA_DIR)
print(f"Carpeta de datos encontrada: {DATA_PATH}")

# Se deja detectado el dataset completo solo como respaldo, no como fuente principal.
path_completo = DATA_PATH / "dataset_historico_completo.csv"
print("Dataset histórico completo disponible como respaldo:", path_completo.exists())

# 1.3) Carga de datasets por curso

dfs = []
for file_name in REQUIRED_FILES:
    path = DATA_PATH / file_name
    df_tmp = pd.read_csv(path)
    dfs.append(df_tmp)
    print(f"{file_name}: {df_tmp.shape[0]:,} filas × {df_tmp.shape[1]} columnas")

df = pd.concat(dfs, ignore_index=True)

print("\nDataset unido para el análisis final:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]}")
display(df.head())

# 1.4) Panorama inicial del dataset

resumen_obtain = pd.DataFrame({
    "valor": [
        df.shape[0],
        df.shape[1],
        ", ".join(map(str, sorted(df["agno"].dropna().unique()))),
        ", ".join([CURSO_NOMBRE.get(c, c) for c in CURSOS_ORDEN if c in set(df["curso"])]),
    ]
}, index=["filas", "columnas", "años disponibles", "cursos disponibles"])

display(resumen_obtain)

print("Registros por curso:")
display(df["curso"].value_counts().reindex(CURSOS_ORDEN).rename(index=CURSO_NOMBRE).to_frame("n_registros"))

print("Registros por año y curso:")
display(pd.crosstab(df["agno"], df["curso"]).reindex(columns=CURSOS_ORDEN))

"""---
# 2) SCRUB: Limpieza y preparación

El dataset ya viene consolidado desde el pipeline del GitHub. En esta sección se revisan y estandarizan los elementos necesarios para el modelamiento:

- categorías de NSE, dependencia y ruralidad;
- valores nulos;
- rangos de puntajes SIMCE e IDPS;
- outliers calculados por curso, para evitar mezclar niveles educativos distintos.

También se codifica el NSE como variable ordinal, respondiendo al feedback recibido en la Presentación 1.

## Nota sobre codificación ordinal del NSE

`cod_grupo` representa el nivel socioeconómico del establecimiento. Esta variable tiene un orden natural: `Bajo < Medio bajo < Medio < Medio alto < Alto`. Por eso, en el modelo final se crea `nse_ord`, que asigna valores de 1 a 5 respetando ese orden.

Esto cumple la misma idea que usar `OrdinalEncoder` de sklearn, pero de forma manual y explícita. La ventaja de hacerlo manualmente en este notebook es que el orden queda visible y es más fácil de defender en la presentación. Si se usara `OrdinalEncoder`, habría que entregarle explícitamente el orden de categorías para evitar que lo interprete en orden alfabético.

En el modelo final, `nse_ord` se estandariza junto con los IDPS. Por lo tanto, su coeficiente representa el cambio esperado en SIMCE asociado a un aumento de una desviación estándar en NSE, lo que permite comparar mejor su magnitud relativa frente a los indicadores IDPS.

"""

# 2.1) Normalización de categorías y tipos

nse_map = {
    "1": "Bajo", "1.0": "Bajo", "Bajo": "Bajo",
    "2": "Medio bajo", "2.0": "Medio bajo", "Medio bajo": "Medio bajo",
    "3": "Medio", "3.0": "Medio", "Medio": "Medio",
    "4": "Medio alto", "4.0": "Medio alto", "Medio alto": "Medio alto",
    "5": "Alto", "5.0": "Alto", "Alto": "Alto",
}

dependencia_map = {
    "1": "Municipal", "1.0": "Municipal", "Municipal": "Municipal",
    "2": "Particular subvencionado", "2.0": "Particular subvencionado", "Particular subvencionado": "Particular subvencionado",
    "3": "Particular pagado", "3.0": "Particular pagado", "Particular pagado": "Particular pagado",
    "4": "SLEP", "4.0": "SLEP", "SLEP": "SLEP",
}

ruralidad_map = {
    "1": "Urbano", "1.0": "Urbano", "Urbano": "Urbano",
    "2": "Rural", "2.0": "Rural", "Rural": "Rural",
}

nse_ord_map = {
    "Bajo": 1,
    "Medio bajo": 2,
    "Medio": 3,
    "Medio alto": 4,
    "Alto": 5,
}


def normalizar_categorias(df_in):
    df_out = df_in.copy()

    for col in ["cod_grupo", "cod_depe2", "cod_rural_rbd", "curso"]:
        df_out[col] = df_out[col].astype(str).str.strip()

    df_out["cod_grupo"] = df_out["cod_grupo"].replace(nse_map)
    df_out["cod_depe2"] = df_out["cod_depe2"].replace(dependencia_map)
    df_out["cod_rural_rbd"] = df_out["cod_rural_rbd"].replace(ruralidad_map)
    df_out["nse_ord"] = df_out["cod_grupo"].map(nse_ord_map)

    numeric_cols = ["rbd", "agno"] + targets + features_idps + ["nse_ord"]
    for col in numeric_cols:
        df_out[col] = pd.to_numeric(df_out[col], errors="coerce")

    df_out["curso_nombre"] = df_out["curso"].map(CURSO_NOMBRE)
    return df_out


df = normalizar_categorias(df)

display(df[["curso", "curso_nombre", "agno", "cod_grupo", "nse_ord", "cod_rural_rbd", "cod_depe2"]].head())

# 2.2) Revisión de nulos y categorías

columnas_requeridas = [
    "rbd", "agno", "curso", "curso_nombre",
    "prom_mate2m_rbd", "prom_lect2m_rbd",
    "cod_grupo", "nse_ord", "cod_rural_rbd", "cod_depe2",
    "ind_am", "ind_cc", "ind_hv", "ind_pf",
]

print("Valores nulos por columna relevante:")
display(df[columnas_requeridas].isna().sum().to_frame("nulos"))

print("Categorías detectadas:")
for col in ["cod_grupo", "cod_rural_rbd", "cod_depe2", "curso"]:
    print(f"- {col}: {sorted(df[col].dropna().unique())}")

antes = len(df)
df_scrub = df.dropna(subset=columnas_requeridas).copy()
print(f"\nFilas antes de dropna: {antes:,}")
print(f"Filas después de dropna: {len(df_scrub):,}")
print(f"Filas eliminadas por nulos: {antes - len(df_scrub):,}")

# 2.3) Revisión de rangos principales

cols_interes = targets + features_idps
resumen_rangos = df_scrub.groupby("curso")[cols_interes].agg(["min", "mean", "max"]).round(2)
resumen_rangos = resumen_rangos.reindex(CURSOS_ORDEN)
display(resumen_rangos)

"""## Análisis de simetría / skewness

El feedback de la Presentación 1 pidió revisar la simetría de las variables. Para esto se calcula el **skewness** de los puntajes SIMCE y de los IDPS por curso.

Una regla práctica de lectura es:

- `|skewness| < 0.5`: distribución aproximadamente simétrica.
- `0.5 <= |skewness| < 1`: asimetría moderada.
- `|skewness| >= 1`: asimetría alta.

Este diagnóstico no cambia automáticamente el modelo, pero ayuda a justificar si las variables son razonables para una regresión lineal o si, en una iteración futura, convendría probar transformaciones.

"""

# 2.4) Análisis de simetría / skewness

variables_skew = targets + features_idps


def clasificar_skewness(valor):
    abs_val = abs(valor)
    if abs_val < 0.5:
        return "Aprox. simétrica"
    if abs_val < 1:
        return "Asimetría moderada"
    return "Asimetría alta"


skew_rows = []
for curso in CURSOS_ORDEN:
    g = df_scrub[df_scrub["curso"] == curso]
    for variable in variables_skew:
        skew_value = g[variable].skew()
        skew_rows.append({
            "curso": curso,
            "curso_nombre": CURSO_NOMBRE[curso],
            "variable": variable,
            "skewness": skew_value,
            "interpretacion": clasificar_skewness(skew_value),
        })

skewness_df = pd.DataFrame(skew_rows)

tabla_skew = skewness_df.pivot(
    index="variable",
    columns="curso_nombre",
    values="skewness",
)[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]

display(tabla_skew.round(3))
display(skewness_df.round(3))

fig, axes = plt.subplots(2, 3, figsize=(16, 8))
axes = axes.flatten()

for ax, variable in zip(axes, variables_skew):
    sns.histplot(
        data=df_scrub,
        x=variable,
        hue="curso_nombre",
        bins=35,
        kde=True,
        stat="density",
        common_norm=False,
        ax=ax,
    )
    ax.set_title(f"Distribución de {variable}")
    ax.set_xlabel(variable)
    ax.set_ylabel("Densidad")

plt.suptitle("Distribuciones para análisis de skewness")
plt.tight_layout()
plt.show()

# 2.4) Tratamiento de outliers por curso usando IQR sobre puntajes SIMCE

# El IQR se calcula por curso porque mezclar 4° básico, 6° básico, 8° básico y II medio
# puede clasificar como outlier un valor que solo pertenece a otra escala de comparación educativa.

def filtrar_outliers_iqr_por_curso(df_in, targets_modelo):
    keep_global = pd.Series(True, index=df_in.index)
    filas_resumen = []

    for curso, g in df_in.groupby("curso"):
        keep_curso = pd.Series(True, index=g.index)
        for col in targets_modelo:
            q1 = g[col].quantile(0.25)
            q3 = g[col].quantile(0.75)
            iqr = q3 - q1
            lower = q1 - 1.5 * iqr
            upper = q3 + 1.5 * iqr
            keep_col = g[col].between(lower, upper)
            filas_resumen.append({
                "curso": curso,
                "curso_nombre": CURSO_NOMBRE.get(curso, curso),
                "variable": col,
                "limite_inferior": lower,
                "limite_superior": upper,
                "outliers_detectados": int((~keep_col).sum()),
            })
            keep_curso &= keep_col
        keep_global.loc[g.index] = keep_curso

    return df_in.loc[keep_global].copy(), pd.DataFrame(filas_resumen)


df_modelo, resumen_outliers = filtrar_outliers_iqr_por_curso(df_scrub, targets)

print(f"Filas antes de IQR: {len(df_scrub):,}")
print(f"Filas después de IQR: {len(df_modelo):,}")
print(f"Filas eliminadas por IQR: {len(df_scrub) - len(df_modelo):,}")
display(resumen_outliers.round(2))

"""---
# 3) EXPLORE: Análisis descriptivo

Esta sección compara los puntajes SIMCE y los IDPS entre cursos. La idea es verificar si tiene sentido modelar cada nivel educativo por separado en vez de mezclar todos los cursos en un único modelo.

"""

# 3.1) Distribución de SIMCE por curso y asignatura

plot_df = df_modelo.melt(
    id_vars=["rbd", "agno", "curso", "curso_nombre"],
    value_vars=targets,
    var_name="tipo_prueba",
    value_name="puntaje_simce",
)
plot_df["asignatura"] = plot_df["tipo_prueba"].map({
    "prom_mate2m_rbd": "Matemática",
    "prom_lect2m_rbd": "Lectura",
})
plot_df["curso_nombre"] = pd.Categorical(
    plot_df["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)

plt.figure(figsize=(11, 5))
sns.boxplot(data=plot_df, x="curso_nombre", y="puntaje_simce", hue="asignatura", hue_order=HUE_ASIGNATURA, palette=PALETA_ASIGNATURA)
plt.title("Distribución de puntajes SIMCE por curso y asignatura")
plt.xlabel("Curso")
plt.ylabel("Puntaje SIMCE")
plt.legend(title="Asignatura")
plt.tight_layout()
plt.show()

# 3.2) Evolución por año disponible

promedios_anuales = plot_df.groupby(["agno", "curso", "curso_nombre", "asignatura"], as_index=False)["puntaje_simce"].mean()

plt.figure(figsize=(12, 5))
sns.lineplot(
    data=promedios_anuales,
    x="agno", y="puntaje_simce",
    hue="curso_nombre", style="asignatura",
    markers=True, dashes=False,
)
plt.title("Promedio SIMCE por año, curso y asignatura")
plt.xlabel("Año")
plt.ylabel("Puntaje promedio")
plt.legend(title="Curso / asignatura", bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.show()

# 3.3) Correlaciones IDPS vs SIMCE por curso

filas_corr = []
for curso in CURSOS_ORDEN:
    g = df_modelo[df_modelo["curso"] == curso]
    for idps in features_idps:
        for target, asignatura, _ in ASIGNATURAS:
            filas_corr.append({
                "curso": curso,
                "curso_nombre": CURSO_NOMBRE[curso],
                "idps": idps,
                "indicador": IDPS_NOMBRE[idps],
                "asignatura": asignatura,
                "correlacion": g[idps].corr(g[target]),
            })

corr_idps = pd.DataFrame(filas_corr)

for asignatura in ["Matemática", "Lectura"]:
    tabla = corr_idps[corr_idps["asignatura"] == asignatura].pivot(
        index="indicador", columns="curso_nombre", values="correlacion"
    )[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]
    print(f"Correlación IDPS vs SIMCE - {asignatura}")
    display(tabla.round(3))

"""## Matrices de correlación complementarias

El GitHub incluye una matriz global de correlación entre puntajes SIMCE e IDPS. En esta versión se mantiene esa mirada global y se agrega una lectura por curso, porque el modelo final se estima de forma separada para 4° básico, 6° básico, 8° básico e II medio.

Estas matrices no reemplazan al modelo de regresión: sirven para diagnosticar relaciones lineales simples antes de controlar por NSE, dependencia y ruralidad.

"""

# 3.3b) Matrices de correlación: global y por curso

corr_vars_modelo = targets + features_idps + ["nse_ord"]
corr_labels = {
    "prom_mate2m_rbd": "SIMCE Matemática",
    "prom_lect2m_rbd": "SIMCE Lectura",
    "ind_am": "Autoestima",
    "ind_cc": "Convivencia",
    "ind_hv": "Hábitos",
    "ind_pf": "Participación",
    "nse_ord": "NSE ordinal",
}

corr_global = df_modelo[corr_vars_modelo].corr()
plt.figure(figsize=(9, 7))
sns.heatmap(
    corr_global.rename(index=corr_labels, columns=corr_labels),
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    square=True,
)
plt.title("Matriz de correlación global: SIMCE, IDPS y NSE")
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(15, 12))
axes = axes.flatten()

for ax, curso in zip(axes, CURSOS_ORDEN):
    g = df_modelo[df_modelo["curso"] == curso]
    corr_curso = g[corr_vars_modelo].corr().rename(index=corr_labels, columns=corr_labels)
    sns.heatmap(
        corr_curso,
        annot=True,
        fmt=".2f",
        cmap="coolwarm",
        center=0,
        square=True,
        ax=ax,
        cbar=False,
    )
    ax.set_title(f"Matriz de correlación - {CURSO_NOMBRE[curso]}")
    ax.tick_params(axis="x", rotation=35)
    ax.tick_params(axis="y", rotation=0)

plt.suptitle("Matrices de correlación por curso", fontsize=14)
plt.tight_layout()
plt.show()

# 3.4) Multicolinealidad entre IDPS: correlación y VIF

corr_idps_global = df_modelo[features_idps].corr()
plt.figure(figsize=(7, 5))
sns.heatmap(corr_idps_global, annot=True, fmt=".2f", cmap="coolwarm", center=0,
            xticklabels=[IDPS_NOMBRE[c] for c in features_idps],
            yticklabels=[IDPS_NOMBRE[c] for c in features_idps])
plt.title("Correlación entre indicadores IDPS")
plt.xticks(rotation=35, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()


def calcular_vif_sklearn(df_num):
    """Calcula VIF sin depender de statsmodels."""
    from sklearn.linear_model import LinearRegression

    filas = []
    for col in df_num.columns:
        y = df_num[col].values
        X = df_num.drop(columns=[col]).values
        r2 = LinearRegression().fit(X, y).score(X, y)
        vif = np.inf if (1 - r2) <= 1e-12 else 1 / (1 - r2)
        filas.append({"variable": col, "indicador": IDPS_NOMBRE.get(col, col), "R2_auxiliar": r2, "VIF": vif})
    return pd.DataFrame(filas)

vif_rows = []
for curso in CURSOS_ORDEN:
    vif_tmp = calcular_vif_sklearn(df_modelo.loc[df_modelo["curso"] == curso, features_idps])
    vif_tmp.insert(0, "curso", curso)
    vif_tmp.insert(1, "curso_nombre", CURSO_NOMBRE[curso])
    vif_rows.append(vif_tmp)

vif_df = pd.concat(vif_rows, ignore_index=True)
display(vif_df.round(3))

"""---
# 4) MODEL: Regresión lineal múltiple por curso y asignatura

Se entrenan **8 modelos**:

- 4 cursos: 4° básico, 6° básico, 8° básico y II medio.
- 2 asignaturas: Matemática y Lectura.

Este enfoque reemplaza al modelo unificado como modelo principal porque permite comparar directamente los coeficientes de IDPS entre niveles educativos y asignaturas.

## Ajustes respecto al script del GitHub

Se toma el GitHub como referencia de estructura y visualización, pero se ajustan algunas decisiones para hacer la validación más defendible en la entrega:

- **Split agrupado por `rbd`:** evita que un mismo establecimiento aparezca simultáneamente en entrenamiento y prueba.
- **Validación cruzada agrupada:** evalúa estabilidad respetando la unidad establecimiento.
- **NSE ordinal estandarizado:** permite comparar su magnitud con los IDPS.
- **One-hot con categoría base (`drop="first"`):** evita redundancia perfecta entre categorías y facilita la interpretación de las variables contextuales.

Los gráficos de importancia se muestran con el estilo del GitHub, pero usan los coeficientes obtenidos con esta metodología.


## Variables del modelo

**Targets:**

- `prom_mate2m_rbd`: puntaje SIMCE Matemática.
- `prom_lect2m_rbd`: puntaje SIMCE Lectura.

**Predictores:**

- IDPS: `ind_am`, `ind_cc`, `ind_hv`, `ind_pf`.
- NSE ordinal estandarizado: `nse_ord`.
- Ruralidad: `cod_rural_rbd`.
- Dependencia administrativa: `cod_depe2`.

Los IDPS y `nse_ord` se estandarizan para que sus coeficientes sean comparables en magnitud. Ruralidad y dependencia se codifican con one-hot encoding, por lo que sus coeficientes se interpretan como diferencias respecto a una categoría base.

La variable `curso` no se usa como predictor dentro de cada modelo porque cada modelo se ajusta sobre un único curso.

"""

# 4.1) Funciones de modelamiento

features_num = ["ind_am", "ind_cc", "ind_hv", "ind_pf", "nse_ord"]
features_cat = ["cod_rural_rbd", "cod_depe2"]
features_modelo = features_num + features_cat


def calcular_metricas(y_real, y_estimado):
    return {
        "MAE": mean_absolute_error(y_real, y_estimado),
        "RMSE": np.sqrt(mean_squared_error(y_real, y_estimado)),
        "R2": r2_score(y_real, y_estimado),
    }


def crear_pipeline_regresion():
    preprocessor = ColumnTransformer(transformers=[
        ("num", StandardScaler(), features_num),
        ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat),
    ])

    return Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("regressor", LinearRegression()),
    ])


def obtener_feature_names(model):
    pre = model.named_steps["preprocessor"]
    num_names = pre.named_transformers_["num"].get_feature_names_out(features_num).tolist()
    cat_names = pre.named_transformers_["cat"].get_feature_names_out(features_cat).tolist()
    return num_names + cat_names


def entrenar_modelo(df_curso, curso, target, asignatura):
    data = df_curso.dropna(subset=features_modelo + [target, "rbd"]).copy()

    X = data[features_modelo]
    y = data[target]
    groups = data["rbd"]

    model = crear_pipeline_regresion()

    # Split agrupado por establecimiento para evitar que el mismo RBD quede simultáneamente en train y test.
    if groups.nunique() >= 5:
        splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
        train_idx, test_idx = next(splitter.split(X, y, groups=groups))
    else:
        # Fallback poco probable: si hubiese muy pocos establecimientos.
        rng = np.random.default_rng(42)
        indices = np.arange(len(data))
        rng.shuffle(indices)
        split = int(len(indices) * 0.8)
        train_idx, test_idx = indices[:split], indices[split:]

    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)

    metricas_train = calcular_metricas(y_train, y_pred_train)
    metricas_test = calcular_metricas(y_test, y_pred_test)

    # Validación cruzada agrupada por RBD en el set completo del curso/asignatura.
    cv_metricas = {"MAE_CV": np.nan, "RMSE_CV": np.nan, "R2_CV": np.nan, "R2_CV_STD": np.nan}
    n_groups = groups.nunique()
    if n_groups >= 3:
        cv = GroupKFold(n_splits=min(5, n_groups))
        scoring = {
            "MAE": "neg_mean_absolute_error",
            "MSE": "neg_mean_squared_error",
            "R2": "r2",
        }
        cv_scores = cross_validate(
            crear_pipeline_regresion(), X, y,
            groups=groups, cv=cv, scoring=scoring,
            return_train_score=False,
        )
        cv_metricas = {
            "MAE_CV": -cv_scores["test_MAE"].mean(),
            "RMSE_CV": np.sqrt(-cv_scores["test_MSE"]).mean(),
            "R2_CV": cv_scores["test_R2"].mean(),
            "R2_CV_STD": cv_scores["test_R2"].std(),
        }

    feature_names = obtener_feature_names(model)
    coefs = model.named_steps["regressor"].coef_
    coef_df = pd.DataFrame({
        "variable": feature_names,
        "coeficiente": coefs,
    }).sort_values("coeficiente", key=lambda s: s.abs(), ascending=False)

    pred_df = pd.DataFrame({
        "curso": curso,
        "curso_nombre": CURSO_NOMBRE[curso],
        "asignatura": asignatura,
        "real": y_test.values,
        "predicho": y_pred_test,
    })
    pred_df["residuo"] = pred_df["real"] - pred_df["predicho"]

    metricas = {
        "curso": curso,
        "curso_nombre": CURSO_NOMBRE[curso],
        "asignatura": asignatura,
        "n_total": len(data),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "MAE_train": metricas_train["MAE"],
        "RMSE_train": metricas_train["RMSE"],
        "R2_train": metricas_train["R2"],
        "MAE_test": metricas_test["MAE"],
        "RMSE_test": metricas_test["RMSE"],
        "R2_test": metricas_test["R2"],
        **cv_metricas,
    }

    return {
        "model": model,
        "metricas": metricas,
        "coeficientes": coef_df,
        "predicciones": pred_df,
    }

# 4.2) Entrenamiento de los 8 modelos

resultados = {}
metricas_rows = []
coef_rows = []
pred_rows = []

for curso in CURSOS_ORDEN:
    df_curso = df_modelo[df_modelo["curso"] == curso].copy()
    print(f"Entrenando modelos para {CURSO_NOMBRE[curso]}: {len(df_curso):,} registros")

    for target, asignatura, color in ASIGNATURAS:
        res = entrenar_modelo(df_curso, curso, target, asignatura)
        resultados[(curso, asignatura)] = res
        metricas_rows.append(res["metricas"])

        coef_tmp = res["coeficientes"].copy()
        coef_tmp.insert(0, "curso", curso)
        coef_tmp.insert(1, "curso_nombre", CURSO_NOMBRE[curso])
        coef_tmp.insert(2, "asignatura", asignatura)
        coef_rows.append(coef_tmp)

        pred_rows.append(res["predicciones"])

metricas_df = pd.DataFrame(metricas_rows)
coeficientes_df = pd.concat(coef_rows, ignore_index=True)
predicciones_df = pd.concat(pred_rows, ignore_index=True)

print("Modelos entrenados:", len(resultados))

"""### Formato de tablas por asignatura

Para facilitar la lectura en la presentación, las tablas de métricas y comparación se muestran separadas por asignatura. Así se comparan los cursos directamente sin mezclar Matemática y Lectura en una sola tabla extensa.

"""

# 4.3) Tabla de métricas: train, test y validación cruzada

metricas_ordenadas = metricas_df.copy()
metricas_ordenadas["curso_nombre"] = pd.Categorical(
    metricas_ordenadas["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)
metricas_ordenadas = metricas_ordenadas.sort_values(["curso_nombre", "asignatura"])

cols_metricas = [
    "curso_nombre", "asignatura", "n_total", "n_train", "n_test",
    "MAE_train", "MAE_test", "RMSE_train", "RMSE_test",
    "R2_train", "R2_test", "MAE_CV", "RMSE_CV", "R2_CV", "R2_CV_STD",
]
cols_metricas_sin_asignatura = [c for c in cols_metricas if c != "asignatura"]

for asignatura in HUE_ASIGNATURA:
    print(f"Métricas train/test y validación cruzada - {asignatura}")
    tabla_asignatura = metricas_ordenadas[metricas_ordenadas["asignatura"] == asignatura]
    display(tabla_asignatura[cols_metricas_sin_asignatura].round(3).reset_index(drop=True))

# 4.4) Visualización de desempeño por curso y asignatura

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
for ax, metric, title in zip(
    axes,
    ["MAE_test", "RMSE_test", "R2_test"],
    ["MAE test", "RMSE test", "R² test"],
):
    sns.barplot(
        data=metricas_ordenadas,
        x="curso_nombre", y=metric,
        hue="asignatura", ax=ax,
        hue_order=HUE_ASIGNATURA,
        palette=PALETA_ASIGNATURA,
    )
    ax.set_title(title)
    ax.set_xlabel("Curso")
    ax.set_ylabel(metric)
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="Asignatura")

plt.suptitle("Comparación de métricas de test por modelo")
plt.tight_layout()
plt.show()

# 4.5) Coeficientes de IDPS por curso y asignatura

coef_idps = coeficientes_df[coeficientes_df["variable"].isin(features_idps)].copy()
coef_idps["indicador"] = coef_idps["variable"].map(IDPS_NOMBRE)
coef_idps["curso_nombre"] = pd.Categorical(
    coef_idps["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)

for asignatura in ["Matemática", "Lectura"]:
    tabla_coef = coef_idps[coef_idps["asignatura"] == asignatura].pivot(
        index="indicador", columns="curso_nombre", values="coeficiente"
    )[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]
    print(f"Coeficientes IDPS estandarizados - {asignatura}")
    display(tabla_coef.round(3))

# 4.6) Evolución visual de coeficientes IDPS por curso

fig, axes = plt.subplots(1, 2, figsize=(15, 5), sharey=True)

for ax, asignatura in zip(axes, ["Matemática", "Lectura"]):
    data_plot = coef_idps[coef_idps["asignatura"] == asignatura].copy()
    sns.lineplot(
        data=data_plot,
        x="curso_nombre", y="coeficiente",
        hue="indicador", marker="o", ax=ax,
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(f"Coeficientes IDPS - {asignatura}")
    ax.set_xlabel("Curso")
    ax.set_ylabel("Coeficiente estandarizado")
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="IDPS", fontsize=8)

plt.suptitle("Comparación de asociaciones IDPS-SIMCE por curso")
plt.tight_layout()
plt.show()

"""## Importancia de variables - modelo principal

Los gráficos siguientes usan el **estilo visual del GitHub**: barras horizontales, variables ordenadas por magnitud absoluta, línea en cero, coeficientes positivos en el color de la asignatura y coeficientes negativos en gris.

La diferencia es metodológica: estos gráficos **no** reentrenan con el pipeline del GitHub. Usan los coeficientes del modelo principal del notebook, es decir, split agrupado por `rbd`, validación agrupada, `nse_ord` estandarizado y `OneHotEncoder(drop="first")`.

"""

# 4.7) Importancia de variables (estilo GitHub - modelo principal)

def preparar_coeficientes_para_grafico(coef_df, curso, asignatura):
    data_plot = coef_df[
        (coef_df["curso"] == curso)
        & (coef_df["asignatura"] == asignatura)
    ].copy()
    data_plot = data_plot.reindex(
        data_plot["coeficiente"].abs().sort_values(ascending=False).index
    )
    return data_plot


def graficar_importancia_estilo_github(coef_df, curso, asignatura, titulo_prefijo="", output_path=None):
    data_plot = preparar_coeficientes_para_grafico(coef_df, curso, asignatura)

    plt.figure(figsize=(9, 5))
    colores = [
        PALETA_ASIGNATURA[asignatura] if c > 0 else "gray"
        for c in data_plot["coeficiente"]
    ]
    plt.barh(data_plot["variable"], data_plot["coeficiente"], color=colores)
    plt.axvline(0, color="black", linewidth=0.8)
    plt.xlabel(f"Coeficiente del modelo sobre SIMCE {asignatura}")
    prefijo = f"{titulo_prefijo} - " if titulo_prefijo else ""
    plt.title(f"{prefijo}Importancia de variables — {asignatura} · {CURSO_NOMBRE[curso]}")
    plt.gca().invert_yaxis()
    plt.tight_layout()
    if output_path is not None:
        plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.show()


FIG_PRINCIPAL_DIR = Path("salidas_modelo_final") / "figuras_modelo_principal"
FIG_PRINCIPAL_DIR.mkdir(parents=True, exist_ok=True)

for curso in CURSOS_ORDEN:
    for asignatura in ["Matemática", "Lectura"]:
        nombre_asig = "mate" if asignatura == "Matemática" else "lect"
        graficar_importancia_estilo_github(
            coeficientes_df,
            curso,
            asignatura,
            output_path=FIG_PRINCIPAL_DIR / f"{nombre_asig}_{curso}_importancia.png",
        )

print(f"Figuras de importancia del modelo principal guardadas en: {FIG_PRINCIPAL_DIR.resolve()}")

# 4.7) Valores reales vs estimados y residuos

fig, axes = plt.subplots(4, 2, figsize=(12, 16), sharex=False, sharey=False)

for i, curso in enumerate(CURSOS_ORDEN):
    for j, asignatura in enumerate(["Matemática", "Lectura"]):
        ax = axes[i, j]
        p = predicciones_df[(predicciones_df["curso"] == curso) & (predicciones_df["asignatura"] == asignatura)]
        ax.scatter(p["real"], p["predicho"], alpha=0.25, s=12, color=PALETA_ASIGNATURA[asignatura])
        min_val = min(p["real"].min(), p["predicho"].min())
        max_val = max(p["real"].max(), p["predicho"].max())
        ax.plot([min_val, max_val], [min_val, max_val], "r--", linewidth=1)
        ax.set_title(f"{CURSO_NOMBRE[curso]} - {asignatura}")
        ax.set_xlabel("Real")
        ax.set_ylabel("Estimado")

plt.suptitle("Valores reales vs estimados por modelo")
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(4, 2, figsize=(12, 16), sharex=False, sharey=False)

for i, curso in enumerate(CURSOS_ORDEN):
    for j, asignatura in enumerate(["Matemática", "Lectura"]):
        ax = axes[i, j]
        p = predicciones_df[(predicciones_df["curso"] == curso) & (predicciones_df["asignatura"] == asignatura)]
        ax.hist(p["residuo"], bins=35, edgecolor="white", color=PALETA_ASIGNATURA[asignatura])
        ax.axvline(0, color="black", linestyle="--", linewidth=1)
        ax.set_title(f"Residuos: {CURSO_NOMBRE[curso]} - {asignatura}")
        ax.set_xlabel("Residuo")
        ax.set_ylabel("Frecuencia")

plt.suptitle("Distribución de residuos por modelo")
plt.tight_layout()
plt.show()

"""## Variante del modelo: análisis sin NSE

En el modelo principal se mantiene NSE como variable de control porque es una dimensión contextual relevante. Sin embargo, en Chile el nivel socioeconómico suele dominar parte importante de las diferencias educativas, por lo que puede ocultar la lectura de los IDPS.

Por eso se estima una variante del mismo modelo, quitando solo `nse_ord`:

- **Modelo principal:** IDPS + NSE + ruralidad + dependencia.
- **Modelo sin NSE:** IDPS + ruralidad + dependencia.

Esta variante no reemplaza al modelo principal. Sirve para observar cómo cambian las métricas y los coeficientes de IDPS cuando no se controla por nivel socioeconómico.

"""

# 4.8) Entrenamiento del modelo sin NSE

features_num_sin_nse = ["ind_am", "ind_cc", "ind_hv", "ind_pf"]
features_cat_sin_nse = ["cod_rural_rbd", "cod_depe2"]
features_modelo_sin_nse = features_num_sin_nse + features_cat_sin_nse


def crear_pipeline_regresion_sin_nse():
    preprocessor = ColumnTransformer(transformers=[
        ("num", StandardScaler(), features_num_sin_nse),
        ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat_sin_nse),
    ])

    return Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("regressor", LinearRegression()),
    ])


def obtener_feature_names_sin_nse(model):
    pre = model.named_steps["preprocessor"]
    num_names = pre.named_transformers_["num"].get_feature_names_out(features_num_sin_nse).tolist()
    cat_names = pre.named_transformers_["cat"].get_feature_names_out(features_cat_sin_nse).tolist()
    return num_names + cat_names


def entrenar_modelo_sin_nse(df_curso, curso, target, asignatura):
    data = df_curso.dropna(subset=features_modelo_sin_nse + [target, "rbd"]).copy()

    X = data[features_modelo_sin_nse]
    y = data[target]
    groups = data["rbd"]

    model = crear_pipeline_regresion_sin_nse()

    splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    train_idx, test_idx = next(splitter.split(X, y, groups=groups))

    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)

    metricas_train = calcular_metricas(y_train, y_pred_train)
    metricas_test = calcular_metricas(y_test, y_pred_test)

    cv_metricas = {"MAE_CV": np.nan, "RMSE_CV": np.nan, "R2_CV": np.nan, "R2_CV_STD": np.nan}
    n_groups = groups.nunique()
    if n_groups >= 3:
        cv = GroupKFold(n_splits=min(5, n_groups))
        scoring = {
            "MAE": "neg_mean_absolute_error",
            "MSE": "neg_mean_squared_error",
            "R2": "r2",
        }
        cv_scores = cross_validate(
            crear_pipeline_regresion_sin_nse(), X, y,
            groups=groups, cv=cv, scoring=scoring,
            return_train_score=False,
        )
        cv_metricas = {
            "MAE_CV": -cv_scores["test_MAE"].mean(),
            "RMSE_CV": np.sqrt(-cv_scores["test_MSE"]).mean(),
            "R2_CV": cv_scores["test_R2"].mean(),
            "R2_CV_STD": cv_scores["test_R2"].std(),
        }

    feature_names = obtener_feature_names_sin_nse(model)
    coefs = model.named_steps["regressor"].coef_
    coef_df = pd.DataFrame({
        "variable": feature_names,
        "coeficiente": coefs,
    }).sort_values("coeficiente", key=lambda s: s.abs(), ascending=False)

    pred_df = pd.DataFrame({
        "curso": curso,
        "curso_nombre": CURSO_NOMBRE[curso],
        "asignatura": asignatura,
        "real": y_test.values,
        "predicho": y_pred_test,
    })
    pred_df["residuo"] = pred_df["real"] - pred_df["predicho"]

    metricas = {
        "curso": curso,
        "curso_nombre": CURSO_NOMBRE[curso],
        "asignatura": asignatura,
        "n_total": len(data),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "MAE_train": metricas_train["MAE"],
        "RMSE_train": metricas_train["RMSE"],
        "R2_train": metricas_train["R2"],
        "MAE_test": metricas_test["MAE"],
        "RMSE_test": metricas_test["RMSE"],
        "R2_test": metricas_test["R2"],
        **cv_metricas,
    }

    return {
        "model": model,
        "metricas": metricas,
        "coeficientes": coef_df,
        "predicciones": pred_df,
    }


resultados_sin_nse = {}
metricas_sin_nse_rows = []
coef_sin_nse_rows = []
pred_sin_nse_rows = []

for curso in CURSOS_ORDEN:
    df_curso = df_modelo[df_modelo["curso"] == curso].copy()
    print(f"Entrenando modelos sin NSE para {CURSO_NOMBRE[curso]}: {len(df_curso):,} registros")

    for target, asignatura, color in ASIGNATURAS:
        res = entrenar_modelo_sin_nse(df_curso, curso, target, asignatura)
        resultados_sin_nse[(curso, asignatura)] = res
        metricas_sin_nse_rows.append(res["metricas"])

        coef_tmp = res["coeficientes"].copy()
        coef_tmp.insert(0, "curso", curso)
        coef_tmp.insert(1, "curso_nombre", CURSO_NOMBRE[curso])
        coef_tmp.insert(2, "asignatura", asignatura)
        coef_sin_nse_rows.append(coef_tmp)

        pred_sin_nse_rows.append(res["predicciones"])

metricas_sin_nse_df = pd.DataFrame(metricas_sin_nse_rows)
coeficientes_sin_nse_df = pd.concat(coef_sin_nse_rows, ignore_index=True)
predicciones_sin_nse_df = pd.concat(pred_sin_nse_rows, ignore_index=True)

print("Modelos sin NSE entrenados:", len(resultados_sin_nse))

# 4.9) Métricas del modelo sin NSE

metricas_sin_nse_ordenadas = metricas_sin_nse_df.copy()
metricas_sin_nse_ordenadas["curso_nombre"] = pd.Categorical(
    metricas_sin_nse_ordenadas["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)
metricas_sin_nse_ordenadas = metricas_sin_nse_ordenadas.sort_values(["curso_nombre", "asignatura"])

for asignatura in HUE_ASIGNATURA:
    print(f"Modelo sin NSE - Métricas train/test y validación cruzada - {asignatura}")
    tabla_asignatura = metricas_sin_nse_ordenadas[metricas_sin_nse_ordenadas["asignatura"] == asignatura]
    display(tabla_asignatura[cols_metricas_sin_asignatura].round(3).reset_index(drop=True))

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
for ax, metric, title in zip(
    axes,
    ["MAE_test", "RMSE_test", "R2_test"],
    ["MAE test", "RMSE test", "R² test"],
):
    sns.barplot(
        data=metricas_sin_nse_ordenadas,
        x="curso_nombre", y=metric,
        hue="asignatura",
        hue_order=HUE_ASIGNATURA,
        palette=PALETA_ASIGNATURA,
        ax=ax,
    )
    ax.set_title(title)
    ax.set_xlabel("Curso")
    ax.set_ylabel(metric)
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="Asignatura")

plt.suptitle("Modelo sin NSE: comparación de métricas de test")
plt.tight_layout()
plt.show()

# 4.10) Coeficientes e importancia de variables - modelo sin NSE

coef_idps_sin_nse = coeficientes_sin_nse_df[
    coeficientes_sin_nse_df["variable"].isin(features_idps)
].copy()
coef_idps_sin_nse["indicador"] = coef_idps_sin_nse["variable"].map(IDPS_NOMBRE)
coef_idps_sin_nse["curso_nombre"] = pd.Categorical(
    coef_idps_sin_nse["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)

for asignatura in ["Matemática", "Lectura"]:
    tabla_coef = coef_idps_sin_nse[coef_idps_sin_nse["asignatura"] == asignatura].pivot(
        index="indicador", columns="curso_nombre", values="coeficiente"
    )[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]
    print(f"Modelo sin NSE - Coeficientes IDPS estandarizados - {asignatura}")
    display(tabla_coef.round(3))

fig, axes = plt.subplots(1, 2, figsize=(15, 5), sharey=True)
for ax, asignatura in zip(axes, ["Matemática", "Lectura"]):
    data_plot = coef_idps_sin_nse[coef_idps_sin_nse["asignatura"] == asignatura].copy()
    sns.lineplot(
        data=data_plot,
        x="curso_nombre", y="coeficiente",
        hue="indicador", marker="o", ax=ax,
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(f"Modelo sin NSE - Coeficientes IDPS - {asignatura}")
    ax.set_xlabel("Curso")
    ax.set_ylabel("Coeficiente estandarizado")
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="IDPS", fontsize=8)

plt.suptitle("Modelo sin NSE: comparación de asociaciones IDPS-SIMCE por curso")
plt.tight_layout()
plt.show()

FIG_SIN_NSE_DIR = Path("salidas_modelo_final") / "figuras_modelo_sin_nse"
FIG_SIN_NSE_DIR.mkdir(parents=True, exist_ok=True)

for curso in CURSOS_ORDEN:
    for asignatura in ["Matemática", "Lectura"]:
        nombre_asig = "mate" if asignatura == "Matemática" else "lect"
        graficar_importancia_estilo_github(
            coeficientes_sin_nse_df,
            curso,
            asignatura,
            titulo_prefijo="Modelo sin NSE",
            output_path=FIG_SIN_NSE_DIR / f"{nombre_asig}_{curso}_importancia_sin_nse.png",
        )

print(f"Figuras de importancia del modelo sin NSE guardadas en: {FIG_SIN_NSE_DIR.resolve()}")

# 4.11) Valores reales vs estimados y residuos - Modelo sin NSE

fig, axes = plt.subplots(4, 2, figsize=(12, 16), sharex=False, sharey=False)

for i, curso in enumerate(CURSOS_ORDEN):
    for j, asignatura in enumerate(["Matemática", "Lectura"]):
        ax = axes[i, j]
        p = predicciones_sin_nse_df[
            (predicciones_sin_nse_df["curso"] == curso)
            & (predicciones_sin_nse_df["asignatura"] == asignatura)
        ]
        ax.scatter(p["real"], p["predicho"], alpha=0.25, s=12, color=PALETA_ASIGNATURA[asignatura])
        min_val = min(p["real"].min(), p["predicho"].min())
        max_val = max(p["real"].max(), p["predicho"].max())
        ax.plot([min_val, max_val], [min_val, max_val], "r--", linewidth=1)
        ax.set_title(f"Modelo sin NSE - {CURSO_NOMBRE[curso]} - {asignatura}")
        ax.set_xlabel("Real")
        ax.set_ylabel("Estimado")

plt.suptitle("Modelo sin NSE: valores reales vs estimados")
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(4, 2, figsize=(12, 16), sharex=False, sharey=False)

for i, curso in enumerate(CURSOS_ORDEN):
    for j, asignatura in enumerate(["Matemática", "Lectura"]):
        ax = axes[i, j]
        p = predicciones_sin_nse_df[
            (predicciones_sin_nse_df["curso"] == curso)
            & (predicciones_sin_nse_df["asignatura"] == asignatura)
        ]
        ax.hist(p["residuo"], bins=35, edgecolor="white", color=PALETA_ASIGNATURA[asignatura])
        ax.axvline(0, color="black", linestyle="--", linewidth=1)
        ax.set_title(f"Modelo sin NSE - Residuos: {CURSO_NOMBRE[curso]} - {asignatura}")
        ax.set_xlabel("Residuo")
        ax.set_ylabel("Frecuencia")

plt.suptitle("Modelo sin NSE: distribución de residuos")
plt.tight_layout()
plt.show()

"""## Comparación modelo principal vs modelo sin NSE

Después de revisar ambos modelos por separado, se comparan directamente sus métricas y coeficientes IDPS.

La lectura recomendada es:

- Si al quitar NSE baja el R² y sube el MAE, el NSE aportaba información explicativa relevante.
- Si al quitar NSE suben mucho los coeficientes de IDPS, parte de su asociación estaba mezclada con desigualdad socioeconómica.
- Si los coeficientes IDPS se mantienen parecidos, los IDPS muestran una asociación más estable incluso al cambiar el control por NSE.

"""

# 4.12) Comparación de métricas: modelo principal vs modelo sin NSE

metricas_con_nse_comp = metricas_ordenadas.copy()
metricas_con_nse_comp["modelo"] = "Principal"

metricas_sin_nse_comp = metricas_sin_nse_ordenadas.copy()
metricas_sin_nse_comp["modelo"] = "Sin NSE"

metricas_comp_df = pd.concat([metricas_con_nse_comp, metricas_sin_nse_comp], ignore_index=True)

for asignatura in HUE_ASIGNATURA:
    print(f"Comparación de métricas: modelo principal vs modelo sin NSE - {asignatura}")
    tabla_asignatura = metricas_comp_df[metricas_comp_df["asignatura"] == asignatura]
    display(tabla_asignatura[[
        "curso_nombre", "modelo",
        "MAE_test", "RMSE_test", "R2_test",
        "MAE_CV", "RMSE_CV", "R2_CV",
    ]].round(3).reset_index(drop=True))

metricas_wide = metricas_comp_df.pivot_table(
    index=["curso", "curso_nombre", "asignatura"],
    columns="modelo",
    values=["MAE_test", "RMSE_test", "R2_test", "MAE_CV", "RMSE_CV", "R2_CV"],
)
metricas_wide.columns = [f"{metrica}_{modelo}" for metrica, modelo in metricas_wide.columns]
metricas_wide = metricas_wide.reset_index()

metricas_wide["delta_R2_test_sin_menos_principal"] = (
    metricas_wide["R2_test_Sin NSE"] - metricas_wide["R2_test_Principal"]
)
metricas_wide["delta_MAE_test_sin_menos_principal"] = (
    metricas_wide["MAE_test_Sin NSE"] - metricas_wide["MAE_test_Principal"]
)

for asignatura in HUE_ASIGNATURA:
    print(f"Impacto de quitar NSE - {asignatura}")
    tabla_asignatura = metricas_wide[metricas_wide["asignatura"] == asignatura]
    display(tabla_asignatura[[
        "curso_nombre",
        "R2_test_Principal", "R2_test_Sin NSE", "delta_R2_test_sin_menos_principal",
        "MAE_test_Principal", "MAE_test_Sin NSE", "delta_MAE_test_sin_menos_principal",
    ]].round(3).reset_index(drop=True))

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

sns.barplot(
    data=metricas_comp_df,
    x="curso_nombre", y="R2_test",
    hue="modelo",
    ax=axes[0],
)
axes[0].set_title("R² test: modelo principal vs sin NSE")
axes[0].set_xlabel("Curso")
axes[0].set_ylabel("R² test")
axes[0].tick_params(axis="x", rotation=20)

sns.barplot(
    data=metricas_comp_df,
    x="curso_nombre", y="MAE_test",
    hue="modelo",
    ax=axes[1],
)
axes[1].set_title("MAE test: modelo principal vs sin NSE")
axes[1].set_xlabel("Curso")
axes[1].set_ylabel("MAE test")
axes[1].tick_params(axis="x", rotation=20)

plt.suptitle("Impacto de quitar NSE del modelo")
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(14, 4), sharey=True)
for ax, asignatura in zip(axes, HUE_ASIGNATURA):
    data_plot = metricas_wide[metricas_wide["asignatura"] == asignatura].copy()
    sns.barplot(
        data=data_plot,
        x="curso_nombre", y="delta_R2_test_sin_menos_principal",
        ax=ax,
        color="gray",
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(f"Cambio de R² al quitar NSE - {asignatura}")
    ax.set_xlabel("Curso")
    ax.set_ylabel("R² sin NSE - R² principal")
    ax.tick_params(axis="x", rotation=20)

plt.tight_layout()
plt.show()

# 4.13) Comparación de coeficientes IDPS: modelo principal vs modelo sin NSE

coef_idps_principal_comp = coef_idps[["curso", "curso_nombre", "asignatura", "variable", "indicador", "coeficiente"]].copy()
coef_idps_principal_comp["modelo"] = "Principal"

coef_idps_sin_nse_comp = coef_idps_sin_nse[["curso", "curso_nombre", "asignatura", "variable", "indicador", "coeficiente"]].copy()
coef_idps_sin_nse_comp["modelo"] = "Sin NSE"

coef_idps_comp = pd.concat([coef_idps_principal_comp, coef_idps_sin_nse_comp], ignore_index=True)

coef_idps_wide = coef_idps_comp.pivot_table(
    index=["curso", "curso_nombre", "asignatura", "variable", "indicador"],
    columns="modelo",
    values="coeficiente",
).reset_index()

coef_idps_wide["cambio_sin_menos_principal"] = (
    coef_idps_wide["Sin NSE"] - coef_idps_wide["Principal"]
)
coef_idps_wide["cambio_abs"] = coef_idps_wide["cambio_sin_menos_principal"].abs()

for asignatura in HUE_ASIGNATURA:
    print(f"Coeficientes IDPS: modelo principal vs modelo sin NSE - {asignatura}")
    tabla_asignatura = coef_idps_wide[coef_idps_wide["asignatura"] == asignatura]
    display(
        tabla_asignatura.sort_values(["curso", "cambio_abs"], ascending=[True, False])
        [["curso_nombre", "indicador", "Principal", "Sin NSE", "cambio_sin_menos_principal"]]
        .round(3)
        .reset_index(drop=True)
    )

for asignatura in HUE_ASIGNATURA:
    tabla_cambio = coef_idps_wide[coef_idps_wide["asignatura"] == asignatura].pivot_table(
        index="indicador",
        columns="curso_nombre",
        values="cambio_sin_menos_principal",
    )[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]
    print(f"Cambio en coeficientes IDPS al quitar NSE - {asignatura}")
    display(tabla_cambio.round(3))

fig, axes = plt.subplots(1, 2, figsize=(15, 5), sharey=True)
for ax, asignatura in zip(axes, HUE_ASIGNATURA):
    data_plot = coef_idps_wide[coef_idps_wide["asignatura"] == asignatura].copy()
    sns.barplot(
        data=data_plot,
        x="curso_nombre", y="cambio_sin_menos_principal",
        hue="indicador",
        ax=ax,
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(f"Cambio de coeficientes IDPS al quitar NSE - {asignatura}")
    ax.set_xlabel("Curso")
    ax.set_ylabel("Coef. sin NSE - coef. principal")
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="IDPS", fontsize=8)

plt.tight_layout()
plt.show()

OUTPUT_DIR = Path("salidas_modelo_final")
OUTPUT_DIR.mkdir(exist_ok=True)
metricas_sin_nse_ordenadas.to_csv(OUTPUT_DIR / "metricas_modelo_sin_nse.csv", index=False)
coeficientes_sin_nse_df.to_csv(OUTPUT_DIR / "coeficientes_modelo_sin_nse.csv", index=False)
predicciones_sin_nse_df.to_csv(OUTPUT_DIR / "predicciones_modelo_sin_nse.csv", index=False)
metricas_comp_df.to_csv(OUTPUT_DIR / "metricas_principal_vs_sin_nse.csv", index=False)
metricas_wide.to_csv(OUTPUT_DIR / "impacto_quitar_nse_metricas.csv", index=False)
coef_idps_wide.to_csv(OUTPUT_DIR / "impacto_quitar_nse_coeficientes_idps.csv", index=False)

print(f"Tablas del modelo sin NSE y comparación guardadas en: {OUTPUT_DIR.resolve()}")

"""## 4.14) Modelo global de referencia (todos los cursos juntos)

Además de los 8 modelos por curso, se ajusta un par de modelos (Matemática / Lectura) sobre
**todos los cursos a la vez**. Sirve de panorama general y de línea base para comparar contra los
modelos por curso. Se agrega `curso` como variable de control (one-hot), porque cada nivel evaluado
tiene una escala de puntajes distinta; sus coeficientes son ajustes de escala, no efectos a
interpretar. El NSE va ordinal y estandarizado, igual que en el modelo principal.
"""

# 4.14) MODELO GLOBAL — todos los cursos juntos
features_num_global = ["ind_am", "ind_cc", "ind_hv", "ind_pf", "nse_ord"]
features_cat_global = ["cod_rural_rbd", "cod_depe2", "curso"]   # curso = control de escala
features_modelo_global = features_num_global + features_cat_global


def crear_pipeline_global():
    preprocessor = ColumnTransformer(transformers=[
        ("num", StandardScaler(), features_num_global),
        ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat_global),
    ])
    return Pipeline(steps=[("preprocessor", preprocessor), ("regressor", LinearRegression())])


def obtener_feature_names_global(model):
    pre = model.named_steps["preprocessor"]
    return (pre.named_transformers_["num"].get_feature_names_out(features_num_global).tolist()
            + pre.named_transformers_["cat"].get_feature_names_out(features_cat_global).tolist())


metricas_global_rows, coef_global_rows = [], []
for target, asignatura, color in ASIGNATURAS:
    data = df_modelo.dropna(subset=features_modelo_global + [target, "rbd"]).copy()
    X, y, groups = data[features_modelo_global], data[target], data["rbd"]

    # Split agrupado por establecimiento (mismo criterio que los modelos por curso).
    train_idx, test_idx = next(
        GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42).split(X, y, groups)
    )
    model = crear_pipeline_global()
    model.fit(X.iloc[train_idx], y.iloc[train_idx])
    m_train = calcular_metricas(y.iloc[train_idx], model.predict(X.iloc[train_idx]))
    m_test = calcular_metricas(y.iloc[test_idx], model.predict(X.iloc[test_idx]))

    cv = cross_validate(crear_pipeline_global(), X, y, groups=groups, cv=GroupKFold(n_splits=5),
                        scoring={"MAE": "neg_mean_absolute_error",
                                 "MSE": "neg_mean_squared_error", "R2": "r2"})
    metricas_global_rows.append({
        "asignatura": asignatura, "n_total": len(data),
        "MAE_train": m_train["MAE"], "MAE_test": m_test["MAE"],
        "RMSE_train": m_train["RMSE"], "RMSE_test": m_test["RMSE"],
        "R2_train": m_train["R2"], "R2_test": m_test["R2"],
        "MAE_CV": -cv["test_MAE"].mean(), "RMSE_CV": np.sqrt(-cv["test_MSE"]).mean(),
        "R2_CV": cv["test_R2"].mean(), "R2_CV_STD": cv["test_R2"].std(),
    })
    coef_tmp = pd.DataFrame({"variable": obtener_feature_names_global(model),
                             "coeficiente": model.named_steps["regressor"].coef_})
    coef_tmp.insert(0, "asignatura", asignatura)
    coef_global_rows.append(coef_tmp)

metricas_global_df = pd.DataFrame(metricas_global_rows)
coeficientes_global_df = pd.concat(coef_global_rows, ignore_index=True)

print("Modelo global — métricas train/test y validación cruzada:")
display(metricas_global_df.round(3))

# Importancia de variables (se omiten del ranking los dummies de `curso`, que son controles de escala)
for asignatura in HUE_ASIGNATURA:
    c = coeficientes_global_df[coeficientes_global_df["asignatura"] == asignatura].copy()
    es_control = c["variable"].str.startswith("curso")
    interes = c[~es_control].reindex(
        c[~es_control]["coeficiente"].abs().sort_values(ascending=False).index
    )
    plt.figure(figsize=(9, 5))
    colores = [PALETA_ASIGNATURA[asignatura] if v > 0 else "gray" for v in interes["coeficiente"]]
    plt.barh(interes["variable"], interes["coeficiente"], color=colores)
    plt.axvline(0, color="black", linewidth=0.8)
    plt.gca().invert_yaxis()
    plt.title(f"Modelo global — importancia de variables · {asignatura}")
    plt.xlabel("Coeficiente sobre SIMCE")
    plt.tight_layout()
    plt.show()
    print(f"(controles de escala omitidos del ranking: {sorted(c.loc[es_control, 'variable'])})")

"""## 4.15) Modelo unificado: Matemática + Lectura con `tipo_prueba`

Atendiendo el feedback del profesor, se integra un modelo que **no** separa por completo Matemática
y Lectura. Se apilan ambas pruebas en una sola variable objetivo (`puntaje_simce`) y se agrega
`tipo_prueba` como predictor categórico. Así el modelo comparte la estructura común de ambas
asignaturas y el coeficiente de `tipo_prueba` mide la **brecha sistemática** entre ellas. La
partición es agrupada por establecimiento (`rbd`) para que Matemática y Lectura del mismo colegio no
queden a ambos lados del split.
"""

# 4.15) MODELO UNIFICADO mate+lect con `tipo_prueba`
df_unif = df_modelo.melt(
    id_vars=["rbd", "agno", "curso", "nse_ord", "cod_rural_rbd", "cod_depe2",
             "ind_am", "ind_cc", "ind_hv", "ind_pf"],
    value_vars=targets, var_name="_col", value_name="puntaje_simce",
)
df_unif["tipo_prueba"] = df_unif["_col"].map(
    {"prom_mate2m_rbd": "Matemática", "prom_lect2m_rbd": "Lectura"}
)
df_unif = df_unif.dropna(subset=["puntaje_simce"]).reset_index(drop=True)
print(f"Formato largo: {len(df_modelo):,} filas anchas -> {len(df_unif):,} filas largas")

features_num_unif = ["ind_am", "ind_cc", "ind_hv", "ind_pf", "nse_ord"]
features_cat_unif = ["cod_rural_rbd", "cod_depe2", "curso", "tipo_prueba"]
features_modelo_unif = features_num_unif + features_cat_unif


def crear_pipeline_unif():
    preprocessor = ColumnTransformer(transformers=[
        ("num", StandardScaler(), features_num_unif),
        ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat_unif),
    ])
    return Pipeline(steps=[("preprocessor", preprocessor), ("regressor", LinearRegression())])


X, y, groups = df_unif[features_modelo_unif], df_unif["puntaje_simce"], df_unif["rbd"]
train_idx, test_idx = next(
    GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42).split(X, y, groups)
)
model_unif = crear_pipeline_unif()
model_unif.fit(X.iloc[train_idx], y.iloc[train_idx])
m_train = calcular_metricas(y.iloc[train_idx], model_unif.predict(X.iloc[train_idx]))
m_test = calcular_metricas(y.iloc[test_idx], model_unif.predict(X.iloc[test_idx]))
cv = cross_validate(crear_pipeline_unif(), X, y, groups=groups, cv=GroupKFold(n_splits=5),
                    scoring={"MAE": "neg_mean_absolute_error",
                             "MSE": "neg_mean_squared_error", "R2": "r2"})

print("Modelo unificado — métricas:")
display(pd.DataFrame([
    {"split": "train", **m_train},
    {"split": "test", **m_test},
    {"split": "CV (GroupKFold 5)", "MAE": -cv["test_MAE"].mean(),
     "RMSE": np.sqrt(-cv["test_MSE"]).mean(), "R2": cv["test_R2"].mean()},
]).round(3))

pre = model_unif.named_steps["preprocessor"]
nombres_unif = (pre.named_transformers_["num"].get_feature_names_out(features_num_unif).tolist()
                + pre.named_transformers_["cat"].get_feature_names_out(features_cat_unif).tolist())
coef_unif = pd.DataFrame({"variable": nombres_unif,
                          "coeficiente": model_unif.named_steps["regressor"].coef_})
coef_unif = coef_unif.reindex(coef_unif["coeficiente"].abs().sort_values(ascending=False).index)

print("Coeficientes del modelo unificado:")
display(coef_unif.round(3).reset_index(drop=True))
print("Coeficiente de `tipo_prueba` (brecha entre asignaturas; categoría de referencia = Lectura):")
display(coef_unif[coef_unif["variable"].str.startswith("tipo_prueba")].round(3))

"""# 5) Anexo predictivo — desfase temporal T-1 (out-of-time)

El análisis principal de este notebook es **contemporáneo** (IDPS y SIMCE del mismo año → asociación).
Para responder la observación sobre predicción real, se agrega un anexo con **desfase temporal
explícito**: los predictores se miden en el año **T-1** y el target (SIMCE) en el año **T**. La
partición es *out-of-time*: se entrena con años pasados y se evalúa en el último año disponible
(2025), que el modelo nunca ve durante el ajuste. Se comparan dos conjuntos de predictores:

- **Solo IDPS:** aísla el aporte socioemocional previo.
- **Autorregresivo:** agrega el SIMCE del año anterior (`simce_*_prev`), que aporta la mayor
  capacidad predictiva.

Por el desfase estricto T-1, solo sobreviven los cursos evaluados de forma anual (`4b` y `2m`).
"""

# 6) ANEXO PREDICTIVO — desfase T-1 (requiere dataset_maestro.csv subido a Colab)
from pathlib import Path


def encontrar_maestro():
    candidatos = [Path("dataset_maestro.csv"), Path("/content/dataset_maestro.csv"),
                  Path("data/processed/dataset_maestro.csv"),
                  Path("/content/data/processed/dataset_maestro.csv")]
    for c in candidatos:
        if c.exists():
            return c
    for raiz in [Path.cwd(), Path("/content")]:
        if raiz.exists():
            for hit in raiz.rglob("dataset_maestro.csv"):
                return hit
    raise FileNotFoundError("Sube dataset_maestro.csv a /content (o a la carpeta de datos).")


df_pred = pd.read_csv(encontrar_maestro())
print(f"dataset_maestro: {df_pred.shape[0]:,} filas | "
      f"años {sorted(df_pred['agno'].unique())} | cursos {sorted(df_pred['curso'].unique())}")

FEAT_CAT_PRED = ["cod_rural_rbd", "cod_depe2"]
FEAT_NUM_IDPS = ["idps_am_prev", "idps_cc_prev", "idps_hv_prev", "idps_pf_prev", "nse_ord", "curso_ord"]
FEAT_NUM_AR = FEAT_NUM_IDPS + ["simce_mate_prev", "simce_lect_prev"]
TARGETS_PRED = {"Matemática": "target_mate", "Lectura": "target_lect"}
ANIOS_TRAIN, ANIO_TEST = [2017, 2018, 2023, 2024], 2025

cols_pred = list(dict.fromkeys(FEAT_NUM_AR + FEAT_CAT_PRED + list(TARGETS_PRED.values()) + ["agno"]))
df_pred = df_pred.dropna(subset=cols_pred).reset_index(drop=True)
train_pred = df_pred[df_pred["agno"].isin(ANIOS_TRAIN)]
test_pred = df_pred[df_pred["agno"] == ANIO_TEST]
print(f"Train (años {ANIOS_TRAIN}): {len(train_pred):,} | Test (año {ANIO_TEST}): {len(test_pred):,}")


def crear_pipeline_pred(feat_num, feat_cat):
    preprocessor = ColumnTransformer(transformers=[
        ("num", StandardScaler(), feat_num),
        ("cat", OneHotEncoder(handle_unknown="ignore"), feat_cat),
    ])
    return Pipeline(steps=[("preprocessor", preprocessor), ("regressor", LinearRegression())])


filas_pred = []
for asignatura, target in TARGETS_PRED.items():
    for nombre, feat_num in [("Solo IDPS", FEAT_NUM_IDPS), ("Autorregresivo", FEAT_NUM_AR)]:
        pipe = crear_pipeline_pred(feat_num, FEAT_CAT_PRED)
        pipe.fit(train_pred[feat_num + FEAT_CAT_PRED], train_pred[target])
        m_tr = calcular_metricas(train_pred[target], pipe.predict(train_pred[feat_num + FEAT_CAT_PRED]))
        m_te = calcular_metricas(test_pred[target], pipe.predict(test_pred[feat_num + FEAT_CAT_PRED]))
        filas_pred.append({"asignatura": asignatura, "modelo": nombre,
                           "MAE_train": m_tr["MAE"], "MAE_test": m_te["MAE"],
                           "RMSE_test": m_te["RMSE"], "R2_train": m_tr["R2"], "R2_test": m_te["R2"]})

metricas_pred_df = pd.DataFrame(filas_pred)
print("Predictivo T-1 — Train vs Test (out-of-time, test = 2025):")
display(metricas_pred_df.round(3))

"""---
# 5) iNTERPRET: Comparación e interpretación

Esta sección resume los resultados principales para conectarlos con el problema inicial y con la rúbrica de la Presentación 2.

"""

# 5.1) Ranking automático de IDPS con mayor asociación absoluta por modelo

top_idps = (
    coef_idps.assign(abs_coef=lambda x: x["coeficiente"].abs())
    .sort_values(["curso_nombre", "asignatura", "abs_coef"], ascending=[True, True, False])
    .groupby(["curso", "curso_nombre", "asignatura"], as_index=False)
    .head(1)
    [["curso_nombre", "asignatura", "indicador", "coeficiente"]]
)

display(top_idps.round(3))

# 5.2) Brecha train-test para revisar estabilidad

brechas = metricas_ordenadas[["curso_nombre", "asignatura", "MAE_train", "MAE_test", "R2_train", "R2_test"]].copy()
brechas["brecha_MAE_test_minus_train"] = brechas["MAE_test"] - brechas["MAE_train"]
brechas["brecha_R2_train_minus_test"] = brechas["R2_train"] - brechas["R2_test"]
display(brechas.round(3))

"""## Síntesis interpretativa

Las tablas anteriores pertenecen a la etapa de modelamiento. En esta sección se resume qué significan los resultados para responder la pregunta del proyecto.

El foco interpretativo está en tres puntos:

1. Qué tan estable es el desempeño del modelo por curso y asignatura.
2. Qué variables dominan la explicación del SIMCE.
3. Qué cambia cuando se quita NSE para observar mejor los IDPS.

"""

# 5.3) Síntesis interpretativa del modelo principal y la variante sin NSE

print("Desempeño promedio del modelo principal por asignatura:")
display(
    metricas_ordenadas.groupby("asignatura")[["MAE_test", "RMSE_test", "R2_test", "MAE_CV", "RMSE_CV", "R2_CV"]]
    .mean()
    .round(3)
)

print("Mejor y peor R² test del modelo principal:")
ranking_r2 = metricas_ordenadas.sort_values("R2_test", ascending=False)[
    ["curso_nombre", "asignatura", "MAE_test", "RMSE_test", "R2_test"]
]
display(ranking_r2.round(3))

print("Top 5 variables por magnitud absoluta en cada modelo principal:")
top_variables_principal = (
    coeficientes_df.assign(abs_coef=lambda x: x["coeficiente"].abs())
    .sort_values(["curso", "asignatura", "abs_coef"], ascending=[True, True, False])
    .groupby(["curso", "curso_nombre", "asignatura"], as_index=False)
    .head(5)
    [["curso_nombre", "asignatura", "variable", "coeficiente"]]
)
display(top_variables_principal.round(3))

if "metricas_wide" in globals():
    print("Impacto de quitar NSE en métricas:")
    display(metricas_wide[[
        "curso_nombre", "asignatura",
        "R2_test_Principal", "R2_test_Sin NSE", "delta_R2_test_sin_menos_principal",
        "MAE_test_Principal", "MAE_test_Sin NSE", "delta_MAE_test_sin_menos_principal",
    ]].round(3))

if "coef_idps_wide" in globals():
    print("Mayores cambios en coeficientes IDPS al quitar NSE:")
    display(
        coef_idps_wide.sort_values("cambio_abs", ascending=False)
        [["curso_nombre", "asignatura", "indicador", "Principal", "Sin NSE", "cambio_sin_menos_principal"]]
        .head(12)
        .round(3)
    )

"""### Guía para redactar la interpretación final

Después de ejecutar el notebook, completa las conclusiones usando estos criterios:

- Si II medio presenta mayor R², se puede decir que las variables disponibles explican mejor la variabilidad SIMCE en ese nivel que en básica.
- Si `nse_ord` aparece entre las variables más grandes, es consistente con la desigualdad educativa chilena y justifica la variante sin NSE.
- Si al quitar NSE aumentan los coeficientes IDPS, parte de su asociación estaba mediada o mezclada con el contexto socioeconómico.
- Si `ind_cc` mantiene coeficientes altos en ambos modelos, puede defenderse como el IDPS más estable.
- Si `ind_pf` cambia de signo o queda cerca de cero, debe interpretarse con cautela y no como efecto causal.

"""

# 5.4) Guardar tablas principales para la presentación

OUTPUT_DIR = Path("salidas_modelo_final")
OUTPUT_DIR.mkdir(exist_ok=True)

metricas_ordenadas[cols_metricas].to_csv(OUTPUT_DIR / "metricas_modelo_final.csv", index=False)
coeficientes_df.to_csv(OUTPUT_DIR / "coeficientes_modelo_final.csv", index=False)
coef_idps.to_csv(OUTPUT_DIR / "coeficientes_idps_modelo_final.csv", index=False)
skewness_df.to_csv(OUTPUT_DIR / "skewness_por_curso.csv", index=False)
vif_df.to_csv(OUTPUT_DIR / "vif_por_curso.csv", index=False)

if "metricas_sin_nse_ordenadas" in globals():
    metricas_sin_nse_ordenadas.to_csv(OUTPUT_DIR / "metricas_modelo_sin_nse.csv", index=False)
    coeficientes_sin_nse_df.to_csv(OUTPUT_DIR / "coeficientes_modelo_sin_nse.csv", index=False)
    metricas_comp_df.to_csv(OUTPUT_DIR / "metricas_principal_vs_sin_nse.csv", index=False)
    metricas_wide.to_csv(OUTPUT_DIR / "impacto_quitar_nse_metricas.csv", index=False)
    coef_idps_wide.to_csv(OUTPUT_DIR / "impacto_quitar_nse_coeficientes_idps.csv", index=False)

print(f"Tablas guardadas en: {OUTPUT_DIR.resolve()}")

"""## Comparación de iteraciones

| Iteración | Qué hacía | Limitación principal | Qué se mejora en el modelo final |
|---|---|---|---|
| `DataScienceProyecto1` | Regresión lineal para Matemática y Lectura por separado sobre dataset provisorio. | No incorpora cursos ni dataset final consolidado. | Se usa dataset final por curso y se comparan 8 modelos. |
| `ModeloUnificado_beta` | Integra Matemática y Lectura en formato largo con `tipo_prueba`. Mejora la narrativa descriptivo-explicativa. | El modelo unificado dificulta comparar directamente cómo cambian los IDPS por asignatura y curso. | Se separa por curso y asignatura para interpretar coeficientes de forma más clara. |
| `ModeloFinal_beta` | Regresión lineal múltiple por curso y asignatura usando datasets finales del GitHub. | Sigue siendo contemporáneo; no prueba causalidad ni predicción futura. | Responde mejor a la pregunta educativa y a la rúbrica de iteración, validación e interpretación. |

## Justificación del modelo final

Se selecciona el enfoque de **8 regresiones lineales múltiples** porque:

- mantiene la interpretabilidad de los coeficientes;
- evita mezclar niveles educativos distintos en un solo ajuste;
- permite comparar Matemática vs Lectura;
- permite observar si la asociación entre IDPS y SIMCE cambia entre 4° básico, 6° básico, 8° básico e II medio;
- responde directamente a la hipótesis trabajada en el GitHub.

## Conclusiones a completar después de ejecutar

Después de ejecutar el notebook, completar esta sección con los resultados observados:

1. **Desempeño general:** indicar qué cursos/asignaturas obtienen mejor y peor R², y cómo se comportan MAE/RMSE.
2. **IDPS más asociados:** describir qué indicadores aparecen con mayor coeficiente absoluto en Matemática y Lectura.
3. **Comparación por curso:** explicar si la asociación de los IDPS cambia entre básica y media.
4. **Variables contextuales:** comentar el rol del NSE, dependencia administrativa y ruralidad.
5. **Conexión con el problema:** explicar qué sugieren los resultados sobre la relación entre desarrollo personal/social y rendimiento SIMCE.

## Limitaciones

- Los coeficientes representan asociaciones, no causalidad.
- El análisis principal es contemporáneo: IDPS y SIMCE corresponden al mismo año.
- Si se quisiera afirmar predicción futura, habría que usar un dataset con desfase temporal explícito, por ejemplo IDPS en `T-1` para estimar SIMCE en `T`.
- Los indicadores IDPS pueden presentar multicolinealidad, por lo que los coeficientes individuales deben interpretarse con cautela.
- Los resultados dependen de la disponibilidad histórica de SIMCE por curso; no todos los cursos tienen los mismos años evaluados.

---
# Anexo opcional: dataset histórico completo

El archivo `dataset_historico_completo.csv` queda disponible como respaldo para un análisis global si los resultados por curso no fueran satisfactorios o si se quisiera comparar contra un modelo con todos los cursos juntos.

No se usa en el flujo principal porque la decisión metodológica final es comparar cursos y asignaturas por separado.
"""

# Anexo opcional: cargar dataset completo solo si se necesita comparar contra un modelo global.
# No ejecutar como parte del flujo principal de la Presentación 2.

# path_completo = DATA_PATH / "dataset_historico_completo.csv"
# if path_completo.exists():
#     df_completo = pd.read_csv(path_completo)
#     print(df_completo.shape)
#     display(df_completo.head())