# -*- coding: utf-8 -*-
"""notebook_presentacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jZz-jpoDFBbFkEwx1Vc5JcydMU4G8grG

# Análisis del desempeño académico SIMCE mediante IDPS y variables contextuales
## Presentación 2 — Modelo final

Este notebook estudia **cómo se asocian los Indicadores de Desarrollo Personal y
Social (IDPS), junto con variables contextuales, con los resultados SIMCE de
Matemática y Lectura según el nivel educativo evaluado**.

## Evolución metodológica respecto a la Presentación 1

En la Presentación 1 se usó un primer modelo de regresión lineal múltiple sobre un
dataset provisorio. Ya separaba Matemática y Lectura, pero no incorporaba el dataset
final ni distinguía los cursos evaluados. A partir del feedback del profesor se
realizaron ajustes importantes:

- Se reformuló el enfoque para **no** presentar el modelo como predicción futura
  cuando las variables IDPS y SIMCE pertenecen al mismo período.
- Se probó una iteración intermedia que integraba Matemática y Lectura en una sola
  variable objetivo usando `tipo_prueba` como variable explicativa.
- Se mejoró la narrativa hacia un análisis **descriptivo-explicativo**, centrado en
  asociaciones y no en causalidad.
- Se incorporó la necesidad de comparar resultados, validar train/test y justificar
  las métricas (MAE, RMSE, R²).

Para esta entrega se adopta el enfoque por curso: **modelos separados por curso y
asignatura**, lo que permite comparar si los IDPS se asocian de manera distinta con
el SIMCE según el nivel escolar y según Matemática o Lectura.

## Pregunta de investigación

¿Qué relación existe entre los IDPS, las variables contextuales de los establecimientos
y los puntajes SIMCE de Matemática y Lectura, considerando diferencias entre cursos?

## Objetivo general

Analizar la asociación entre IDPS, variables contextuales y resultados SIMCE por
establecimiento, diferenciando por curso y asignatura, para identificar qué variables
se relacionan con mayores o menores puntajes en Matemática y Lectura.

## Enfoque OSEMN

1. **Obtain:** carga del dataset final por curso.
2. **Scrub:** revisión de nulos, categorías, rangos y outliers por curso.
3. **Explore:** análisis descriptivo y correlaciones.
4. **Model:** regresión lineal múltiple por curso y asignatura.
5. **iNterpret:** comparación de métricas, coeficientes e interpretación educativa.

> El enfoque principal es **contemporáneo**: estudia asociaciones del mismo período, no
> afirma causalidad ni predicción futura. Al final se agrega un anexo predictivo con
> desfase temporal explícito (T-1) para mostrar predicción real.
"""

# 0) Imports y configuración
import warnings
warnings.filterwarnings("ignore")
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

try:
    from IPython.display import display
except ImportError:                      # permite correr como script fuera de Colab
    display = print

from sklearn.model_selection import GroupShuffleSplit, GroupKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

sns.set_theme(style="whitegrid", context="notebook")
pd.set_option("display.max_columns", 100)

DATA_DIR = Path("/content")              # en Colab los CSV van a /content
CURSOS = ["4b", "6b", "8b", "2m"]
CURSO_NOMBRE = {"4b": "4° básico", "6b": "6° básico", "8b": "8° básico", "2m": "II medio"}
IDPS_NOMBRE = {"ind_am": "Autoestima", "ind_cc": "Convivencia",
               "ind_hv": "Hábitos", "ind_pf": "Participación"}
ASIGNATURAS = [("prom_mate2m_rbd", "Matemática"), ("prom_lect2m_rbd", "Lectura")]
PALETA = {"Matemática": "steelblue", "Lectura": "coral"}
FEATURES_IDPS = ["ind_am", "ind_cc", "ind_hv", "ind_pf"]
TARGETS = ["prom_mate2m_rbd", "prom_lect2m_rbd"]

"""# 1) OBTAIN — Carga de datos finales

Se usan los cuatro datasets por curso consolidados desde el pipeline del proyecto
(`dataset_historico_{4b,6b,8b,2m}.csv`). Cada archivo contiene puntajes SIMCE, IDPS y
variables contextuales por establecimiento (`rbd`), año (`agno`) y curso (`curso`).
"""

# 1.1) Carga
def cargar_datos(data_dir=DATA_DIR):
    rutas = {c: data_dir / f"dataset_historico_{c}.csv" for c in CURSOS}
    faltan = [str(p) for p in rutas.values() if not p.exists()]
    if faltan:                            # fallback: buscar bajo /content y el cwd
        for raiz in [Path.cwd(), Path("/content")]:
            hit = next(raiz.rglob("dataset_historico_4b.csv"), None) if raiz.exists() else None
            if hit:
                return cargar_datos(hit.parent)
        raise FileNotFoundError(f"No encontré los CSV por curso. Faltan: {faltan}")
    partes = []
    for c in CURSOS:
        t = pd.read_csv(rutas[c])
        print(f"  dataset_historico_{c}.csv: {t.shape[0]:,} filas × {t.shape[1]} columnas")
        partes.append(t)
    return pd.concat(partes, ignore_index=True)


df_raw = cargar_datos()
print(f"\nDataset unido: {df_raw.shape[0]:,} filas × {df_raw.shape[1]} columnas")
display(df_raw.head())

# 1.2) Panorama inicial (registros, años, cobertura)
print("Años disponibles:", sorted(df_raw["agno"].dropna().unique()))
print("\nRegistros por curso:")
display(df_raw["curso"].astype(str).str.strip().value_counts()
        .reindex(CURSOS).rename(index=CURSO_NOMBRE).to_frame("n_registros"))
print("Registros por año y curso:")
display(pd.crosstab(df_raw["agno"], df_raw["curso"].astype(str).str.strip()).reindex(columns=CURSOS))

"""# 2) SCRUB — Limpieza y preparación

El dataset ya viene consolidado. Aquí se estandarizan categorías (NSE, dependencia,
ruralidad), se revisan nulos y rangos, y se tratan outliers por curso. También se
codifica el NSE como variable **ordinal**, respondiendo al feedback de la Presentación 1.

## Nota: codificación ordinal del NSE

`cod_grupo` representa el nivel socioeconómico del establecimiento y tiene un orden
natural: `Bajo < Medio bajo < Medio < Medio alto < Alto`. Por eso se crea `nse_ord`
(1 a 5) respetando ese orden. Es la misma idea que `OrdinalEncoder`, pero explícita y
fácil de defender. En el modelo `nse_ord` se estandariza junto con los IDPS, así su
coeficiente es comparable en magnitud con ellos (cambio en SIMCE por una desviación
estándar de NSE).
"""

# 2.1) Normalización de categorías y NSE ordinal
NSE_MAP = {**{k: "Bajo" for k in ["1", "1.0", "Bajo"]},
           **{k: "Medio bajo" for k in ["2", "2.0", "Medio bajo"]},
           **{k: "Medio" for k in ["3", "3.0", "Medio"]},
           **{k: "Medio alto" for k in ["4", "4.0", "Medio alto"]},
           **{k: "Alto" for k in ["5", "5.0", "Alto"]}}
NSE_ORD = {"Bajo": 1, "Medio bajo": 2, "Medio": 3, "Medio alto": 4, "Alto": 5}
COLS_REQ = ["rbd", "agno", "curso", *TARGETS, "cod_grupo", "nse_ord",
            "cod_rural_rbd", "cod_depe2", *FEATURES_IDPS]


def preparar(df):
    df = df.copy()
    for c in ["cod_grupo", "cod_depe2", "cod_rural_rbd", "curso"]:
        df[c] = df[c].astype(str).str.strip()
    df["cod_grupo"] = df["cod_grupo"].replace(NSE_MAP)
    df["nse_ord"] = df["cod_grupo"].map(NSE_ORD)
    for c in ["rbd", "agno", *TARGETS, *FEATURES_IDPS, "nse_ord"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")
    df["curso_nombre"] = df["curso"].map(CURSO_NOMBRE)
    return df


df_prep = preparar(df_raw)
print("Categorías detectadas:")
for col in ["cod_grupo", "cod_rural_rbd", "cod_depe2", "curso"]:
    print(f"- {col}: {sorted(df_prep[col].dropna().unique())}")

print("\nNulos por columna relevante:")
display(df_prep[COLS_REQ].isna().sum().to_frame("nulos"))

df_scrub = df_prep.dropna(subset=COLS_REQ).copy()
print(f"Filas: {len(df_prep):,} → tras dropna: {len(df_scrub):,} "
      f"({len(df_prep) - len(df_scrub):,} eliminadas)")

# 2.2) Revisión de rangos por curso
print("Rangos (min / mean / max) de puntajes e IDPS por curso:")
display(df_scrub.groupby("curso")[TARGETS + FEATURES_IDPS]
        .agg(["min", "mean", "max"]).reindex(CURSOS).rename(index=CURSO_NOMBRE).round(2))

"""## Nota: análisis de simetría (skewness)

El feedback de la Presentación 1 pidió revisar la simetría de las variables. Regla de
lectura: `|s|<0.5` aprox. simétrica · `0.5≤|s|<1` asimetría moderada · `|s|≥1` alta.
No cambia el modelo automáticamente, pero justifica si las variables son razonables
para una regresión lineal.
"""

# 2.3) Skewness por curso
skew_tbl = (df_scrub.groupby("curso")[TARGETS + FEATURES_IDPS].skew()
            .reindex(CURSOS).rename(index=CURSO_NOMBRE).round(3))
print("Skewness por curso (puntajes e IDPS):")
display(skew_tbl)

"""## Nota: outliers por IQR calculado dentro de cada curso

El rango intercuartílico (IQR) se calcula **por curso** porque mezclar 4° básico, 6°,
8° e II medio puede marcar como outlier un valor que solo pertenece a otra escala de
comparación educativa. Se filtran los puntajes SIMCE fuera de `[Q1−1.5·IQR, Q3+1.5·IQR]`.
"""

# 2.4) Filtro de outliers IQR por curso
def quitar_outliers_iqr(df):
    keep = pd.Series(True, index=df.index)
    for _, g in df.groupby("curso"):
        kc = pd.Series(True, index=g.index)
        for col in TARGETS:
            q1, q3 = g[col].quantile(0.25), g[col].quantile(0.75)
            iqr = q3 - q1
            kc &= g[col].between(q1 - 1.5 * iqr, q3 + 1.5 * iqr)
        keep.loc[g.index] = kc
    return df.loc[keep].copy()


df_modelo = quitar_outliers_iqr(df_scrub)
print(f"Filas: {len(df_scrub):,} → tras IQR: {len(df_modelo):,} "
      f"({len(df_scrub) - len(df_modelo):,} eliminadas)")
display(df_modelo.groupby("curso_nombre").size().reindex(
    [CURSO_NOMBRE[c] for c in CURSOS]).to_frame("registros_finales"))

"""## Multicolinealidad entre IDPS (VIF)

VIF<5 indica que no hay redundancia grave entre los IDPS; aun así los coeficientes
individuales se interpretan con cautela.
"""

# 2.5) VIF por curso
def vif(df_num):
    filas = []
    for col in df_num.columns:
        X = df_num.drop(columns=col)
        r2 = LinearRegression().fit(X, df_num[col]).score(X, df_num[col])
        filas.append({"variable": IDPS_NOMBRE.get(col, col),
                      "VIF": np.inf if 1 - r2 < 1e-12 else 1 / (1 - r2)})
    return pd.DataFrame(filas)


vif_tbl = pd.concat([vif(df_modelo[df_modelo["curso"] == c][FEATURES_IDPS]).assign(
    curso=CURSO_NOMBRE[c]) for c in CURSOS], ignore_index=True)
print("VIF de los IDPS por curso:")
display(vif_tbl.pivot(index="variable", columns="curso", values="VIF")
        [[CURSO_NOMBRE[c] for c in CURSOS]].round(2))

"""# 3) EXPLORE — Análisis descriptivo

Se compara la distribución de SIMCE entre cursos, la correlación global entre SIMCE,
IDPS y NSE, y la correlación IDPS↔SIMCE dentro de cada curso. Esto verifica si tiene
sentido modelar cada nivel por separado.
"""

# 3.1) Distribución de SIMCE por curso y matriz de correlación global
plot_df = df_modelo.melt(id_vars=["curso_nombre"], value_vars=TARGETS,
                         var_name="_c", value_name="puntaje")
plot_df["asignatura"] = plot_df["_c"].map(dict(ASIGNATURAS))
plot_df["curso_nombre"] = pd.Categorical(
    plot_df["curso_nombre"], [CURSO_NOMBRE[c] for c in CURSOS], ordered=True)

plt.figure(figsize=(10, 4.5))
sns.boxplot(data=plot_df, x="curso_nombre", y="puntaje", hue="asignatura", palette=PALETA)
plt.title("Distribución de puntajes SIMCE por curso y asignatura")
plt.xlabel("Curso"); plt.ylabel("Puntaje SIMCE"); plt.tight_layout(); plt.show()

corr_labels = {"prom_mate2m_rbd": "Matemática", "prom_lect2m_rbd": "Lectura",
               "ind_am": "Autoestima", "ind_cc": "Convivencia", "ind_hv": "Hábitos",
               "ind_pf": "Participación", "nse_ord": "NSE"}
plt.figure(figsize=(8, 6))
sns.heatmap(df_modelo[list(corr_labels)].corr().rename(index=corr_labels, columns=corr_labels),
            annot=True, fmt=".2f", cmap="coolwarm", center=0, square=True)
plt.title("Correlación global: SIMCE, IDPS y NSE"); plt.tight_layout(); plt.show()

# 3.2) Correlación IDPS ↔ SIMCE por curso (tablas)
filas_corr = []
for curso in CURSOS:
    g = df_modelo[df_modelo["curso"] == curso]
    for idps in FEATURES_IDPS:
        for target, asig in ASIGNATURAS:
            filas_corr.append({"indicador": IDPS_NOMBRE[idps], "asignatura": asig,
                               "curso": CURSO_NOMBRE[curso], "corr": g[idps].corr(g[target])})
corr_idps_simce = pd.DataFrame(filas_corr)
for asig in ["Matemática", "Lectura"]:
    print(f"Correlación IDPS ↔ SIMCE — {asig}")
    display(corr_idps_simce[corr_idps_simce["asignatura"] == asig]
            .pivot(index="indicador", columns="curso", values="corr")
            [[CURSO_NOMBRE[c] for c in CURSOS]].round(3))

"""# 4) MODEL — Regresión lineal múltiple por curso y asignatura

Se entrenan **8 modelos** (4 cursos × 2 asignaturas: Matemática y Lectura). Este
enfoque permite comparar directamente los coeficientes de IDPS entre niveles y
asignaturas.

## Variables del modelo
**Targets:** `prom_mate2m_rbd` (Matemática), `prom_lect2m_rbd` (Lectura).
**Predictores:** IDPS (`ind_am`, `ind_cc`, `ind_hv`, `ind_pf`) + NSE ordinal
estandarizado (`nse_ord`) + ruralidad (`cod_rural_rbd`) + dependencia (`cod_depe2`).
Los IDPS y `nse_ord` se estandarizan para que sus coeficientes sean comparables;
ruralidad y dependencia van con one-hot (coeficientes = diferencia vs categoría base).

## Decisiones metodológicas de esta iteración
Respecto al primer modelo, se ajusta la validación para hacerla más defendible:
- **Split agrupado por `rbd`:** un mismo establecimiento no aparece a la vez en train y test.
- **Validación cruzada agrupada (GroupKFold):** evalúa estabilidad respetando la unidad establecimiento.
- **NSE ordinal estandarizado:** permite comparar su magnitud con los IDPS.
- **One-hot con categoría base (`drop="first"`):** evita redundancia entre categorías.
"""

# 4.1) Funciones de modelado (reutilizables: principal y sin NSE)
def metricas(yr, yp):
    return {"MAE": mean_absolute_error(yr, yp),
            "RMSE": np.sqrt(mean_squared_error(yr, yp)), "R2": r2_score(yr, yp)}


def pipeline(feat_num, feat_cat):
    pre = ColumnTransformer([("num", StandardScaler(), feat_num),
                             ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), feat_cat)])
    return Pipeline([("pre", pre), ("reg", LinearRegression())])


def correr_por_curso(feat_num, feat_cat):
    """Devuelve (métricas, coeficientes) para los 8 modelos curso×asignatura."""
    met, coef = [], []
    for curso in CURSOS:
        d = df_modelo[df_modelo["curso"] == curso]
        for target, asig in ASIGNATURAS:
            data = d.dropna(subset=feat_num + feat_cat + [target, "rbd"])
            X, y, g = data[feat_num + feat_cat], data[target], data["rbd"]
            tr, te = next(GroupShuffleSplit(1, test_size=0.2, random_state=42).split(X, y, g))
            m = pipeline(feat_num, feat_cat).fit(X.iloc[tr], y.iloc[tr])
            mtr = metricas(y.iloc[tr], m.predict(X.iloc[tr]))
            mte = metricas(y.iloc[te], m.predict(X.iloc[te]))
            r2cv = cross_validate(pipeline(feat_num, feat_cat), X, y, groups=g,
                                  cv=GroupKFold(5), scoring="r2")["test_score"].mean()
            met.append({"curso": CURSO_NOMBRE[curso], "asignatura": asig, "n": len(data),
                        "MAE_train": mtr["MAE"], "MAE_test": mte["MAE"],
                        "RMSE_test": mte["RMSE"], "R2_train": mtr["R2"],
                        "R2_test": mte["R2"], "R2_CV": r2cv})
            nombres = (m.named_steps["pre"].named_transformers_["num"].get_feature_names_out(feat_num).tolist()
                       + m.named_steps["pre"].named_transformers_["cat"].get_feature_names_out(feat_cat).tolist())
            for v, c in zip(nombres, m.named_steps["reg"].coef_):
                coef.append({"curso": CURSO_NOMBRE[curso], "asignatura": asig, "variable": v, "coef": c})
    return pd.DataFrame(met), pd.DataFrame(coef)


FEAT_NUM = ["ind_am", "ind_cc", "ind_hv", "ind_pf", "nse_ord"]
FEAT_CAT = ["cod_rural_rbd", "cod_depe2"]
met_principal, coef_principal = correr_por_curso(FEAT_NUM, FEAT_CAT)
orden = [CURSO_NOMBRE[c] for c in CURSOS]
met_principal["curso"] = pd.Categorical(met_principal["curso"], orden, ordered=True)
met_principal = met_principal.sort_values(["curso", "asignatura"]).reset_index(drop=True)

print("Métricas de los 8 modelos (train / test / validación cruzada):")
display(met_principal.round(3))

# 4.2) Desempeño por curso (R² y MAE) y coeficientes IDPS
fig, axes = plt.subplots(1, 2, figsize=(14, 4.5))
for ax, metr, titulo in zip(axes, ["R2_test", "MAE_test"], ["R² test", "MAE test"]):
    sns.barplot(data=met_principal, x="curso", y=metr, hue="asignatura", palette=PALETA, ax=ax)
    ax.set_title(titulo); ax.set_xlabel("Curso"); ax.tick_params(axis="x", rotation=15)
plt.suptitle("Desempeño por curso y asignatura"); plt.tight_layout(); plt.show()

coef_idps = coef_principal[coef_principal["variable"].isin(FEATURES_IDPS)].copy()
coef_idps["indicador"] = coef_idps["variable"].map(IDPS_NOMBRE)
coef_idps["curso"] = pd.Categorical(coef_idps["curso"], orden, ordered=True)
for asig in ["Matemática", "Lectura"]:
    print(f"Coeficientes IDPS estandarizados — {asig}")
    display(coef_idps[coef_idps["asignatura"] == asig]
            .pivot(index="indicador", columns="curso", values="coef")
            [[CURSO_NOMBRE[c] for c in CURSOS]].round(3))

fig, axes = plt.subplots(1, 2, figsize=(14, 4.5), sharey=True)
for ax, asig in zip(axes, ["Matemática", "Lectura"]):
    sns.lineplot(data=coef_idps[coef_idps["asignatura"] == asig], x="curso", y="coef",
                 hue="indicador", marker="o", ax=ax)
    ax.axhline(0, color="black", lw=0.8); ax.set_title(f"Coeficientes IDPS — {asig}")
    ax.set_xlabel("Curso"); ax.set_ylabel("Coef. estandarizado"); ax.tick_params(axis="x", rotation=15)
plt.suptitle("Asociación IDPS→SIMCE por curso"); plt.tight_layout(); plt.show()

# 4.3) Importancia de variables por modelo (todas las variables)
fig, axes = plt.subplots(4, 2, figsize=(14, 18))
for i, curso in enumerate(CURSOS):
    for j, (target, asig) in enumerate(ASIGNATURAS):
        ax = axes[i, j]
        c = coef_principal[(coef_principal["curso"] == CURSO_NOMBRE[curso])
                           & (coef_principal["asignatura"] == asig)].copy()
        c = c.reindex(c["coef"].abs().sort_values(ascending=False).index)
        colores = [PALETA[asig] if v > 0 else "gray" for v in c["coef"]]
        ax.barh(c["variable"], c["coef"], color=colores)
        ax.axvline(0, color="black", lw=0.8); ax.invert_yaxis()
        ax.set_title(f"{asig} · {CURSO_NOMBRE[curso]}")
plt.suptitle("Importancia de variables (modelo principal)", y=1.001)
plt.tight_layout(); plt.show()

"""## 4.4) Variante sin NSE — ¿cuánto del "efecto IDPS" es en realidad NSE?

En Chile el nivel socioeconómico domina parte importante de las diferencias
educativas, por lo que puede ocultar la lectura de los IDPS. Se reentrenan los 8
modelos quitando solo `nse_ord`. Si el R² baja, el NSE aportaba información real; si
los coeficientes IDPS suben, parte de su asociación estaba mezclada con el contexto
socioeconómico.
"""

# 4.4) Comparación con / sin NSE
met_sin_nse, coef_sin_nse = correr_por_curso(FEATURES_IDPS, FEAT_CAT)
comp = met_principal[["curso", "asignatura", "R2_test", "MAE_test"]].merge(
    met_sin_nse[["curso", "asignatura", "R2_test", "MAE_test"]],
    on=["curso", "asignatura"], suffixes=("_con_NSE", "_sin_NSE"))
comp["delta_R2"] = comp["R2_test_sin_NSE"] - comp["R2_test_con_NSE"]
comp["delta_MAE"] = comp["MAE_test_sin_NSE"] - comp["MAE_test_con_NSE"]
print("Impacto de quitar NSE (test):")
display(comp.round(3))

plt.figure(figsize=(9, 4.5))
sns.barplot(data=comp, x="curso", y="delta_R2", hue="asignatura", palette=PALETA)
plt.axhline(0, color="black", lw=0.8)
plt.title("Caída de R² al quitar NSE (más negativo = NSE aportaba más)")
plt.xlabel("Curso"); plt.ylabel("Δ R² (sin − con)"); plt.tight_layout(); plt.show()

"""# 5) Modelos complementarios

- **Global:** todos los cursos juntos (`curso` como control de escala) → panorama y línea base.
- **Unificado `tipo_prueba`:** Matemática y Lectura apiladas en una sola variable objetivo;
  el coeficiente de `tipo_prueba` mide la brecha sistemática entre asignaturas (lo pidió el profe).
"""

# 5) Global + unificado
print("MODELO GLOBAL (todos los cursos):")
for target, asig in ASIGNATURAS:
    fn, fc = FEAT_NUM, ["cod_rural_rbd", "cod_depe2", "curso"]
    data = df_modelo.dropna(subset=fn + fc + [target, "rbd"])
    X, y, g = data[fn + fc], data[target], data["rbd"]
    tr, te = next(GroupShuffleSplit(1, test_size=0.2, random_state=42).split(X, y, g))
    m = pipeline(fn, fc).fit(X.iloc[tr], y.iloc[tr]); mte = metricas(y.iloc[te], m.predict(X.iloc[te]))
    print(f"  {asig:11s} R²_test={mte['R2']:.3f}  MAE_test={mte['MAE']:.2f}")

du = df_modelo.melt(id_vars=["rbd", "curso", "nse_ord", "cod_rural_rbd", "cod_depe2", *FEATURES_IDPS],
                    value_vars=TARGETS, var_name="_c", value_name="puntaje")
du["tipo_prueba"] = du["_c"].map(dict(ASIGNATURAS))
du = du.dropna(subset=["puntaje"])
fn, fc = FEAT_NUM, ["cod_rural_rbd", "cod_depe2", "curso", "tipo_prueba"]
X, y, g = du[fn + fc], du["puntaje"], du["rbd"]
tr, te = next(GroupShuffleSplit(1, test_size=0.2, random_state=42).split(X, y, g))
m = pipeline(fn, fc).fit(X.iloc[tr], y.iloc[tr]); mte = metricas(y.iloc[te], m.predict(X.iloc[te]))
nombres = (m.named_steps["pre"].named_transformers_["num"].get_feature_names_out(fn).tolist()
           + m.named_steps["pre"].named_transformers_["cat"].get_feature_names_out(fc).tolist())
coef_tp = {v: c for v, c in zip(nombres, m.named_steps["reg"].coef_) if v.startswith("tipo_prueba")}
print(f"\nMODELO UNIFICADO (tipo_prueba): R²_test={mte['R2']:.3f}  MAE_test={mte['MAE']:.2f}")
print(f"  coef {list(coef_tp)[0]} = {list(coef_tp.values())[0]:.2f} "
      f"(Matemática vs Lectura, a igualdad del resto)")

"""# 6) Anexo predictivo — desfase temporal T-1 (out-of-time)

El análisis principal es contemporáneo (asociación). Este anexo hace predicción
**real**: predictores en el año **T-1**, target SIMCE en **T**, y test = 2025 (nunca
visto en el ajuste). Se comparan **Solo IDPS** vs **Autorregresivo** (agrega el SIMCE
previo). Por el desfase estricto solo sobreviven los cursos evaluados todos los años
(`4b` y `2m`). Requiere `dataset_maestro.csv` subido a /content.
"""

# 6) Predictivo T-1
def cargar_maestro(data_dir=DATA_DIR):
    p = data_dir / "dataset_maestro.csv"
    if p.exists():
        return pd.read_csv(p)
    for raiz in [Path.cwd(), Path("/content")]:
        hit = next(raiz.rglob("dataset_maestro.csv"), None) if raiz.exists() else None
        if hit:
            return pd.read_csv(hit)
    raise FileNotFoundError("Sube dataset_maestro.csv a /content.")


dp = cargar_maestro()
FC = ["cod_rural_rbd", "cod_depe2"]
FI = ["idps_am_prev", "idps_cc_prev", "idps_hv_prev", "idps_pf_prev", "nse_ord", "curso_ord"]
FA = FI + ["simce_mate_prev", "simce_lect_prev"]
TG = {"Matemática": "target_mate", "Lectura": "target_lect"}
dp = dp.dropna(subset=list(dict.fromkeys(FA + FC + list(TG.values()) + ["agno"])))
train, test = dp[dp["agno"].isin([2017, 2018, 2023, 2024])], dp[dp["agno"] == 2025]
print(f"Predictivo T-1 | train {len(train):,} | test 2025 {len(test):,} | cursos {sorted(dp['curso'].unique())}")

filas = []
for asig, tg in TG.items():
    for nombre, fn in [("Solo IDPS", FI), ("Autorregresivo", FA)]:
        m = pipeline(fn, FC).fit(train[fn + FC], train[tg])
        mte = metricas(test[tg], m.predict(test[fn + FC]))
        filas.append({"asignatura": asig, "modelo": nombre,
                      "MAE_test": mte["MAE"], "R2_test": mte["R2"]})
print("Predictivo T-1 — resultados sobre 2025:")
display(pd.DataFrame(filas).round(3))

"""# 7) iNTERPRET — Síntesis e interpretación

Se conectan los resultados con la pregunta del proyecto y con la rúbrica.
"""

# 7.1) Síntesis cuantitativa
print("Mejor → peor R² test (modelo principal):")
display(met_principal.sort_values("R2_test", ascending=False)
        [["curso", "asignatura", "MAE_test", "RMSE_test", "R2_test"]].round(3).reset_index(drop=True))

br = met_principal[["curso", "asignatura", "MAE_train", "MAE_test", "R2_train", "R2_test", "R2_CV"]].copy()
br["brecha_R2_train_test"] = (br["R2_train"] - br["R2_test"]).round(3)
print("Brecha train–test y comparación con validación cruzada (estabilidad):")
display(br.round(3))

"""## Conclusiones (números reales de esta corrida)

**1. El NSE es el predictor dominante y su peso crece con el nivel.** Estandarizado,
pasa de ~10 pts en 4° básico a ~28 pts en II medio: 2–4× el IDPS más influyente.

**2. Quitar el NSE empeora el ajuste, y el deterioro escala con el curso:** Δ R² ≈ −0,08
en básica hasta **−0,19 en II medio**. Buena parte del "efecto IDPS" es, en realidad, NSE.

**3. Entre los IDPS, Convivencia (`ind_cc`) es el más estable y dominante.** Participación
(`ind_pf`) es inestable / cambia de signo → no interpretar como efecto.

**4. El ajuste mejora con el nivel educativo:** R² test ~0,37–0,43 en básica vs **0,61
(mate) / 0,56 (lect) en II medio**. MAE entre 13 y 19 puntos SIMCE.

**5. Sin sobreajuste:** en los 8 modelos R²_test ≈ R²_CV y la brecha train–test es pequeña.

**6. `tipo_prueba` ≈ −1,4:** la brecha mate–lectura es pequeña → comparten estructura,
lo que justifica el modelo unificado.

**7. Predictivo T-1:** el predictor fuerte del SIMCE futuro es el **SIMCE previo**
(R² 0,62/0,52); los IDPS solos anticipan ~0,36–0,38. Predicen algo, pero no son el motor.

**Métrica elegida — MAE (principal):** error en puntos SIMCE reales, interpretable para
directivos. R²: bondad de ajuste comparable entre cursos. RMSE: vigila errores grandes.

## Comparación de iteraciones

| Iteración | Qué hacía | Limitación principal | Qué se mejora en el modelo final |
|---|---|---|---|
| Primer modelo (Presentación 1) | Regresión lineal para Matemática y Lectura por separado sobre dataset provisorio. | No incorpora cursos ni dataset final consolidado. | Se usa el dataset final por curso y se comparan 8 modelos. |
| Iteración intermedia (unificada) | Integra Matemática y Lectura en formato largo con `tipo_prueba`. Mejora la narrativa descriptivo-explicativa. | El modelo unificado dificulta comparar cómo cambian los IDPS por asignatura y curso. | Se separa por curso y asignatura para interpretar coeficientes con claridad (y se conserva el unificado como complemento). |
| Modelo final (Presentación 2) | Regresión lineal múltiple por curso y asignatura + complementos (global, `tipo_prueba`, predictivo T-1). | Sigue siendo contemporáneo en su parte principal; no prueba causalidad. | Responde mejor la pregunta educativa y la rúbrica: iteración, validación, métricas y un anexo predictivo real. |

## Justificación del modelo final
Se elige el enfoque de **8 regresiones lineales múltiples** porque: mantiene la
interpretabilidad de los coeficientes; evita mezclar niveles educativos en un solo
ajuste; permite comparar Matemática vs Lectura; y permite observar si la asociación
IDPS↔SIMCE cambia entre 4° básico e II medio. Los modelos global, unificado y
predictivo T-1 lo complementan respondiendo, uno a uno, las observaciones del profesor.

## Limitaciones
- Los coeficientes representan **asociaciones, no causalidad**.
- El análisis principal es **contemporáneo** (IDPS y SIMCE del mismo año).
- Para afirmar predicción futura se usa el anexo T-1 (IDPS en T-1 → SIMCE en T).
- Los IDPS presentan multicolinealidad leve → interpretar coeficientes con cautela.
- No todos los cursos tienen los mismos años de SIMCE evaluados.

##SEPARACION - MODELO RIDGE

# Análisis del desempeño académico SIMCE mediante IDPS y variables contextuales
## Modelo final beta - Presentación 2 (versión Ridge)
### Ridge Regression adaptado a la metodología previa, con visualizacion estilo github

Este notebook adapta el modelo **Ridge Regression** (`Ridge_SIMCE_modelo_unificado`) para que siga **la misma estructura, el mismo dataset y el mismo pipeline** que el modelo de regresión lineal múltiple del notebook `ModeloFinal_beta2`. Con el fin de comparar ambos modelos y sus resultados, escogiendo cual modelo se adapta mejor al proyecto.

## Pregunta de investigación

¿Qué relación existe entre los Indicadores de Desarrollo Personal y Social (IDPS), las variables contextuales de los establecimientos y los puntajes SIMCE de Matemática y Lectura, considerando diferencias entre cursos evaluados?

## Objetivo general

Analizar la asociación entre IDPS, variables contextuales y resultados SIMCE por establecimiento, diferenciando por curso y asignatura, comparando los resultados obtenidos mediante **Ridge Regression** con los obtenidos mediante **regresión lineal múltiple (OLS)**.

## Enfoque

Se mantiene la metodología **OSEMN**, igual que en el modelo OLS:

1. **Obtain:** carga del dataset final por curso (idéntico al modelo OLS).
2. **Scrub:** revisión de nulos, categorías, rangos y outliers por curso (idéntico al modelo OLS).
3. **Explore:** análisis descriptivo y correlaciones (idéntico al modelo OLS).
4. **Model:** Ridge Regression (`RidgeCV`) por curso y asignatura, usando el mismo pipeline que OLS.
5. **iNterpret:** comparación de métricas, coeficientes, alpha seleccionado e interpretación educativa.

> Importante: igual que en el modelo OLS, el enfoque principal es contemporáneo. El modelo estudia asociaciones en el mismo período, no afirma causalidad ni predicción futura.

---
# 1) OBTAIN: Carga de datos finales

Se utilizan los **mismos cuatro datasets por curso** que en `ModeloFinal_beta2`, para garantizar que la comparación OLS vs Ridge se haga sobre exactamente la misma información:

- `dataset_historico_4b.csv`
- `dataset_historico_6b.csv`
- `dataset_historico_8b.csv`
- `dataset_historico_2m.csv`

Cada archivo contiene puntajes SIMCE, IDPS y variables contextuales por establecimiento (`rbd`), año (`agno`) y curso (`curso`).

El archivo `dataset_historico_completo.csv` puede quedar disponible en la carpeta como respaldo para análisis global, pero no se usa en el flujo principal de este notebook.
"""

# 1.1) Imports y configuración general

import warnings
warnings.filterwarnings("ignore")

from pathlib import Path
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display

from sklearn.model_selection import GroupShuffleSplit, GroupKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression, RidgeCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

sns.set_theme(style="whitegrid", context="notebook")
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 120)

CURSOS_ORDEN = ["4b", "6b", "8b", "2m"]
CURSO_NOMBRE = {
    "4b": "4° básico",
    "6b": "6° básico",
    "8b": "8° básico",
    "2m": "II medio",
}

IDPS_NOMBRE = {
    "ind_am": "Autoestima académica y motivación",
    "ind_cc": "Clima de convivencia escolar",
    "ind_hv": "Hábitos de vida saludable",
    "ind_pf": "Participación y formación ciudadana",
}

ASIGNATURAS = [
    ("prom_mate2m_rbd", "Matemática", "steelblue"),
    ("prom_lect2m_rbd", "Lectura", "coral"),
]

PALETA_ASIGNATURA = {"Matemática": "steelblue", "Lectura": "coral"}
HUE_ASIGNATURA = ["Matemática", "Lectura"]

features_idps = ["ind_am", "ind_cc", "ind_hv", "ind_pf"]
features_contexto = ["cod_grupo", "cod_rural_rbd", "cod_depe2"]
targets = ["prom_mate2m_rbd", "prom_lect2m_rbd"]

# Rejilla de alphas usada por RidgeCV en todos los modelos del notebook.
ALPHAS_RIDGE = np.logspace(-3, 4, 50)

# 1.2) Ubicación de los CSV

# Si estás en Google Colab y subiste los CSV a /content, deja DATA_DIR = None.
# Si están en Google Drive, monta Drive y define DATA_DIR manualmente, por ejemplo:
# from google.colab import drive
# drive.mount('/content/drive')
# DATA_DIR = "/content/drive/MyDrive/ProyectoDataScience/presentacion2"

DATA_DIR = None

REQUIRED_FILES = [
    "dataset_historico_4b.csv",
    "dataset_historico_6b.csv",
    "dataset_historico_8b.csv",
    "dataset_historico_2m.csv",
]


def encontrar_carpeta_datos(data_dir=None):
    # Busca la carpeta que contiene los cuatro CSV por curso.
    candidates = []
    if data_dir is not None:
        candidates.append(Path(data_dir))

    cwd = Path.cwd()
    candidates.extend([
        cwd,
        cwd / "presentacion2",
        cwd / "data" / "processed" / "por_curso",
        cwd / "por_curso",
        Path("/content"),
        Path("/content/presentacion2"),
        Path("/content/data/processed/por_curso"),
    ])

    for candidate in candidates:
        if candidate.exists() and all((candidate / f).exists() for f in REQUIRED_FILES):
            return candidate

    # Fallback liviano para Colab: buscar solo dentro de /content y el directorio actual.
    search_roots = [cwd]
    if Path("/content").exists():
        search_roots.append(Path("/content"))

    for root in search_roots:
        for hit in root.rglob("dataset_historico_4b.csv"):
            candidate = hit.parent
            if all((candidate / f).exists() for f in REQUIRED_FILES):
                return candidate

    raise FileNotFoundError(
        "No encontré los cuatro CSV por curso. En Colab puedes subirlos directamente a /content "
        "o definir DATA_DIR con la ruta de la carpeta que los contiene."
    )

DATA_PATH = encontrar_carpeta_datos(DATA_DIR)
print(f"Carpeta de datos encontrada: {DATA_PATH}")

# Se deja detectado el dataset completo solo como respaldo, no como fuente principal.
path_completo = DATA_PATH / "dataset_historico_completo.csv"
print("Dataset histórico completo disponible como respaldo:", path_completo.exists())

# 1.3) Carga de datasets por curso

dfs = []
for file_name in REQUIRED_FILES:
    path = DATA_PATH / file_name
    df_tmp = pd.read_csv(path)
    dfs.append(df_tmp)
    print(f"{file_name}: {df_tmp.shape[0]:,} filas × {df_tmp.shape[1]} columnas")

df = pd.concat(dfs, ignore_index=True)

print("\nDataset unido para el análisis final:")
print(f"Filas: {df.shape[0]:,}")
print(f"Columnas: {df.shape[1]}")
display(df.head())

# 1.4) Panorama inicial del dataset

resumen_obtain = pd.DataFrame({
    "valor": [
        df.shape[0],
        df.shape[1],
        ", ".join(map(str, sorted(df["agno"].dropna().unique()))),
        ", ".join([CURSO_NOMBRE.get(c, c) for c in CURSOS_ORDEN if c in set(df["curso"])]),
    ]
}, index=["filas", "columnas", "años disponibles", "cursos disponibles"])

display(resumen_obtain)

print("Registros por curso:")
display(df["curso"].value_counts().reindex(CURSOS_ORDEN).rename(index=CURSO_NOMBRE).to_frame("n_registros"))

print("Registros por año y curso:")
display(pd.crosstab(df["agno"], df["curso"]).reindex(columns=CURSOS_ORDEN))

"""---
# 2) SCRUB: Limpieza y preparación

Idéntico al modelo OLS (`ModeloFinal_beta2`), para asegurar que ambos modelos parten del mismo dataset depurado:

- categorías de NSE, dependencia y ruralidad;
- valores nulos;
- rangos de puntajes SIMCE e IDPS;
- outliers calculados por curso, para evitar mezclar niveles educativos distintos.

También se codifica el NSE como variable ordinal (`nse_ord`), igual que en el modelo OLS.

## Nota sobre codificación ordinal del NSE

`cod_grupo` representa el nivel socioeconómico del establecimiento. Esta variable tiene un orden natural: `Bajo < Medio bajo < Medio < Medio alto < Alto`. Por eso se crea `nse_ord`, que asigna valores de 1 a 5 respetando ese orden.

En el modelo, `nse_ord` se estandariza junto con los IDPS. Por lo tanto, su coeficiente representa el cambio esperado en SIMCE asociado a un aumento de una desviación estándar en NSE, lo que permite comparar mejor su magnitud relativa frente a los indicadores IDPS, tanto en OLS como en Ridge.
"""

# 2.1) Normalización de categorías y tipos

nse_map = {
    "1": "Bajo", "1.0": "Bajo", "Bajo": "Bajo",
    "2": "Medio bajo", "2.0": "Medio bajo", "Medio bajo": "Medio bajo",
    "3": "Medio", "3.0": "Medio", "Medio": "Medio",
    "4": "Medio alto", "4.0": "Medio alto", "Medio alto": "Medio alto",
    "5": "Alto", "5.0": "Alto", "Alto": "Alto",
}

dependencia_map = {
    "1": "Municipal", "1.0": "Municipal", "Municipal": "Municipal",
    "2": "Particular subvencionado", "2.0": "Particular subvencionado", "Particular subvencionado": "Particular subvencionado",
    "3": "Particular pagado", "3.0": "Particular pagado", "Particular pagado": "Particular pagado",
    "4": "SLEP", "4.0": "SLEP", "SLEP": "SLEP",
}

ruralidad_map = {
    "1": "Urbano", "1.0": "Urbano", "Urbano": "Urbano",
    "2": "Rural", "2.0": "Rural", "Rural": "Rural",
}

nse_ord_map = {
    "Bajo": 1,
    "Medio bajo": 2,
    "Medio": 3,
    "Medio alto": 4,
    "Alto": 5,
}


def normalizar_categorias(df_in):
    df_out = df_in.copy()

    for col in ["cod_grupo", "cod_depe2", "cod_rural_rbd", "curso"]:
        df_out[col] = df_out[col].astype(str).str.strip()

    df_out["cod_grupo"] = df_out["cod_grupo"].replace(nse_map)
    df_out["cod_depe2"] = df_out["cod_depe2"].replace(dependencia_map)
    df_out["cod_rural_rbd"] = df_out["cod_rural_rbd"].replace(ruralidad_map)
    df_out["nse_ord"] = df_out["cod_grupo"].map(nse_ord_map)

    numeric_cols = ["rbd", "agno"] + targets + features_idps + ["nse_ord"]
    for col in numeric_cols:
        df_out[col] = pd.to_numeric(df_out[col], errors="coerce")

    df_out["curso_nombre"] = df_out["curso"].map(CURSO_NOMBRE)
    return df_out


df = normalizar_categorias(df)

display(df[["curso", "curso_nombre", "agno", "cod_grupo", "nse_ord", "cod_rural_rbd", "cod_depe2"]].head())

# 2.2) Revisión de nulos y categorías

columnas_requeridas = [
    "rbd", "agno", "curso", "curso_nombre",
    "prom_mate2m_rbd", "prom_lect2m_rbd",
    "cod_grupo", "nse_ord", "cod_rural_rbd", "cod_depe2",
    "ind_am", "ind_cc", "ind_hv", "ind_pf",
]

print("Valores nulos por columna relevante:")
display(df[columnas_requeridas].isna().sum().to_frame("nulos"))

print("Categorías detectadas:")
for col in ["cod_grupo", "cod_rural_rbd", "cod_depe2", "curso"]:
    print(f"- {col}: {sorted(df[col].dropna().unique())}")

antes = len(df)
df_scrub = df.dropna(subset=columnas_requeridas).copy()
print(f"\nFilas antes de dropna: {antes:,}")
print(f"Filas después de dropna: {len(df_scrub):,}")
print(f"Filas eliminadas por nulos: {antes - len(df_scrub):,}")

# 2.3) Revisión de rangos principales

cols_interes = targets + features_idps
resumen_rangos = df_scrub.groupby("curso")[cols_interes].agg(["min", "mean", "max"]).round(2)
resumen_rangos = resumen_rangos.reindex(CURSOS_ORDEN)
display(resumen_rangos)

"""## Análisis de simetría / skewness

Igual que en el modelo OLS, se calcula el **skewness** de los puntajes SIMCE y de los IDPS por curso.

Una regla práctica de lectura es:

- `|skewness| < 0.5`: distribución aproximadamente simétrica.
- `0.5 <= |skewness| < 1`: asimetría moderada.
- `|skewness| >= 1`: asimetría alta.

Este diagnóstico es el mismo para ambos modelos, ya que el dataset y las variables son idénticas.
"""

# 2.4) Análisis de simetría / skewness

variables_skew = targets + features_idps


def clasificar_skewness(valor):
    abs_val = abs(valor)
    if abs_val < 0.5:
        return "Aprox. simétrica"
    if abs_val < 1:
        return "Asimetría moderada"
    return "Asimetría alta"


skew_rows = []
for curso in CURSOS_ORDEN:
    g = df_scrub[df_scrub["curso"] == curso]
    for variable in variables_skew:
        skew_value = g[variable].skew()
        skew_rows.append({
            "curso": curso,
            "curso_nombre": CURSO_NOMBRE[curso],
            "variable": variable,
            "skewness": skew_value,
            "interpretacion": clasificar_skewness(skew_value),
        })

skewness_df = pd.DataFrame(skew_rows)

tabla_skew = skewness_df.pivot(
    index="variable",
    columns="curso_nombre",
    values="skewness",
)[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]

display(tabla_skew.round(3))
display(skewness_df.round(3))

fig, axes = plt.subplots(2, 3, figsize=(16, 8))
axes = axes.flatten()

for ax, variable in zip(axes, variables_skew):
    sns.histplot(
        data=df_scrub,
        x=variable,
        hue="curso_nombre",
        bins=35,
        kde=True,
        stat="density",
        common_norm=False,
        ax=ax,
    )
    ax.set_title(f"Distribución de {variable}")
    ax.set_xlabel(variable)
    ax.set_ylabel("Densidad")

plt.suptitle("Distribuciones para análisis de skewness")
plt.tight_layout()
plt.show()

# 2.4) Tratamiento de outliers por curso usando IQR sobre puntajes SIMCE

# El IQR se calcula por curso porque mezclar 4° básico, 6° básico, 8° básico y II medio
# puede clasificar como outlier un valor que solo pertenece a otra escala de comparación educativa.

def filtrar_outliers_iqr_por_curso(df_in, targets_modelo):
    keep_global = pd.Series(True, index=df_in.index)
    filas_resumen = []

    for curso, g in df_in.groupby("curso"):
        keep_curso = pd.Series(True, index=g.index)
        for col in targets_modelo:
            q1 = g[col].quantile(0.25)
            q3 = g[col].quantile(0.75)
            iqr = q3 - q1
            lower = q1 - 1.5 * iqr
            upper = q3 + 1.5 * iqr
            keep_col = g[col].between(lower, upper)
            filas_resumen.append({
                "curso": curso,
                "curso_nombre": CURSO_NOMBRE.get(curso, curso),
                "variable": col,
                "limite_inferior": lower,
                "limite_superior": upper,
                "outliers_detectados": int((~keep_col).sum()),
            })
            keep_curso &= keep_col
        keep_global.loc[g.index] = keep_curso

    return df_in.loc[keep_global].copy(), pd.DataFrame(filas_resumen)


df_modelo, resumen_outliers = filtrar_outliers_iqr_por_curso(df_scrub, targets)

print(f"Filas antes de IQR: {len(df_scrub):,}")
print(f"Filas después de IQR: {len(df_modelo):,}")
print(f"Filas eliminadas por IQR: {len(df_scrub) - len(df_modelo):,}")
display(resumen_outliers.round(2))

"""---
# 3) EXPLORE: Análisis descriptivo

Idéntico al modelo OLS. Esta sección compara los puntajes SIMCE y los IDPS entre cursos, y deja la misma base exploratoria que se usó para justificar el modelo de regresión lineal múltiple, ahora también como referencia para Ridge.
"""

# 3.1) Distribución de SIMCE por curso y asignatura

plot_df = df_modelo.melt(
    id_vars=["rbd", "agno", "curso", "curso_nombre"],
    value_vars=targets,
    var_name="tipo_prueba",
    value_name="puntaje_simce",
)
plot_df["asignatura"] = plot_df["tipo_prueba"].map({
    "prom_mate2m_rbd": "Matemática",
    "prom_lect2m_rbd": "Lectura",
})
plot_df["curso_nombre"] = pd.Categorical(
    plot_df["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)

plt.figure(figsize=(11, 5))
sns.boxplot(data=plot_df, x="curso_nombre", y="puntaje_simce", hue="asignatura", hue_order=HUE_ASIGNATURA, palette=PALETA_ASIGNATURA)
plt.title("Distribución de puntajes SIMCE por curso y asignatura")
plt.xlabel("Curso")
plt.ylabel("Puntaje SIMCE")
plt.legend(title="Asignatura")
plt.tight_layout()
plt.show()

# 3.2) Evolución por año disponible

promedios_anuales = plot_df.groupby(["agno", "curso", "curso_nombre", "asignatura"], as_index=False)["puntaje_simce"].mean()

plt.figure(figsize=(12, 5))
sns.lineplot(
    data=promedios_anuales,
    x="agno", y="puntaje_simce",
    hue="curso_nombre", style="asignatura",
    markers=True, dashes=False,
)
plt.title("Promedio SIMCE por año, curso y asignatura")
plt.xlabel("Año")
plt.ylabel("Puntaje promedio")
plt.legend(title="Curso / asignatura", bbox_to_anchor=(1.02, 1), loc="upper left")
plt.tight_layout()
plt.show()

# 3.3) Correlaciones IDPS vs SIMCE por curso

filas_corr = []
for curso in CURSOS_ORDEN:
    g = df_modelo[df_modelo["curso"] == curso]
    for idps in features_idps:
        for target, asignatura, _ in ASIGNATURAS:
            filas_corr.append({
                "curso": curso,
                "curso_nombre": CURSO_NOMBRE[curso],
                "idps": idps,
                "indicador": IDPS_NOMBRE[idps],
                "asignatura": asignatura,
                "correlacion": g[idps].corr(g[target]),
            })

corr_idps = pd.DataFrame(filas_corr)

for asignatura in ["Matemática", "Lectura"]:
    tabla = corr_idps[corr_idps["asignatura"] == asignatura].pivot(
        index="indicador", columns="curso_nombre", values="correlacion"
    )[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]
    print(f"Correlación IDPS vs SIMCE - {asignatura}")
    display(tabla.round(3))

"""## Matrices de correlación complementarias

Igual que en el modelo OLS, se incluye una matriz global de correlación entre puntajes SIMCE e IDPS y una lectura por curso.

Estas matrices no reemplazan al modelo de regresión: sirven para diagnosticar relaciones lineales simples antes de controlar por NSE, dependencia y ruralidad, y para justificar por qué Ridge puede ser una alternativa razonable cuando hay multicolinealidad entre los IDPS.
"""

# 3.3b) Matrices de correlación: global y por curso

corr_vars_modelo = targets + features_idps + ["nse_ord"]
corr_labels = {
    "prom_mate2m_rbd": "SIMCE Matemática",
    "prom_lect2m_rbd": "SIMCE Lectura",
    "ind_am": "Autoestima",
    "ind_cc": "Convivencia",
    "ind_hv": "Hábitos",
    "ind_pf": "Participación",
    "nse_ord": "NSE ordinal",
}

corr_global = df_modelo[corr_vars_modelo].corr()
plt.figure(figsize=(9, 7))
sns.heatmap(
    corr_global.rename(index=corr_labels, columns=corr_labels),
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    center=0,
    square=True,
)
plt.title("Matriz de correlación global: SIMCE, IDPS y NSE")
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(15, 12))
axes = axes.flatten()

for ax, curso in zip(axes, CURSOS_ORDEN):
    g = df_modelo[df_modelo["curso"] == curso]
    corr_curso = g[corr_vars_modelo].corr().rename(index=corr_labels, columns=corr_labels)
    sns.heatmap(
        corr_curso,
        annot=True,
        fmt=".2f",
        cmap="coolwarm",
        center=0,
        square=True,
        ax=ax,
        cbar=False,
    )
    ax.set_title(f"Matriz de correlación - {CURSO_NOMBRE[curso]}")
    ax.tick_params(axis="x", rotation=35)
    ax.tick_params(axis="y", rotation=0)

plt.suptitle("Matrices de correlación por curso", fontsize=14)
plt.tight_layout()
plt.show()

# 3.4) Multicolinealidad entre IDPS: correlación y VIF

corr_idps_global = df_modelo[features_idps].corr()
plt.figure(figsize=(7, 5))
sns.heatmap(corr_idps_global, annot=True, fmt=".2f", cmap="coolwarm", center=0,
            xticklabels=[IDPS_NOMBRE[c] for c in features_idps],
            yticklabels=[IDPS_NOMBRE[c] for c in features_idps])
plt.title("Correlación entre indicadores IDPS")
plt.xticks(rotation=35, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()


def calcular_vif_sklearn(df_num):
    # Calcula VIF sin depender de statsmodels.
    filas = []
    for col in df_num.columns:
        y = df_num[col].values
        X = df_num.drop(columns=[col]).values
        r2 = LinearRegression().fit(X, y).score(X, y)
        vif = np.inf if (1 - r2) <= 1e-12 else 1 / (1 - r2)
        filas.append({"variable": col, "indicador": IDPS_NOMBRE.get(col, col), "R2_auxiliar": r2, "VIF": vif})
    return pd.DataFrame(filas)

vif_rows = []
for curso in CURSOS_ORDEN:
    vif_tmp = calcular_vif_sklearn(df_modelo.loc[df_modelo["curso"] == curso, features_idps])
    vif_tmp.insert(0, "curso", curso)
    vif_tmp.insert(1, "curso_nombre", CURSO_NOMBRE[curso])
    vif_rows.append(vif_tmp)

vif_df = pd.concat(vif_rows, ignore_index=True)
display(vif_df.round(3))

print("\nNota: valores de VIF moderados (5-10) o altos (>10) son un argumento a favor de Ridge,")
print("ya que penaliza los coeficientes inestables causados por multicolinealidad entre los IDPS.")

"""---
# 4) MODEL: Ridge Regression por curso y asignatura

Se entrenan **8 modelos**, exactamente igual que en el modelo OLS:

- 4 cursos: 4° básico, 6° básico, 8° básico y II medio.
- 2 asignaturas: Matemática y Lectura.

La estructura, el preprocesamiento, el split y la validación cruzada son **idénticos al modelo de regresión lineal múltiple**. La única diferencia es el regresor: `RidgeCV` en lugar de `LinearRegression`.

## Pipeline y validación (igual que en OLS)

- **Split agrupado por `rbd`:** evita que un mismo establecimiento aparezca simultáneamente en entrenamiento y prueba.
- **Validación cruzada agrupada:** evalúa estabilidad respetando la unidad establecimiento.
- **NSE ordinal estandarizado:** permite comparar su magnitud con los IDPS.
- **One-hot con categoría base (`drop="first"`):** evita redundancia perfecta entre categorías y facilita la interpretación de las variables contextuales.

## Diferencia específica de Ridge

- El regresor es `RidgeCV(alphas=ALPHAS_RIDGE, cv=5)`, que selecciona automáticamente el parámetro de penalización `alpha` para **cada uno de los 8 modelos** (cada combinación de curso y asignatura puede tener un `alpha` distinto).
- Ridge **no elimina variables**: encoge (shrinkage) los coeficientes hacia cero, lo que reduce su varianza cuando hay multicolinealidad entre los IDPS, pero mantiene todas las variables del modelo.
- La interpretación de los coeficientes es la misma que en OLS (asociaciones ajustadas, manteniendo constantes las demás variables), pero los valores absolutos de los coeficientes de Ridge suelen ser algo menores que los de OLS.

## Variables del modelo (idénticas a OLS)

**Targets:**

- `prom_mate2m_rbd`: puntaje SIMCE Matemática.
- `prom_lect2m_rbd`: puntaje SIMCE Lectura.

**Predictores:**

- IDPS: `ind_am`, `ind_cc`, `ind_hv`, `ind_pf`.
- NSE ordinal estandarizado: `nse_ord`.
- Ruralidad: `cod_rural_rbd`.
- Dependencia administrativa: `cod_depe2`.

La variable `curso` no se usa como predictor dentro de cada modelo porque cada modelo se ajusta sobre un único curso.
"""

# 4.1) Funciones de modelamiento (Ridge)

features_num = ["ind_am", "ind_cc", "ind_hv", "ind_pf", "nse_ord"]
features_cat = ["cod_rural_rbd", "cod_depe2"]
features_modelo = features_num + features_cat


def calcular_metricas(y_real, y_estimado):
    return {
        "MAE": mean_absolute_error(y_real, y_estimado),
        "RMSE": np.sqrt(mean_squared_error(y_real, y_estimado)),
        "R2": r2_score(y_real, y_estimado),
    }


def crear_pipeline_regresion():
    preprocessor = ColumnTransformer(transformers=[
        ("num", StandardScaler(), features_num),
        ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat),
    ])

    return Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("regressor", RidgeCV(alphas=ALPHAS_RIDGE, cv=5)),
    ])


def obtener_feature_names(model):
    pre = model.named_steps["preprocessor"]
    num_names = pre.named_transformers_["num"].get_feature_names_out(features_num).tolist()
    cat_names = pre.named_transformers_["cat"].get_feature_names_out(features_cat).tolist()
    return num_names + cat_names


def entrenar_modelo(df_curso, curso, target, asignatura):
    data = df_curso.dropna(subset=features_modelo + [target, "rbd"]).copy()

    X = data[features_modelo]
    y = data[target]
    groups = data["rbd"]

    model = crear_pipeline_regresion()

    # Split agrupado por establecimiento para evitar que el mismo RBD quede simultáneamente en train y test.
    if groups.nunique() >= 5:
        splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
        train_idx, test_idx = next(splitter.split(X, y, groups=groups))
    else:
        # Fallback poco probable: si hubiese muy pocos establecimientos.
        rng = np.random.default_rng(42)
        indices = np.arange(len(data))
        rng.shuffle(indices)
        split = int(len(indices) * 0.8)
        train_idx, test_idx = indices[:split], indices[split:]

    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)

    # Alpha seleccionado automáticamente por RidgeCV para este curso/asignatura.
    alpha_seleccionado = model.named_steps["regressor"].alpha_

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)

    metricas_train = calcular_metricas(y_train, y_pred_train)
    metricas_test = calcular_metricas(y_test, y_pred_test)

    # Validación cruzada agrupada por RBD en el set completo del curso/asignatura.
    cv_metricas = {"MAE_CV": np.nan, "RMSE_CV": np.nan, "R2_CV": np.nan, "R2_CV_STD": np.nan}
    n_groups = groups.nunique()
    if n_groups >= 3:
        cv = GroupKFold(n_splits=min(5, n_groups))
        scoring = {
            "MAE": "neg_mean_absolute_error",
            "MSE": "neg_mean_squared_error",
            "R2": "r2",
        }
        cv_scores = cross_validate(
            crear_pipeline_regresion(), X, y,
            groups=groups, cv=cv, scoring=scoring,
            return_train_score=False,
        )
        cv_metricas = {
            "MAE_CV": -cv_scores["test_MAE"].mean(),
            "RMSE_CV": np.sqrt(-cv_scores["test_MSE"]).mean(),
            "R2_CV": cv_scores["test_R2"].mean(),
            "R2_CV_STD": cv_scores["test_R2"].std(),
        }

    feature_names = obtener_feature_names(model)
    coefs = model.named_steps["regressor"].coef_
    coef_df = pd.DataFrame({
        "variable": feature_names,
        "coeficiente": coefs,
    }).sort_values("coeficiente", key=lambda s: s.abs(), ascending=False)

    pred_df = pd.DataFrame({
        "curso": curso,
        "curso_nombre": CURSO_NOMBRE[curso],
        "asignatura": asignatura,
        "real": y_test.values,
        "predicho": y_pred_test,
    })
    pred_df["residuo"] = pred_df["real"] - pred_df["predicho"]

    metricas = {
        "curso": curso,
        "curso_nombre": CURSO_NOMBRE[curso],
        "asignatura": asignatura,
        "n_total": len(data),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "alpha_seleccionado": alpha_seleccionado,
        "MAE_train": metricas_train["MAE"],
        "RMSE_train": metricas_train["RMSE"],
        "R2_train": metricas_train["R2"],
        "MAE_test": metricas_test["MAE"],
        "RMSE_test": metricas_test["RMSE"],
        "R2_test": metricas_test["R2"],
        **cv_metricas,
    }

    return {
        "model": model,
        "metricas": metricas,
        "coeficientes": coef_df,
        "predicciones": pred_df,
    }

# 4.2) Entrenamiento de los 8 modelos Ridge

resultados = {}
metricas_rows = []
coef_rows = []
pred_rows = []

for curso in CURSOS_ORDEN:
    df_curso = df_modelo[df_modelo["curso"] == curso].copy()
    print(f"Entrenando modelos Ridge para {CURSO_NOMBRE[curso]}: {len(df_curso):,} registros")

    for target, asignatura, color in ASIGNATURAS:
        res = entrenar_modelo(df_curso, curso, target, asignatura)
        resultados[(curso, asignatura)] = res
        metricas_rows.append(res["metricas"])

        coef_tmp = res["coeficientes"].copy()
        coef_tmp.insert(0, "curso", curso)
        coef_tmp.insert(1, "curso_nombre", CURSO_NOMBRE[curso])
        coef_tmp.insert(2, "asignatura", asignatura)
        coef_rows.append(coef_tmp)

        pred_rows.append(res["predicciones"])

metricas_df = pd.DataFrame(metricas_rows)
coeficientes_df = pd.concat(coef_rows, ignore_index=True)
predicciones_df = pd.concat(pred_rows, ignore_index=True)

print("Modelos Ridge entrenados:", len(resultados))

"""### Formato de tablas por asignatura

Igual que en el modelo OLS, las tablas de métricas y comparación se muestran separadas por asignatura, para comparar los cursos directamente sin mezclar Matemática y Lectura en una sola tabla extensa.
"""

# 4.2) Entrenamiento de los 8 modelos Ridge

resultados = {}
metricas_rows = []
coef_rows = []
pred_rows = []

for curso in CURSOS_ORDEN:
    df_curso = df_modelo[df_modelo["curso"] == curso].copy()
    print(f"Entrenando modelos Ridge para {CURSO_NOMBRE[curso]}: {len(df_curso):,} registros")

    for target, asignatura, color in ASIGNATURAS:
        res = entrenar_modelo(df_curso, curso, target, asignatura)
        resultados[(curso, asignatura)] = res
        metricas_rows.append(res["metricas"])

        coef_tmp = res["coeficientes"].copy()
        coef_tmp.insert(0, "curso", curso)
        coef_tmp.insert(1, "curso_nombre", CURSO_NOMBRE[curso])
        coef_tmp.insert(2, "asignatura", asignatura)
        coef_rows.append(coef_tmp)

        pred_rows.append(res["predicciones"])

metricas_df = pd.DataFrame(metricas_rows)
coeficientes_df = pd.concat(coef_rows, ignore_index=True)
predicciones_df = pd.concat(pred_rows, ignore_index=True)

print("Modelos Ridge entrenados:", len(resultados))

# 4.3) Tabla de métricas: train, test, validación cruzada y alpha seleccionado

metricas_ordenadas = metricas_df.copy()
metricas_ordenadas["curso_nombre"] = pd.Categorical(
    metricas_ordenadas["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)
metricas_ordenadas = metricas_ordenadas.sort_values(["curso_nombre", "asignatura"])

cols_metricas = [
    "curso_nombre", "asignatura", "n_total", "n_train", "n_test",
    "alpha_seleccionado",
    "MAE_train", "MAE_test", "RMSE_train", "RMSE_test",
    "R2_train", "R2_test", "MAE_CV", "RMSE_CV", "R2_CV", "R2_CV_STD",
]
cols_metricas_sin_asignatura = [c for c in cols_metricas if c != "asignatura"]

for asignatura in HUE_ASIGNATURA:
    print(f"Métricas train/test, validación cruzada y alpha - {asignatura}")
    tabla_asignatura = metricas_ordenadas[metricas_ordenadas["asignatura"] == asignatura]
    display(tabla_asignatura[cols_metricas_sin_asignatura].round(4).reset_index(drop=True))

# 4.4) Visualización de desempeño por curso y asignatura

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
for ax, metric, title in zip(
    axes,
    ["MAE_test", "RMSE_test", "R2_test"],
    ["MAE test", "RMSE test", "R² test"],
):
    sns.barplot(
        data=metricas_ordenadas,
        x="curso_nombre", y=metric,
        hue="asignatura", ax=ax,
        hue_order=HUE_ASIGNATURA,
        palette=PALETA_ASIGNATURA,
    )
    ax.set_title(title)
    ax.set_xlabel("Curso")
    ax.set_ylabel(metric)
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="Asignatura")

plt.suptitle("Modelo Ridge: comparación de métricas de test por modelo")
plt.tight_layout()
plt.show()

# Alpha seleccionado por RidgeCV en cada curso/asignatura
plt.figure(figsize=(10, 4))
sns.barplot(
    data=metricas_ordenadas,
    x="curso_nombre", y="alpha_seleccionado",
    hue="asignatura",
    hue_order=HUE_ASIGNATURA,
    palette=PALETA_ASIGNATURA,
)
plt.yscale("log")
plt.title("Alpha seleccionado por RidgeCV (escala log)")
plt.xlabel("Curso")
plt.ylabel("alpha")
plt.legend(title="Asignatura")
plt.tight_layout()
plt.show()

# 4.5) Coeficientes de IDPS por curso y asignatura (Ridge)

coef_idps = coeficientes_df[coeficientes_df["variable"].isin(features_idps)].copy()
coef_idps["indicador"] = coef_idps["variable"].map(IDPS_NOMBRE)
coef_idps["curso_nombre"] = pd.Categorical(
    coef_idps["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)

for asignatura in ["Matemática", "Lectura"]:
    tabla_coef = coef_idps[coef_idps["asignatura"] == asignatura].pivot(
        index="indicador", columns="curso_nombre", values="coeficiente"
    )[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]
    print(f"Coeficientes IDPS estandarizados (Ridge) - {asignatura}")
    display(tabla_coef.round(3))

# 4.6) Evolución visual de coeficientes IDPS por curso (Ridge)

fig, axes = plt.subplots(1, 2, figsize=(15, 5), sharey=True)

for ax, asignatura in zip(axes, ["Matemática", "Lectura"]):
    data_plot = coef_idps[coef_idps["asignatura"] == asignatura].copy()
    sns.lineplot(
        data=data_plot,
        x="curso_nombre", y="coeficiente",
        hue="indicador", marker="o", ax=ax,
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(f"Coeficientes IDPS (Ridge) - {asignatura}")
    ax.set_xlabel("Curso")
    ax.set_ylabel("Coeficiente estandarizado")
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="IDPS", fontsize=8)

plt.suptitle("Modelo Ridge: comparación de asociaciones IDPS-SIMCE por curso")
plt.tight_layout()
plt.show()

"""## Importancia de variables - modelo principal (Ridge)

Mismos gráficos de barras horizontales que en el modelo OLS: variables ordenadas por magnitud absoluta, línea en cero, coeficientes positivos en el color de la asignatura y coeficientes negativos en gris.

La diferencia frente a OLS es que estos coeficientes provienen de `RidgeCV`, por lo que ya incorporan la penalización L2: en general sus magnitudes serán iguales o menores que las del modelo OLS para las mismas variables, especialmente en variables con alto VIF.
"""

# 4.7) Importancia de variables (estilo GitHub - modelo principal Ridge)

def preparar_coeficientes_para_grafico(coef_df, curso, asignatura):
    data_plot = coef_df[
        (coef_df["curso"] == curso)
        & (coef_df["asignatura"] == asignatura)
    ].copy()
    data_plot = data_plot.reindex(
        data_plot["coeficiente"].abs().sort_values(ascending=False).index
    )
    return data_plot


def graficar_importancia_estilo_github(coef_df, curso, asignatura, titulo_prefijo="", output_path=None):
    data_plot = preparar_coeficientes_para_grafico(coef_df, curso, asignatura)

    plt.figure(figsize=(9, 5))
    colores = [
        PALETA_ASIGNATURA[asignatura] if c > 0 else "gray"
        for c in data_plot["coeficiente"]
    ]
    plt.barh(data_plot["variable"], data_plot["coeficiente"], color=colores)
    plt.axvline(0, color="black", linewidth=0.8)
    plt.xlabel(f"Coeficiente Ridge sobre SIMCE {asignatura}")
    prefijo = f"{titulo_prefijo} - " if titulo_prefijo else ""
    plt.title(f"{prefijo}Importancia de variables (Ridge) — {asignatura} · {CURSO_NOMBRE[curso]}")
    plt.gca().invert_yaxis()
    plt.tight_layout()
    if output_path is not None:
        plt.savefig(output_path, dpi=150, bbox_inches="tight")
    plt.show()


FIG_PRINCIPAL_DIR = Path("salidas_modelo_ridge") / "figuras_modelo_principal"
FIG_PRINCIPAL_DIR.mkdir(parents=True, exist_ok=True)

for curso in CURSOS_ORDEN:
    for asignatura in ["Matemática", "Lectura"]:
        nombre_asig = "mate" if asignatura == "Matemática" else "lect"
        graficar_importancia_estilo_github(
            coeficientes_df,
            curso,
            asignatura,
            output_path=FIG_PRINCIPAL_DIR / f"{nombre_asig}_{curso}_importancia_ridge.png",
        )

print(f"Figuras de importancia del modelo Ridge principal guardadas en: {FIG_PRINCIPAL_DIR.resolve()}")

# 4.7b) Valores reales vs estimados y residuos (Ridge)

fig, axes = plt.subplots(4, 2, figsize=(12, 16), sharex=False, sharey=False)

for i, curso in enumerate(CURSOS_ORDEN):
    for j, asignatura in enumerate(["Matemática", "Lectura"]):
        ax = axes[i, j]
        p = predicciones_df[(predicciones_df["curso"] == curso) & (predicciones_df["asignatura"] == asignatura)]
        ax.scatter(p["real"], p["predicho"], alpha=0.25, s=12, color=PALETA_ASIGNATURA[asignatura])
        min_val = min(p["real"].min(), p["predicho"].min())
        max_val = max(p["real"].max(), p["predicho"].max())
        ax.plot([min_val, max_val], [min_val, max_val], "r--", linewidth=1)
        ax.set_title(f"Ridge - {CURSO_NOMBRE[curso]} - {asignatura}")
        ax.set_xlabel("Real")
        ax.set_ylabel("Estimado")

plt.suptitle("Modelo Ridge: valores reales vs estimados por modelo")
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(4, 2, figsize=(12, 16), sharex=False, sharey=False)

for i, curso in enumerate(CURSOS_ORDEN):
    for j, asignatura in enumerate(["Matemática", "Lectura"]):
        ax = axes[i, j]
        p = predicciones_df[(predicciones_df["curso"] == curso) & (predicciones_df["asignatura"] == asignatura)]
        ax.hist(p["residuo"], bins=35, edgecolor="white", color=PALETA_ASIGNATURA[asignatura])
        ax.axvline(0, color="black", linestyle="--", linewidth=1)
        ax.set_title(f"Ridge - Residuos: {CURSO_NOMBRE[curso]} - {asignatura}")
        ax.set_xlabel("Residuo")
        ax.set_ylabel("Frecuencia")

plt.suptitle("Modelo Ridge: distribución de residuos por modelo")
plt.tight_layout()
plt.show()

"""## Variante del modelo: análisis sin NSE (Ridge)

Igual que en el modelo OLS, se mantiene NSE como variable de control en el modelo principal porque es una dimensión contextual relevante, pero se estima una variante quitando solo `nse_ord`:

- **Modelo principal Ridge:** IDPS + NSE + ruralidad + dependencia.
- **Modelo Ridge sin NSE:** IDPS + ruralidad + dependencia.

Esta variante no reemplaza al modelo principal. Sirve para observar cómo cambian las métricas, el `alpha` seleccionado y los coeficientes de IDPS cuando no se controla por nivel socioeconómico, igual que en la versión OLS.
"""

# 4.8) Entrenamiento del modelo Ridge sin NSE

features_num_sin_nse = ["ind_am", "ind_cc", "ind_hv", "ind_pf"]
features_cat_sin_nse = ["cod_rural_rbd", "cod_depe2"]
features_modelo_sin_nse = features_num_sin_nse + features_cat_sin_nse


def crear_pipeline_regresion_sin_nse():
    preprocessor = ColumnTransformer(transformers=[
        ("num", StandardScaler(), features_num_sin_nse),
        ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat_sin_nse),
    ])

    return Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("regressor", RidgeCV(alphas=ALPHAS_RIDGE, cv=5)),
    ])


def obtener_feature_names_sin_nse(model):
    pre = model.named_steps["preprocessor"]
    num_names = pre.named_transformers_["num"].get_feature_names_out(features_num_sin_nse).tolist()
    cat_names = pre.named_transformers_["cat"].get_feature_names_out(features_cat_sin_nse).tolist()
    return num_names + cat_names


def entrenar_modelo_sin_nse(df_curso, curso, target, asignatura):
    data = df_curso.dropna(subset=features_modelo_sin_nse + [target, "rbd"]).copy()

    X = data[features_modelo_sin_nse]
    y = data[target]
    groups = data["rbd"]

    model = crear_pipeline_regresion_sin_nse()

    splitter = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
    train_idx, test_idx = next(splitter.split(X, y, groups=groups))

    X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

    model.fit(X_train, y_train)

    alpha_seleccionado = model.named_steps["regressor"].alpha_

    y_pred_train = model.predict(X_train)
    y_pred_test = model.predict(X_test)

    metricas_train = calcular_metricas(y_train, y_pred_train)
    metricas_test = calcular_metricas(y_test, y_pred_test)

    cv_metricas = {"MAE_CV": np.nan, "RMSE_CV": np.nan, "R2_CV": np.nan, "R2_CV_STD": np.nan}
    n_groups = groups.nunique()
    if n_groups >= 3:
        cv = GroupKFold(n_splits=min(5, n_groups))
        scoring = {
            "MAE": "neg_mean_absolute_error",
            "MSE": "neg_mean_squared_error",
            "R2": "r2",
        }
        cv_scores = cross_validate(
            crear_pipeline_regresion_sin_nse(), X, y,
            groups=groups, cv=cv, scoring=scoring,
            return_train_score=False,
        )
        cv_metricas = {
            "MAE_CV": -cv_scores["test_MAE"].mean(),
            "RMSE_CV": np.sqrt(-cv_scores["test_MSE"]).mean(),
            "R2_CV": cv_scores["test_R2"].mean(),
            "R2_CV_STD": cv_scores["test_R2"].std(),
        }

    feature_names = obtener_feature_names_sin_nse(model)
    coefs = model.named_steps["regressor"].coef_
    coef_df = pd.DataFrame({
        "variable": feature_names,
        "coeficiente": coefs,
    }).sort_values("coeficiente", key=lambda s: s.abs(), ascending=False)

    pred_df = pd.DataFrame({
        "curso": curso,
        "curso_nombre": CURSO_NOMBRE[curso],
        "asignatura": asignatura,
        "real": y_test.values,
        "predicho": y_pred_test,
    })
    pred_df["residuo"] = pred_df["real"] - pred_df["predicho"]

    metricas = {
        "curso": curso,
        "curso_nombre": CURSO_NOMBRE[curso],
        "asignatura": asignatura,
        "n_total": len(data),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "alpha_seleccionado": alpha_seleccionado,
        "MAE_train": metricas_train["MAE"],
        "RMSE_train": metricas_train["RMSE"],
        "R2_train": metricas_train["R2"],
        "MAE_test": metricas_test["MAE"],
        "RMSE_test": metricas_test["RMSE"],
        "R2_test": metricas_test["R2"],
        **cv_metricas,
    }

    return {
        "model": model,
        "metricas": metricas,
        "coeficientes": coef_df,
        "predicciones": pred_df,
    }


resultados_sin_nse = {}
metricas_sin_nse_rows = []
coef_sin_nse_rows = []
pred_sin_nse_rows = []

for curso in CURSOS_ORDEN:
    df_curso = df_modelo[df_modelo["curso"] == curso].copy()
    print(f"Entrenando modelos Ridge sin NSE para {CURSO_NOMBRE[curso]}: {len(df_curso):,} registros")

    for target, asignatura, color in ASIGNATURAS:
        res = entrenar_modelo_sin_nse(df_curso, curso, target, asignatura)
        resultados_sin_nse[(curso, asignatura)] = res
        metricas_sin_nse_rows.append(res["metricas"])

        coef_tmp = res["coeficientes"].copy()
        coef_tmp.insert(0, "curso", curso)
        coef_tmp.insert(1, "curso_nombre", CURSO_NOMBRE[curso])
        coef_tmp.insert(2, "asignatura", asignatura)
        coef_sin_nse_rows.append(coef_tmp)

        pred_sin_nse_rows.append(res["predicciones"])

metricas_sin_nse_df = pd.DataFrame(metricas_sin_nse_rows)
coeficientes_sin_nse_df = pd.concat(coef_sin_nse_rows, ignore_index=True)
predicciones_sin_nse_df = pd.concat(pred_sin_nse_rows, ignore_index=True)

print("Modelos Ridge sin NSE entrenados:", len(resultados_sin_nse))

# 4.9) Métricas del modelo Ridge sin NSE

metricas_sin_nse_ordenadas = metricas_sin_nse_df.copy()
metricas_sin_nse_ordenadas["curso_nombre"] = pd.Categorical(
    metricas_sin_nse_ordenadas["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)
metricas_sin_nse_ordenadas = metricas_sin_nse_ordenadas.sort_values(["curso_nombre", "asignatura"])

for asignatura in HUE_ASIGNATURA:
    print(f"Modelo Ridge sin NSE - Métricas train/test, validación cruzada y alpha - {asignatura}")
    tabla_asignatura = metricas_sin_nse_ordenadas[metricas_sin_nse_ordenadas["asignatura"] == asignatura]
    display(tabla_asignatura[cols_metricas_sin_asignatura].round(4).reset_index(drop=True))

fig, axes = plt.subplots(1, 3, figsize=(16, 4))
for ax, metric, title in zip(
    axes,
    ["MAE_test", "RMSE_test", "R2_test"],
    ["MAE test", "RMSE test", "R² test"],
):
    sns.barplot(
        data=metricas_sin_nse_ordenadas,
        x="curso_nombre", y=metric,
        hue="asignatura",
        hue_order=HUE_ASIGNATURA,
        palette=PALETA_ASIGNATURA,
        ax=ax,
    )
    ax.set_title(title)
    ax.set_xlabel("Curso")
    ax.set_ylabel(metric)
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="Asignatura")

plt.suptitle("Modelo Ridge sin NSE: comparación de métricas de test")
plt.tight_layout()
plt.show()

# 4.10) Coeficientes e importancia de variables - modelo Ridge sin NSE

coef_idps_sin_nse = coeficientes_sin_nse_df[
    coeficientes_sin_nse_df["variable"].isin(features_idps)
].copy()
coef_idps_sin_nse["indicador"] = coef_idps_sin_nse["variable"].map(IDPS_NOMBRE)
coef_idps_sin_nse["curso_nombre"] = pd.Categorical(
    coef_idps_sin_nse["curso_nombre"],
    categories=[CURSO_NOMBRE[c] for c in CURSOS_ORDEN],
    ordered=True,
)

for asignatura in ["Matemática", "Lectura"]:
    tabla_coef = coef_idps_sin_nse[coef_idps_sin_nse["asignatura"] == asignatura].pivot(
        index="indicador", columns="curso_nombre", values="coeficiente"
    )[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]
    print(f"Modelo Ridge sin NSE - Coeficientes IDPS estandarizados - {asignatura}")
    display(tabla_coef.round(3))

fig, axes = plt.subplots(1, 2, figsize=(15, 5), sharey=True)
for ax, asignatura in zip(axes, ["Matemática", "Lectura"]):
    data_plot = coef_idps_sin_nse[coef_idps_sin_nse["asignatura"] == asignatura].copy()
    sns.lineplot(
        data=data_plot,
        x="curso_nombre", y="coeficiente",
        hue="indicador", marker="o", ax=ax,
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(f"Modelo Ridge sin NSE - Coeficientes IDPS - {asignatura}")
    ax.set_xlabel("Curso")
    ax.set_ylabel("Coeficiente estandarizado")
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="IDPS", fontsize=8)

plt.suptitle("Modelo Ridge sin NSE: comparación de asociaciones IDPS-SIMCE por curso")
plt.tight_layout()
plt.show()

FIG_SIN_NSE_DIR = Path("salidas_modelo_ridge") / "figuras_modelo_sin_nse"
FIG_SIN_NSE_DIR.mkdir(parents=True, exist_ok=True)

for curso in CURSOS_ORDEN:
    for asignatura in ["Matemática", "Lectura"]:
        nombre_asig = "mate" if asignatura == "Matemática" else "lect"
        graficar_importancia_estilo_github(
            coeficientes_sin_nse_df,
            curso,
            asignatura,
            titulo_prefijo="Modelo Ridge sin NSE",
            output_path=FIG_SIN_NSE_DIR / f"{nombre_asig}_{curso}_importancia_ridge_sin_nse.png",
        )

print(f"Figuras de importancia del modelo Ridge sin NSE guardadas en: {FIG_SIN_NSE_DIR.resolve()}")

# 4.11) Valores reales vs estimados y residuos - Modelo Ridge sin NSE

fig, axes = plt.subplots(4, 2, figsize=(12, 16), sharex=False, sharey=False)

for i, curso in enumerate(CURSOS_ORDEN):
    for j, asignatura in enumerate(["Matemática", "Lectura"]):
        ax = axes[i, j]
        p = predicciones_sin_nse_df[
            (predicciones_sin_nse_df["curso"] == curso)
            & (predicciones_sin_nse_df["asignatura"] == asignatura)
        ]
        ax.scatter(p["real"], p["predicho"], alpha=0.25, s=12, color=PALETA_ASIGNATURA[asignatura])
        min_val = min(p["real"].min(), p["predicho"].min())
        max_val = max(p["real"].max(), p["predicho"].max())
        ax.plot([min_val, max_val], [min_val, max_val], "r--", linewidth=1)
        ax.set_title(f"Ridge sin NSE - {CURSO_NOMBRE[curso]} - {asignatura}")
        ax.set_xlabel("Real")
        ax.set_ylabel("Estimado")

plt.suptitle("Modelo Ridge sin NSE: valores reales vs estimados")
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(4, 2, figsize=(12, 16), sharex=False, sharey=False)

for i, curso in enumerate(CURSOS_ORDEN):
    for j, asignatura in enumerate(["Matemática", "Lectura"]):
        ax = axes[i, j]
        p = predicciones_sin_nse_df[
            (predicciones_sin_nse_df["curso"] == curso)
            & (predicciones_sin_nse_df["asignatura"] == asignatura)
        ]
        ax.hist(p["residuo"], bins=35, edgecolor="white", color=PALETA_ASIGNATURA[asignatura])
        ax.axvline(0, color="black", linestyle="--", linewidth=1)
        ax.set_title(f"Ridge sin NSE - Residuos: {CURSO_NOMBRE[curso]} - {asignatura}")
        ax.set_xlabel("Residuo")
        ax.set_ylabel("Frecuencia")

plt.suptitle("Modelo Ridge sin NSE: distribución de residuos")
plt.tight_layout()
plt.show()

"""## Comparación modelo principal vs modelo sin NSE (Ridge)

Igual que en el modelo OLS, se comparan directamente las métricas y los coeficientes IDPS del modelo Ridge principal vs el modelo Ridge sin NSE.

La lectura recomendada es la misma:

- Si al quitar NSE baja el R² y sube el MAE, el NSE aportaba información explicativa relevante.
- Si al quitar NSE suben mucho los coeficientes de IDPS, parte de su asociación estaba mezclada con desigualdad socioeconómica.
- Si los coeficientes IDPS se mantienen parecidos, los IDPS muestran una asociación más estable incluso al cambiar el control por NSE.
- Adicionalmente, se puede observar si el `alpha` seleccionado por `RidgeCV` cambia al quitar NSE (un cambio relevante en `alpha` puede indicar que la estructura de multicolinealidad del modelo cambió).
"""

# 4.12) Comparación de métricas: modelo Ridge principal vs Ridge sin NSE

metricas_con_nse_comp = metricas_ordenadas.copy()
metricas_con_nse_comp["modelo"] = "Principal"

metricas_sin_nse_comp = metricas_sin_nse_ordenadas.copy()
metricas_sin_nse_comp["modelo"] = "Sin NSE"

metricas_comp_df = pd.concat([metricas_con_nse_comp, metricas_sin_nse_comp], ignore_index=True)

for asignatura in HUE_ASIGNATURA:
    print(f"Comparación de métricas (Ridge): modelo principal vs modelo sin NSE - {asignatura}")
    tabla_asignatura = metricas_comp_df[metricas_comp_df["asignatura"] == asignatura]
    display(tabla_asignatura[[
        "curso_nombre", "modelo", "alpha_seleccionado",
        "MAE_test", "RMSE_test", "R2_test",
        "MAE_CV", "RMSE_CV", "R2_CV",
    ]].round(4).reset_index(drop=True))

metricas_wide = metricas_comp_df.pivot_table(
    index=["curso", "curso_nombre", "asignatura"],
    columns="modelo",
    values=["MAE_test", "RMSE_test", "R2_test", "MAE_CV", "RMSE_CV", "R2_CV", "alpha_seleccionado"],
)
metricas_wide.columns = [f"{metrica}_{modelo}" for metrica, modelo in metricas_wide.columns]
metricas_wide = metricas_wide.reset_index()

metricas_wide["delta_R2_test_sin_menos_principal"] = (
    metricas_wide["R2_test_Sin NSE"] - metricas_wide["R2_test_Principal"]
)
metricas_wide["delta_MAE_test_sin_menos_principal"] = (
    metricas_wide["MAE_test_Sin NSE"] - metricas_wide["MAE_test_Principal"]
)

for asignatura in HUE_ASIGNATURA:
    print(f"Impacto de quitar NSE (Ridge) - {asignatura}")
    tabla_asignatura = metricas_wide[metricas_wide["asignatura"] == asignatura]
    display(tabla_asignatura[[
        "curso_nombre",
        "R2_test_Principal", "R2_test_Sin NSE", "delta_R2_test_sin_menos_principal",
        "MAE_test_Principal", "MAE_test_Sin NSE", "delta_MAE_test_sin_menos_principal",
        "alpha_seleccionado_Principal", "alpha_seleccionado_Sin NSE",
    ]].round(4).reset_index(drop=True))

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

sns.barplot(
    data=metricas_comp_df,
    x="curso_nombre", y="R2_test",
    hue="modelo",
    ax=axes[0],
)
axes[0].set_title("R² test (Ridge): modelo principal vs sin NSE")
axes[0].set_xlabel("Curso")
axes[0].set_ylabel("R² test")
axes[0].tick_params(axis="x", rotation=20)

sns.barplot(
    data=metricas_comp_df,
    x="curso_nombre", y="MAE_test",
    hue="modelo",
    ax=axes[1],
)
axes[1].set_title("MAE test (Ridge): modelo principal vs sin NSE")
axes[1].set_xlabel("Curso")
axes[1].set_ylabel("MAE test")
axes[1].tick_params(axis="x", rotation=20)

plt.suptitle("Impacto de quitar NSE del modelo Ridge")
plt.tight_layout()
plt.show()

fig, axes = plt.subplots(1, 2, figsize=(14, 4), sharey=True)
for ax, asignatura in zip(axes, HUE_ASIGNATURA):
    data_plot = metricas_wide[metricas_wide["asignatura"] == asignatura].copy()
    sns.barplot(
        data=data_plot,
        x="curso_nombre", y="delta_R2_test_sin_menos_principal",
        ax=ax,
        color="gray",
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(f"Cambio de R² al quitar NSE (Ridge) - {asignatura}")
    ax.set_xlabel("Curso")
    ax.set_ylabel("R² sin NSE - R² principal")
    ax.tick_params(axis="x", rotation=20)

plt.tight_layout()
plt.show()

# 4.13) Comparación de coeficientes IDPS: modelo Ridge principal vs Ridge sin NSE

coef_idps_principal_comp = coef_idps[["curso", "curso_nombre", "asignatura", "variable", "indicador", "coeficiente"]].copy()
coef_idps_principal_comp["modelo"] = "Principal"

coef_idps_sin_nse_comp = coef_idps_sin_nse[["curso", "curso_nombre", "asignatura", "variable", "indicador", "coeficiente"]].copy()
coef_idps_sin_nse_comp["modelo"] = "Sin NSE"

coef_idps_comp = pd.concat([coef_idps_principal_comp, coef_idps_sin_nse_comp], ignore_index=True)

coef_idps_wide = coef_idps_comp.pivot_table(
    index=["curso", "curso_nombre", "asignatura", "variable", "indicador"],
    columns="modelo",
    values="coeficiente",
).reset_index()

coef_idps_wide["cambio_sin_menos_principal"] = (
    coef_idps_wide["Sin NSE"] - coef_idps_wide["Principal"]
)
coef_idps_wide["cambio_abs"] = coef_idps_wide["cambio_sin_menos_principal"].abs()

for asignatura in HUE_ASIGNATURA:
    print(f"Coeficientes IDPS (Ridge): modelo principal vs modelo sin NSE - {asignatura}")
    tabla_asignatura = coef_idps_wide[coef_idps_wide["asignatura"] == asignatura]
    display(
        tabla_asignatura.sort_values(["curso", "cambio_abs"], ascending=[True, False])
        [["curso_nombre", "indicador", "Principal", "Sin NSE", "cambio_sin_menos_principal"]]
        .round(3)
        .reset_index(drop=True)
    )

for asignatura in HUE_ASIGNATURA:
    tabla_cambio = coef_idps_wide[coef_idps_wide["asignatura"] == asignatura].pivot_table(
        index="indicador",
        columns="curso_nombre",
        values="cambio_sin_menos_principal",
    )[[CURSO_NOMBRE[c] for c in CURSOS_ORDEN]]
    print(f"Cambio en coeficientes IDPS al quitar NSE (Ridge) - {asignatura}")
    display(tabla_cambio.round(3))

fig, axes = plt.subplots(1, 2, figsize=(15, 5), sharey=True)
for ax, asignatura in zip(axes, HUE_ASIGNATURA):
    data_plot = coef_idps_wide[coef_idps_wide["asignatura"] == asignatura].copy()
    sns.barplot(
        data=data_plot,
        x="curso_nombre", y="cambio_sin_menos_principal",
        hue="indicador",
        ax=ax,
    )
    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_title(f"Cambio de coeficientes IDPS al quitar NSE (Ridge) - {asignatura}")
    ax.set_xlabel("Curso")
    ax.set_ylabel("Coef. sin NSE - coef. principal")
    ax.tick_params(axis="x", rotation=20)
    ax.legend(title="IDPS", fontsize=8)

plt.tight_layout()
plt.show()

OUTPUT_DIR = Path("salidas_modelo_ridge")
OUTPUT_DIR.mkdir(exist_ok=True)
metricas_sin_nse_ordenadas.to_csv(OUTPUT_DIR / "metricas_modelo_ridge_sin_nse.csv", index=False)
coeficientes_sin_nse_df.to_csv(OUTPUT_DIR / "coeficientes_modelo_ridge_sin_nse.csv", index=False)
predicciones_sin_nse_df.to_csv(OUTPUT_DIR / "predicciones_modelo_ridge_sin_nse.csv", index=False)
metricas_comp_df.to_csv(OUTPUT_DIR / "metricas_ridge_principal_vs_sin_nse.csv", index=False)
metricas_wide.to_csv(OUTPUT_DIR / "impacto_quitar_nse_metricas_ridge.csv", index=False)
coef_idps_wide.to_csv(OUTPUT_DIR / "impacto_quitar_nse_coeficientes_idps_ridge.csv", index=False)

print(f"Tablas del modelo Ridge sin NSE y comparación guardadas en: {OUTPUT_DIR.resolve()}")

"""---
# 5) iNTERPRET: Comparación e interpretación (Ridge)

Esta sección resume los resultados principales del modelo Ridge para conectarlos con el problema inicial, con la rúbrica de la Presentación 2, y con la comparación frente al modelo OLS (`ModeloFinal_beta2`).
"""

# 5.1) Ranking automático de IDPS con mayor asociación absoluta por modelo (Ridge)

top_idps = (
    coef_idps.assign(abs_coef=lambda x: x["coeficiente"].abs())
    .sort_values(["curso_nombre", "asignatura", "abs_coef"], ascending=[True, True, False])
    .groupby(["curso", "curso_nombre", "asignatura"], as_index=False)
    .head(1)
    [["curso_nombre", "asignatura", "indicador", "coeficiente"]]
)

display(top_idps.round(3))

# 5.2) Brecha train-test y resumen de alpha para revisar estabilidad (Ridge)

brechas = metricas_ordenadas[["curso_nombre", "asignatura", "alpha_seleccionado", "MAE_train", "MAE_test", "R2_train", "R2_test"]].copy()
brechas["brecha_MAE_test_minus_train"] = brechas["MAE_test"] - brechas["MAE_train"]
brechas["brecha_R2_train_minus_test"] = brechas["R2_train"] - brechas["R2_test"]
display(brechas.round(4))

"""## Síntesis interpretativa (Ridge)

Las tablas anteriores pertenecen a la etapa de modelamiento. En esta sección se resume qué significan los resultados para responder la pregunta del proyecto, y se deja la información necesaria para compararlos con los resultados del modelo OLS.

El foco interpretativo está en cuatro puntos:

1. Qué tan estable es el desempeño del modelo Ridge por curso y asignatura.
2. Qué variables dominan la explicación del SIMCE según Ridge.
3. Qué cambia cuando se quita NSE para observar mejor los IDPS.
4. Qué tan grande es el `alpha` seleccionado por `RidgeCV` en cada caso, y qué tan distintos son los coeficientes de Ridge respecto a los esperados en OLS (a mayor `alpha`, mayor encogimiento de los coeficientes).
"""

# 5.3) Síntesis interpretativa del modelo Ridge principal y la variante sin NSE

print("Desempeño promedio del modelo Ridge principal por asignatura:")
display(
    metricas_ordenadas.groupby("asignatura")[["MAE_test", "RMSE_test", "R2_test", "MAE_CV", "RMSE_CV", "R2_CV"]]
    .mean()
    .round(3)
)

print("Alpha seleccionado promedio por asignatura (modelo Ridge principal):")
display(
    metricas_ordenadas.groupby("asignatura")[["alpha_seleccionado"]]
    .mean()
    .round(4)
)

print("Mejor y peor R² test del modelo Ridge principal:")
ranking_r2 = metricas_ordenadas.sort_values("R2_test", ascending=False)[
    ["curso_nombre", "asignatura", "alpha_seleccionado", "MAE_test", "RMSE_test", "R2_test"]
]
display(ranking_r2.round(4))

print("Top 5 variables por magnitud absoluta en cada modelo Ridge principal:")
top_variables_principal = (
    coeficientes_df.assign(abs_coef=lambda x: x["coeficiente"].abs())
    .sort_values(["curso", "asignatura", "abs_coef"], ascending=[True, True, False])
    .groupby(["curso", "curso_nombre", "asignatura"], as_index=False)
    .head(5)
    [["curso_nombre", "asignatura", "variable", "coeficiente"]]
)
display(top_variables_principal.round(3))

if "metricas_wide" in globals():
    print("Impacto de quitar NSE en métricas (Ridge):")
    display(metricas_wide[[
        "curso_nombre", "asignatura",
        "R2_test_Principal", "R2_test_Sin NSE", "delta_R2_test_sin_menos_principal",
        "MAE_test_Principal", "MAE_test_Sin NSE", "delta_MAE_test_sin_menos_principal",
        "alpha_seleccionado_Principal", "alpha_seleccionado_Sin NSE",
    ]].round(4))

if "coef_idps_wide" in globals():
    print("Mayores cambios en coeficientes IDPS al quitar NSE (Ridge):")
    display(
        coef_idps_wide.sort_values("cambio_abs", ascending=False)
        [["curso_nombre", "asignatura", "indicador", "Principal", "Sin NSE", "cambio_sin_menos_principal"]]
        .head(12)
        .round(3)
    )

"""### Guía para redactar la interpretación final (Ridge vs OLS)

Después de ejecutar este notebook **y** el notebook OLS (`ModeloFinal_beta2`) sobre el mismo conjunto de datos, completa las conclusiones usando estos criterios:

- Si II medio presenta mayor R² en Ridge, igual que en OLS, se puede decir que las variables disponibles explican mejor la variabilidad SIMCE en ese nivel que en básica, independientemente del método de regresión usado.
- Compara el `R2_test` y el `R2_CV` de cada curso/asignatura entre OLS y Ridge: diferencias pequeñas sugieren que la multicolinealidad no estaba afectando gravemente al modelo OLS; diferencias grandes (Ridge mejor que OLS, especialmente en `R2_CV`) sugieren que la penalización ayudó a estabilizar el modelo.
- Compara los coeficientes de los IDPS entre OLS y Ridge para el mismo curso/asignatura: si son muy similares, los IDPS tienen una asociación robusta; si los coeficientes de Ridge son notoriamente más pequeños (encogidos hacia 0), puede indicar que esa variable tenía alta multicolinealidad en OLS.
- Si `nse_ord` aparece entre las variables más grandes en ambos modelos, es consistente con la desigualdad educativa chilena y justifica la variante sin NSE.
- Si al quitar NSE aumentan los coeficientes IDPS en ambos modelos de forma parecida, parte de su asociación estaba mediada o mezclada con el contexto socioeconómico, independientemente del método.
- Revisa el `alpha` seleccionado por `RidgeCV`: valores de `alpha` muy cercanos a 0 indican que la penalización Ridge casi no modifica los resultados respecto a OLS; valores de `alpha` grandes indican que la penalización tuvo un efecto más relevante sobre los coeficientes.
"""

# 5.4) Guardar tablas principales del modelo Ridge para la presentación

OUTPUT_DIR = Path("salidas_modelo_ridge")
OUTPUT_DIR.mkdir(exist_ok=True)

metricas_ordenadas[cols_metricas].to_csv(OUTPUT_DIR / "metricas_modelo_ridge.csv", index=False)
coeficientes_df.to_csv(OUTPUT_DIR / "coeficientes_modelo_ridge.csv", index=False)
coef_idps.to_csv(OUTPUT_DIR / "coeficientes_idps_modelo_ridge.csv", index=False)
skewness_df.to_csv(OUTPUT_DIR / "skewness_por_curso.csv", index=False)
vif_df.to_csv(OUTPUT_DIR / "vif_por_curso.csv", index=False)

if "metricas_sin_nse_ordenadas" in globals():
    metricas_sin_nse_ordenadas.to_csv(OUTPUT_DIR / "metricas_modelo_ridge_sin_nse.csv", index=False)
    coeficientes_sin_nse_df.to_csv(OUTPUT_DIR / "coeficientes_modelo_ridge_sin_nse.csv", index=False)
    metricas_comp_df.to_csv(OUTPUT_DIR / "metricas_ridge_principal_vs_sin_nse.csv", index=False)
    metricas_wide.to_csv(OUTPUT_DIR / "impacto_quitar_nse_metricas_ridge.csv", index=False)
    coef_idps_wide.to_csv(OUTPUT_DIR / "impacto_quitar_nse_coeficientes_idps_ridge.csv", index=False)

print(f"Tablas del modelo Ridge guardadas en: {OUTPUT_DIR.resolve()}")

"""## Comparación de iteraciones e integración con el modelo OLS

| Notebook | Modelo | Estructura de datos | Regresor |
|---|---|---|---|
| `ModeloFinal_beta2` | Regresión lineal múltiple (OLS) | 4 datasets por curso, 8 modelos (curso × asignatura) | `LinearRegression` |
| Este notebook | Ridge Regression | **Mismos** 4 datasets por curso, **mismos** 8 modelos (curso × asignatura) | `RidgeCV` (alpha automático) |

## Cómo comparar resultados OLS vs Ridge

Ambos notebooks guardan sus resultados en carpetas distintas pero con la misma estructura:

- OLS: `salidas_modelo_final/metricas_modelo_final.csv`, `coeficientes_modelo_final.csv`, etc.
- Ridge: `salidas_modelo_ridge/metricas_modelo_ridge.csv`, `coeficientes_modelo_ridge.csv`, etc.

Ambas tablas de métricas comparten las mismas columnas clave (`curso_nombre`, `asignatura`, `MAE_test`, `RMSE_test`, `R2_test`, `MAE_CV`, `RMSE_CV`, `R2_CV`), por lo que se pueden unir (`merge`) usando `curso_nombre` y `asignatura` como llaves, agregando un sufijo `_OLS` / `_Ridge` a las columnas numéricas, para construir directamente una tabla comparativa de 8 filas (una por curso/asignatura).

## Justificación del uso de Ridge como comparación

Se incorpora **Ridge Regression** como modelo de comparación porque:

- mantiene la interpretabilidad de los coeficientes, igual que OLS;
- permite cuantificar el efecto de la multicolinealidad entre los IDPS (detectada mediante VIF) sobre la estabilidad de los coeficientes;
- al usar exactamente el mismo dataset, pipeline, split y validación cruzada que OLS, cualquier diferencia en las métricas o en los coeficientes puede atribuirse al efecto de la penalización L2 y no a diferencias metodológicas externas;
- responde a la misma pregunta de investigación que el modelo OLS, permitiendo evaluar si la conclusión sobre qué IDPS se asocian más con SIMCE es robusta al método de regresión utilizado.

## Conclusiones a completar después de ejecutar

Después de ejecutar este notebook **y** `ModeloFinal_beta2` sobre el mismo dataset, completar esta sección con los resultados observados:

1. **Desempeño general:** indicar qué cursos/asignaturas obtienen mejor y peor R² en Ridge, y si el ranking coincide con el de OLS.
2. **Comparación OLS vs Ridge:** indicar en qué cursos/asignaturas Ridge mejora, empeora o mantiene las métricas de test y de validación cruzada respecto a OLS.
3. **IDPS más asociados:** describir qué indicadores aparecen con mayor coeficiente absoluto en Matemática y Lectura según Ridge, y si coinciden con los de OLS.
4. **Efecto de la penalización:** comentar qué tan grande es el `alpha` seleccionado en cada caso y si los coeficientes de Ridge son notoriamente más pequeños que los de OLS para las variables con mayor VIF.
5. **Comparación por curso:** explicar si la asociación de los IDPS cambia entre básica y media, y si ese patrón es consistente entre OLS y Ridge.
6. **Variables contextuales:** comentar el rol del NSE, dependencia administrativa y ruralidad en ambos modelos.
7. **Conexión con el problema:** explicar qué sugieren los resultados sobre la relación entre desarrollo personal/social y rendimiento SIMCE, y si esa conclusión es robusta al método de regresión (OLS vs Ridge).

## Limitaciones

- Los coeficientes representan asociaciones, no causalidad, tanto en OLS como en Ridge.
- El análisis principal es contemporáneo: IDPS y SIMCE corresponden al mismo año.
- Si se quisiera afirmar predicción futura, habría que usar un dataset con desfase temporal explícito, por ejemplo IDPS en `T-1` para estimar SIMCE en `T`.
- Los indicadores IDPS pueden presentar multicolinealidad; Ridge ayuda a estabilizar los coeficientes pero no elimina la necesidad de interpretarlos con cautela.
- Los resultados dependen de la disponibilidad histórica de SIMCE por curso; no todos los cursos tienen los mismos años evaluados.
- `RidgeCV` selecciona `alpha` usando validación cruzada interna (no agrupada por `rbd`); esto es una simplificación frente a una búsqueda de `alpha` completamente agrupada por establecimiento.
"""