# -*- coding: utf-8 -*-
"""Ridge_SIMCE_modelo_unificado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1up6rDbf8wNHKulM0C4e399LfHRzh4b1I

# Análisis del desempeño académico SIMCE mediante IDPS y variables contextuales
## Modelo: Ridge Regression (Regresión Ridge)

### Problema

El rendimiento académico de los establecimientos educacionales en Chile es medido, entre otros instrumentos, mediante los puntajes SIMCE. Sin embargo, estos resultados no dependen únicamente de factores académicos, sino que también pueden estar asociados a variables socioemocionales y contextuales del establecimiento.

En este proyecto se busca analizar la relación entre los Indicadores de Desarrollo Personal y Social (IDPS), variables contextuales como nivel socioeconómico, dependencia administrativa y ruralidad, y los puntajes SIMCE de Matemática y Lectura.

### Objetivo general

Analizar la relación entre los Indicadores de Desarrollo Personal y Social (IDPS), las variables contextuales de los establecimientos y el rendimiento académico SIMCE, con el fin de identificar qué variables se asocian con mayores o menores puntajes en Matemática y Lectura.

#### Pregunta de investigación

¿Qué relación existe entre los Indicadores de Desarrollo Personal y Social (IDPS), las variables contextuales de los establecimientos y los puntajes SIMCE de Matemática y Lectura?

### Objetivos específicos

- Describir el comportamiento de los puntajes SIMCE de Matemática y Lectura según variables contextuales: nivel socioeconómico (NSE), dependencia administrativa y ruralidad.
- Analizar la relación entre los indicadores IDPS y los puntajes SIMCE.
- Comparar la importancia relativa de variables socioemocionales y contextuales dentro del rendimiento académico observado.
- Interpretar los resultados obtenidos desde una perspectiva educativa, evitando presentar el modelo como una predicción de resultados futuros.

## Enfoque del proyecto: análisis descriptivo-explicativo

El enfoque del proyecto se orienta a realizar un análisis descriptivo-explicativo en lugar de un análisis predictivo.

Esta decisión se debe a que, para el contexto educativo, resulta especialmente útil comprender qué variables socioemocionales y contextuales se asocian con mejores o peores resultados SIMCE. Este tipo de análisis puede aportar información relevante para orientar decisiones educativas, identificar áreas de mejora y apoyar la discusión sobre dónde poner mayor atención al momento de diseñar estrategias o políticas públicas educacionales.

En esta etapa, el dataset contiene variables socioemocionales, contextuales y puntajes SIMCE correspondientes al mismo período temporal. Por lo tanto, el análisis permite estudiar relaciones contemporáneas entre variables, pero no permite afirmar que el modelo predice resultados SIMCE de años posteriores.

El proyecto no busca responder "cuánto puntaje tendrá un establecimiento en el futuro", sino responder preguntas como:

- ¿Qué variables socioemocionales se asocian con mejores o peores resultados SIMCE?
- ¿Qué peso tienen las variables contextuales como NSE, dependencia y ruralidad?
- ¿Las relaciones observadas son similares en Matemática y Lectura?
- ¿Qué variables parecen ser más relevantes para comprender las diferencias de rendimiento entre establecimientos?

### Modelo: Ridge Regression con Matemática + Lectura

Ridge Regression es una extensión de la regresión lineal múltiple que incorpora un término de penalización L2 sobre los coeficientes. Esto permite:

- **Manejar multicolinealidad** entre los indicadores IDPS, que suelen estar correlacionados entre sí.
- **Estabilizar los coeficientes** sin eliminar variables del modelo.
- **Mantener la misma interpretabilidad** que la regresión lineal: cada coeficiente representa la asociación ajustada de una variable con el puntaje SIMCE.

Al igual que en el modelo de regresión lineal múltiple, el dataset se reorganiza en formato largo para trabajar Matemática y Lectura dentro de la misma estructura de análisis.

**Variable objetivo (Y):** puntaje SIMCE por establecimiento.

**Variables explicativas (X):** indicadores IDPS, NSE, dependencia administrativa, ruralidad y tipo de prueba.

**Tipo de prueba:** variable categórica que indica si el puntaje corresponde a Matemática o Lectura.

### Significado de variables

- **ind_am = Autoestima Académica y Motivación:** índice alto = colegio con estudiantes que se sienten capaces y motivados.
- **ind_cc = Clima de Convivencia Escolar:** percepción de seguridad, respeto y organización dentro del establecimiento.
- **ind_hv = Hábitos de Vida Saludable:** actitudes relacionadas con bienestar físico, actividad física y autocuidado.
- **ind_pf = Participación y Formación Ciudadana:** sentido de pertenencia al colegio y fomento de valores democráticos y participación estudiantil.
- **Info extra:** todas las variables `ind_` van de 0 a 100, donde un valor mayor representa mejor resultado en el indicador.
- **NSE = Nivel Socioeconómico del Establecimiento = cod_grupo:** Bajo, Medio bajo, Medio, Medio alto y Alto.
- **dependencia = Tipo de Establecimiento = cod_depe2:** Municipal, Particular subvencionado, Particular pagado o SLEP.
- **ruralidad = Zona del establecimiento = cod_rural_rbd:** Urbano o Rural.

### Metodología: Framework OSEMN

Obtain → Scrub → Explore → Model → iNterpret

## 1) OBTAIN:

**Fuente:** [Agencia de Calidad de la Educación](https://informacionestadistica.agenciaeducacion.cl/#/bases),
la cual posee registros históricos de establecimientos educacionales chilenos:
- SIMCE
- Indicadores de Desarrollo Personal y Social (IDPS)
"""

# 1) OBTAIN: Carga y revisión inicial del dataset

from google.colab import files
import pandas as pd
import numpy as np

uploaded = files.upload()  # Sube dataset

df = pd.read_csv("dataset_historico_final.csv")

print(f"Dimensiones del dataset: {df.shape[0]} filas × {df.shape[1]} columnas")
print(f"Años disponibles: {sorted(df['agno'].unique())}")
print(f"\nPrimeras filas:")
df.head()

"""## 2) SCRUB:
En esta sección se realizaron 3 operaciones:
  1) **Estandarizar las variables categóricas:** algunas variables utilizan códigos
   numéricos (1, 2, 3, ...) que no tienen significado real, por lo que se convierten a etiquetas de texto descriptivas para facilitar la interpretación
  2) **Valores Nulos:** Se eliminan las filas con datos nulos (dropna)
  3) **Outliers:** Se aplica IQR (rango intercuartil) sobre los puntajes SIMCE ya que se asume que no hay una distribución normal en los datos

"""

# Valores ANTES de estandarizar
print("NSE (cod_grupo):", df['cod_grupo'].unique())
print("Dependencia (cod_depe2):", df['cod_depe2'].unique())
print("Ruralidad (cod_rural_rbd):", df['cod_rural_rbd'].unique())

# 2) SCRUB: Limpieza de dataset

nse_map = {'1.0': 'Bajo', '2.0': 'Medio bajo', '3.0': 'Medio',
           '4.0': 'Medio alto', '5.0': 'Alto'}
depe_map = {'1': 'Municipal', '2': 'Particular subvencionado',
            '3': 'Particular pagado', '4': 'SLEP'}
rural_map = {'1': 'Urbano', '2': 'Rural'}

df['cod_grupo']     = df['cod_grupo'].replace(nse_map)
df['cod_depe2']     = df['cod_depe2'].replace(depe_map)
df['cod_rural_rbd'] = df['cod_rural_rbd'].replace(rural_map)

print("Resultados de la estandarización de las var. categóricas:")
print("Categorías NSE:", df['cod_grupo'].unique())
print("Categorías dependencia:", df['cod_depe2'].unique())
print("Categorías ruralidad:", df['cod_rural_rbd'].unique())

# Nulos
print(f"\nValores nulos por columna:")
print(df.isnull().sum())
df = df.dropna()
print(f"Filas después de dropna: {len(df)}")

# Detección y eliminación de Outliers en SIMCE
for col in ['prom_mate2m_rbd', 'prom_lect2m_rbd']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    antes = len(df)
    df = df[(df[col] >= Q1 - 1.5*IQR) & (df[col] <= Q3 + 1.5*IQR)]
    print(f"Outliers eliminados en {col}: {antes - len(df)}")

print(f"\nDataset final: {df.shape[0]} filas")

"""## Resultados del SCRUB

- No se encontraron valores nulos en el dataset utilizado.
- La detección de outliers mediante IQR se aplica sobre los puntajes SIMCE de Matemática y Lectura. El número exacto de registros removidos queda reportado en la celda anterior, para mantener trazabilidad del proceso.
- Las variables categóricas NSE, dependencia y ruralidad pasaron de códigos numéricos a etiquetas de texto descriptivas.
- Esta limpieza permite que los análisis posteriores sean más interpretables, especialmente al estudiar factores contextuales externos asociados al puntaje SIMCE.

## 3) EXPLORE:

Se explora la distribución de las variables objetivo y su relación con las variables explicativas, a través de estadísticas descriptivas y visualizaciones.
"""

# 3) EXPLORE: Estadísticas descriptivas

import matplotlib.pyplot as plt
import seaborn as sns

print(" -- Estadísticas descriptivas --")
cols_interes = ['prom_mate2m_rbd', 'prom_lect2m_rbd',
                'ind_am', 'ind_cc', 'ind_hv', 'ind_pf']
print(df[cols_interes].describe().round(2))

"""## Distribución de puntajes SIMCE: Matemática y Lectura

A continuación se visualizan, en una misma celda, las distribuciones de puntajes SIMCE de Matemática y Lectura por establecimiento. Esto permite comparar rápidamente el comportamiento general de ambas pruebas.

"""

# 3.1) EXPLORE: Distribución SIMCE Matemática y Lectura

fig, axes = plt.subplots(1, 2, figsize=(14, 4), sharey=True)

df['prom_mate2m_rbd'].hist(bins=40, ax=axes[0], color='steelblue')
axes[0].set_title("Distribución SIMCE Matemática")
axes[0].set_xlabel("Puntaje")
axes[0].set_ylabel("Frecuencia")

df['prom_lect2m_rbd'].hist(bins=40, ax=axes[1], color='coral')
axes[1].set_title("Distribución SIMCE Lectura")
axes[1].set_xlabel("Puntaje")

plt.suptitle("Distribución de puntajes SIMCE por prueba", fontsize=13)
plt.tight_layout()
plt.show()

"""## Puntaje SIMCE según nivel socioeconómico (NSE)

Los siguientes gráficos comparan la distribución de puntajes SIMCE de Matemática y Lectura según el nivel socioeconómico del establecimiento. Al ubicarlos lado a lado, se puede observar si el patrón por NSE se mantiene de forma similar en ambas pruebas.

"""

# 3.2) EXPLORE: SIMCE Matemática y Lectura por NSE

orden_nse = ['Bajo', 'Medio bajo', 'Medio', 'Medio alto', 'Alto']
fig, axes = plt.subplots(1, 2, figsize=(16, 5), sharey=True)

sns.boxplot(data=df, x='cod_grupo', y='prom_mate2m_rbd',
            order=orden_nse, ax=axes[0], palette='Blues',
            hue='cod_grupo', legend=False)
axes[0].set_title("SIMCE Matemática por NSE")
axes[0].set_xlabel("NSE")
axes[0].set_ylabel("Puntaje SIMCE")

sns.boxplot(data=df, x='cod_grupo', y='prom_lect2m_rbd',
            order=orden_nse, ax=axes[1], palette='Oranges',
            hue='cod_grupo', legend=False)
axes[1].set_title("SIMCE Lectura por NSE")
axes[1].set_xlabel("NSE")
axes[1].set_ylabel("")

plt.suptitle("Puntajes SIMCE por nivel socioeconómico", fontsize=13)
plt.tight_layout()
plt.show()

"""## Puntaje SIMCE según dependencia administrativa

Esta visualización permite analizar diferencias en el rendimiento académico según el tipo de establecimiento educacional, comparando Matemática y Lectura dentro de la misma celda.

"""

# 3.3) EXPLORE: SIMCE Matemática y Lectura por dependencia

fig, axes = plt.subplots(1, 2, figsize=(18, 5), sharey=True)

sns.boxplot(data=df, x='cod_depe2', y='prom_mate2m_rbd',
            palette='Set2', ax=axes[0],
            hue='cod_depe2', legend=False)
axes[0].set_title("SIMCE Matemática por dependencia")
axes[0].set_xlabel("Dependencia")
axes[0].set_ylabel("Puntaje SIMCE")
axes[0].tick_params(axis='x', rotation=30)

sns.boxplot(data=df, x='cod_depe2', y='prom_lect2m_rbd',
            palette='Set2', ax=axes[1],
            hue='cod_depe2', legend=False)
axes[1].set_title("SIMCE Lectura por dependencia")
axes[1].set_xlabel("Dependencia")
axes[1].set_ylabel("")
axes[1].tick_params(axis='x', rotation=30)

plt.suptitle("Puntajes SIMCE por dependencia administrativa", fontsize=13)
plt.tight_layout()
plt.show()

"""## Puntaje SIMCE según ruralidad

Esta visualización permite comparar el comportamiento de Matemática y Lectura según si el establecimiento se encuentra en una zona urbana o rural.

"""

# 3.4) EXPLORE: SIMCE Matemática y Lectura por ruralidad

fig, axes = plt.subplots(1, 2, figsize=(14, 5), sharey=True)

sns.boxplot(data=df, x='cod_rural_rbd', y='prom_mate2m_rbd',
            palette='Set3', ax=axes[0],
            hue='cod_rural_rbd', legend=False)
axes[0].set_title("SIMCE Matemática por ruralidad")
axes[0].set_xlabel("Ruralidad")
axes[0].set_ylabel("Puntaje SIMCE")

sns.boxplot(data=df, x='cod_rural_rbd', y='prom_lect2m_rbd',
            palette='Set3', ax=axes[1],
            hue='cod_rural_rbd', legend=False)
axes[1].set_title("SIMCE Lectura por ruralidad")
axes[1].set_xlabel("Ruralidad")
axes[1].set_ylabel("")

plt.suptitle("Puntajes SIMCE por ruralidad", fontsize=13)
plt.tight_layout()
plt.show()

"""## Matriz de correlaciones

La matriz de correlación permite observar la intensidad y dirección de las relaciones lineales entre los indicadores IDPS y los puntajes SIMCE de Matemática y Lectura.

"""

# 3.5) EXPLORE: Matriz de Correlaciones

corr = df[cols_interes].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", center=0)
plt.title("Matriz de correlación: IDPS y puntajes SIMCE")
plt.tight_layout()
plt.show()

"""## Relación entre indicadores IDPS y puntajes SIMCE

Los siguientes gráficos de dispersión permiten visualizar la relación entre cada indicador IDPS y los puntajes SIMCE de Matemática y Lectura. Cada fila corresponde a un indicador IDPS, dejando Matemática a la izquierda y Lectura a la derecha.

"""

# 3.6) EXPLORE: Scatter IDPS vs SIMCE Matemática y Lectura

idps = [
    ('ind_am', 'Autoestima Académica'),
    ('ind_cc', 'Clima de Convivencia'),
    ('ind_hv', 'Hábitos Saludables'),
    ('ind_pf', 'Participación Ciudadana')
]

fig, axes = plt.subplots(len(idps), 2, figsize=(14, 18), sharey='row')

for i, (col, nombre) in enumerate(idps):
    axes[i, 0].scatter(df[col], df['prom_mate2m_rbd'], alpha=0.2, s=10, color='steelblue')
    axes[i, 0].set_title(f"{nombre} vs SIMCE Matemática")
    axes[i, 0].set_xlabel(nombre)
    axes[i, 0].set_ylabel("SIMCE Matemática")

    axes[i, 1].scatter(df[col], df['prom_lect2m_rbd'], alpha=0.2, s=10, color='coral')
    axes[i, 1].set_title(f"{nombre} vs SIMCE Lectura")
    axes[i, 1].set_xlabel(nombre)
    axes[i, 1].set_ylabel("SIMCE Lectura")

plt.suptitle("Relación entre IDPS y puntajes SIMCE por prueba", fontsize=14)
plt.tight_layout()
plt.show()

"""## Conclusiones del análisis exploratorio

- El NSE muestra una relación progresiva y clara con los puntajes SIMCE: a mayor nivel socioeconómico, se observan mayores puntajes en ambas pruebas.
- La comparación lado a lado permite observar si los patrones de Matemática y Lectura son similares o si existen diferencias relevantes entre ambas pruebas.
- La dependencia administrativa también muestra diferencias en la distribución de puntajes, especialmente al comparar establecimientos municipales, particulares subvencionados, particulares pagados y SLEP.
- La matriz de correlación permite observar que los puntajes de Matemática y Lectura están fuertemente relacionados entre sí, lo que justifica analizarlos dentro de una misma estructura de datos.
- Los indicadores IDPS presentan relaciones positivas con los puntajes SIMCE, aunque la intensidad de esa relación puede variar según el indicador y la prueba.
- Las correlaciones y gráficos deben interpretarse como asociaciones, no como causalidad directa.

## Análisis de factores externos sobre el puntaje SIMCE

Para responder a la intención del proyecto, los gráficos exploratorios se interpretan como una primera aproximación al comportamiento de factores externos o contextuales sobre el puntaje SIMCE.

En este cuaderno se consideran como factores contextuales externos:

- **Nivel socioeconómico (NSE):** variable ordinal que representa el contexto socioeconómico del establecimiento.
- **Dependencia administrativa:** tipo de administración del establecimiento.
- **Ruralidad:** ubicación urbana o rural del establecimiento.

Los IDPS se interpretan como factores socioemocionales del entorno escolar. En conjunto, estas variables permiten estudiar diferencias de rendimiento entre establecimientos.

Importante: en este proyecto se usa la palabra **impacto** solo como una forma comunicacional de hablar de diferencias o asociaciones observadas. Técnicamente, los resultados del modelo deben entenderse como **asociaciones ajustadas**, no como efectos causales demostrados.

"""

# 3.7) EXPLORE: Resumen de factores externos

factores_externos = {
    "NSE": "cod_grupo",
    "Dependencia": "cod_depe2",
    "Ruralidad": "cod_rural_rbd"
}

resumen_factores = []

for nombre_factor, col_factor in factores_externos.items():
    resumen = (
        df.groupby(col_factor)[["prom_mate2m_rbd", "prom_lect2m_rbd"]]
        .agg(["count", "mean", "median", "std"])
        .round(2)
    )
    resumen.columns = [
        "Matemática_n", "Matemática_media", "Matemática_mediana", "Matemática_std",
        "Lectura_n", "Lectura_media", "Lectura_mediana", "Lectura_std"
    ]
    resumen = resumen.reset_index().rename(columns={col_factor: "Categoría"})
    resumen.insert(0, "Factor externo", nombre_factor)
    resumen_factores.append(resumen)

resumen_factores = pd.concat(resumen_factores, ignore_index=True)
display(resumen_factores)

"""### Lectura de los factores externos

La tabla anterior complementa los boxplots y permite observar diferencias promedio por categoría. Si una categoría presenta medias sistemáticamente más altas o más bajas, eso sugiere una asociación entre ese factor externo y el puntaje SIMCE.

Esta evidencia descriptiva no permite afirmar causalidad, pero sí ayuda a responder la pregunta del proyecto: qué factores contextuales y socioemocionales se relacionan con mayores o menores puntajes en Matemática y Lectura.

## 4) MODEL: Ridge Regression con Matemática + Lectura

En esta sección se implementa Ridge Regression utilizando Matemática y Lectura dentro de una misma estructura de datos, en formato largo, exactamente igual que en el modelo de regresión lineal múltiple.

El modelo considera:

- Variables numéricas asociadas a los indicadores IDPS.
- Variables categóricas asociadas al contexto escolar.
- La variable categórica `tipo_prueba`.
- Estandarización de variables numéricas.
- Codificación One-Hot para variables categóricas.
- Separación train/test y validación cruzada para evaluar estabilidad.
- Selección automática del parámetro `alpha` mediante `RidgeCV`.

> Importante: al igual que en el modelo de regresión lineal múltiple, la interpretación del proyecto sigue siendo descriptivo-explicativa. El modelo se usa para estimar asociaciones, no para afirmar predicción futura.
"""

# 4.1) Preparación del dataset en formato largo

df_model = df.reset_index().rename(columns={"index": "id_registro"})

id_vars = [
    "id_registro",
    "ind_am", "ind_cc", "ind_hv", "ind_pf",
    "cod_grupo", "cod_depe2", "cod_rural_rbd"
]

for col in ["agno", "rbd"]:
    if col in df_model.columns and col not in id_vars:
        id_vars.append(col)

df_long = df_model.melt(
    id_vars=id_vars,
    value_vars=["prom_mate2m_rbd", "prom_lect2m_rbd"],
    var_name="tipo_prueba",
    value_name="puntaje_simce"
)

df_long["tipo_prueba"] = df_long["tipo_prueba"].map({
    "prom_mate2m_rbd": "Matemática",
    "prom_lect2m_rbd": "Lectura"
})

df_long = df_long.dropna(subset=["puntaje_simce"]).copy()

print(f"Dataset original: {df.shape[0]} filas")
print(f"Dataset largo: {df_long.shape[0]} filas")
print("\nDistribución por tipo de prueba:")
print(df_long["tipo_prueba"].value_counts())

df_long.head()

# 4.2) Entrenamiento del modelo Ridge

from sklearn.model_selection import train_test_split, cross_val_score, GroupShuffleSplit, GroupKFold
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import RidgeCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

target = "puntaje_simce"

features_num = ["ind_am", "ind_cc", "ind_hv", "ind_pf"]
features_cat = ["cod_grupo", "cod_rural_rbd", "cod_depe2", "tipo_prueba"]

X = df_long[features_num + features_cat]
y = df_long[target]

groups = df_long["id_registro"]

gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_idx, test_idx = next(gss.split(X, y, groups=groups))

X_train = X.iloc[train_idx]
X_test  = X.iloc[test_idx]
y_train = y.iloc[train_idx]
y_test  = y.iloc[test_idx]

print(f"Train: {len(X_train)} registros | Test: {len(X_test)} registros")

# Pipeline con RidgeCV (selecciona alpha óptimo automáticamente)
preprocessor_ridge = ColumnTransformer(transformers=[
    ("num", StandardScaler(), features_num),
    ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat)
])

model_ridge = Pipeline(steps=[
    ("preprocessor", preprocessor_ridge),
    ("regressor", RidgeCV(alphas=np.logspace(-3, 4, 50), cv=5))
])

model_ridge.fit(X_train, y_train)

alpha_seleccionado = model_ridge.named_steps["regressor"].alpha_
print(f"\nAlpha seleccionado por RidgeCV: {alpha_seleccionado:.4f}")

y_pred_train = model_ridge.predict(X_train)
y_pred_test  = model_ridge.predict(X_test)

# 4.3) Evaluación Train vs Test + Validación Cruzada

def calcular_metricas(y_real, y_estimado):
    return {
        "MAE":  mean_absolute_error(y_real, y_estimado),
        "RMSE": np.sqrt(mean_squared_error(y_real, y_estimado)),
        "R2":   r2_score(y_real, y_estimado)
    }

metricas_train = calcular_metricas(y_train, y_pred_train)
metricas_test  = calcular_metricas(y_test,  y_pred_test)

resultados_modelo = pd.DataFrame([
    {"Dataset": "Train", **metricas_train},
    {"Dataset": "Test",  **metricas_test}
])

n_groups = groups.nunique()
n_splits = min(5, n_groups)

if n_splits >= 2:
    cv = GroupKFold(n_splits=n_splits)
    cv_scores = cross_val_score(
        model_ridge,
        X, y,
        cv=cv,
        groups=groups,
        scoring="r2"
    )
    r2_cv_mean = cv_scores.mean()
    r2_cv_std  = cv_scores.std()
else:
    cv_scores = np.array([np.nan])
    r2_cv_mean = np.nan
    r2_cv_std  = np.nan

display(resultados_modelo.round(3))

print(f"R² validación cruzada: {np.round(cv_scores, 3)}")
print(f"R² promedio CV: {r2_cv_mean:.3f} ± {r2_cv_std:.3f}")
print(f"Alpha seleccionado: {alpha_seleccionado:.4f}")

"""## Comparación de iteraciones del modelo

Para mantener la misma estructura que el modelo de regresión lineal múltiple, se comparan tres enfoques:

- **Iteración 1 - Matemática:** modelo Ridge separado usando solo puntaje SIMCE Matemática.
- **Iteración 1 - Lectura:** modelo Ridge separado usando solo puntaje SIMCE Lectura.
- **Iteración 2 - Modelo unificado:** modelo Ridge final con Matemática y Lectura en formato largo, diferenciadas por `tipo_prueba`.

"""

# 4.4) Comparación de iteraciones: modelos separados vs modelo unificado

from copy import deepcopy
from sklearn.linear_model import RidgeCV as RCV

def evaluar_modelo_ridge(nombre, X_tr, X_te, y_tr, y_te):
    pre = ColumnTransformer(transformers=[
        ("num", StandardScaler(), features_num),
        ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"), features_cat_base)
    ])
    pipe = Pipeline(steps=[
        ("preprocessor", pre),
        ("regressor", RCV(alphas=np.logspace(-3, 4, 50), cv=5))
    ])
    pipe.fit(X_tr, y_tr)
    pred_test = pipe.predict(X_te)
    return {
        "Iteración": nombre,
        "MAE Test":  mean_absolute_error(y_te, pred_test),
        "RMSE Test": np.sqrt(mean_squared_error(y_te, pred_test)),
        "R2 Test":   r2_score(y_te, pred_test)
    }

features_cat_base = ["cod_grupo", "cod_rural_rbd", "cod_depe2"]
X_base = df[features_num + features_cat_base]

X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(
    X_base, df["prom_mate2m_rbd"], test_size=0.2, random_state=42
)
X_train_l, X_test_l, y_train_l, y_test_l = train_test_split(
    X_base, df["prom_lect2m_rbd"], test_size=0.2, random_state=42
)

comparacion_iteraciones = [
    evaluar_modelo_ridge(
        "Iteración 1 - Modelo separado Matemática (Ridge)",
        X_train_m, X_test_m, y_train_m, y_test_m
    ),
    evaluar_modelo_ridge(
        "Iteración 1 - Modelo separado Lectura (Ridge)",
        X_train_l, X_test_l, y_train_l, y_test_l
    ),
    {
        "Iteración": "Iteración 2 - Modelo unificado Matemática + Lectura (Ridge)",
        "MAE Test":  metricas_test["MAE"],
        "RMSE Test": metricas_test["RMSE"],
        "R2 Test":   metricas_test["R2"]
    }
]

comparacion_iteraciones = pd.DataFrame(comparacion_iteraciones)
display(comparacion_iteraciones.round(3))

"""### Selección del modelo final

Se selecciona como modelo final la **Ridge Regression unificada** con Matemática y Lectura en formato largo.

La decisión se basa en los mismos criterios metodológicos del modelo de regresión lineal múltiple:

- Permite analizar Matemática y Lectura dentro de una misma estructura.
- Incorpora `tipo_prueba` como variable explicativa.
- Facilita comparar asociaciones de factores externos y socioemocionales sin duplicar el pipeline.
- Mantiene una interpretación clara de coeficientes, útil para explicar qué variables se asocian con mayores o menores puntajes SIMCE.

Adicionalmente, Ridge aporta mayor estabilidad de los coeficientes frente a la multicolinealidad que puede existir entre los indicadores IDPS.

## Chequeos técnicos para Ridge Regression

Se revisan los mismos puntos que en el modelo de regresión lineal múltiple:

- **Simetría/asimetría:** skewness sobre variables SIMCE e IDPS.
- **Multicolinealidad:** VIF sobre los indicadores IDPS. Ridge es especialmente adecuado cuando el VIF es moderado o alto.
- **Codificación de NSE:** comparación One-Hot vs Ordinal.
"""

# 4.5) Chequeos técnicos: asimetría y multicolinealidad

from sklearn.linear_model import LinearRegression

cols_regresion = [
    "prom_mate2m_rbd", "prom_lect2m_rbd",
    "ind_am", "ind_cc", "ind_hv", "ind_pf"
]

asimetria = (
    df[cols_regresion]
    .skew()
    .reset_index()
    .rename(columns={"index": "Variable", 0: "Skewness"})
)

display(asimetria.round(3))

def calcular_vif(df_predictores):
    resultados = []
    for variable in df_predictores.columns:
        otras_variables = [col for col in df_predictores.columns if col != variable]
        X_aux = df_predictores[otras_variables]
        y_aux = df_predictores[variable]
        modelo_aux = LinearRegression()
        modelo_aux.fit(X_aux, y_aux)
        r2_aux = modelo_aux.score(X_aux, y_aux)
        vif = np.inf if r2_aux >= 1 else 1 / (1 - r2_aux)
        resultados.append({
            "Variable": variable,
            "R2 auxiliar": r2_aux,
            "VIF": vif
        })
    return pd.DataFrame(resultados)

vif_idps = calcular_vif(df[features_num])
display(vif_idps.round(3))

print("\nNota: Ridge es especialmente adecuado cuando los VIF son moderados (5-10) o altos (>10),")
print("ya que penaliza los coeficientes inestables causados por multicolinealidad.")

# 4.6) Comparación de codificación de NSE: One-Hot vs Ordinal

from sklearn.preprocessing import OrdinalEncoder

orden_nse = ["Bajo", "Medio bajo", "Medio", "Medio alto", "Alto"]

preprocessor_ordinal_nse = ColumnTransformer(transformers=[
    ("num", StandardScaler(), features_num),
    ("nse", OrdinalEncoder(categories=[orden_nse]), ["cod_grupo"]),
    ("cat", OneHotEncoder(handle_unknown="ignore", drop="first"),
     ["cod_rural_rbd", "cod_depe2", "tipo_prueba"])
])

model_ordinal_nse = Pipeline(steps=[
    ("preprocessor", preprocessor_ordinal_nse),
    ("regressor", RidgeCV(alphas=np.logspace(-3, 4, 50), cv=5))
])

model_ordinal_nse.fit(X_train, y_train)
y_pred_test_ordinal = model_ordinal_nse.predict(X_test)

comparacion_codificacion_nse = pd.DataFrame([
    {
        "Codificación NSE": "One-Hot",
        "MAE Test":  metricas_test["MAE"],
        "RMSE Test": metricas_test["RMSE"],
        "R2 Test":   metricas_test["R2"]
    },
    {
        "Codificación NSE": "Ordinal",
        "MAE Test":  mean_absolute_error(y_test, y_pred_test_ordinal),
        "RMSE Test": np.sqrt(mean_squared_error(y_test, y_pred_test_ordinal)),
        "R2 Test":   r2_score(y_test, y_pred_test_ordinal)
    }
])

display(comparacion_codificacion_nse.round(3))

"""### Interpretación de los chequeos técnicos

- Valores de skewness cercanos a 0 sugieren distribuciones relativamente simétricas; valores más alejados indican asimetría.
- En VIF, valores sobre 5 suelen advertir posible multicolinealidad relevante y valores sobre 10 suelen considerarse problemáticos. Ridge es el modelo preferido cuando el VIF de los IDPS es moderado o alto, ya que encoge los coeficientes inestables sin eliminarlos.
- Para NSE se revisa una alternativa ordinal porque sus categorías tienen orden natural. Si las métricas son similares, se puede preferir la opción que entregue una interpretación más clara para la presentación.

### Interpretación de métricas

- **MAE:** se utiliza porque expresa el error promedio directamente en puntos SIMCE, lo que facilita la interpretación educativa.
- **RMSE:** se reporta como complemento, ya que penaliza con mayor fuerza los errores grandes.
- **R²:** permite observar qué proporción de la variabilidad del puntaje SIMCE es explicada por el modelo.
- **R² CV:** permite evaluar si el desempeño del modelo se mantiene estable al cambiar las particiones de los datos.

En este proyecto no se prioriza MAPE porque los puntajes SIMCE no son una variable porcentual ni tienen un cero interpretativo natural.
"""

# 5) iNTERPRET: Valores reales vs estimados - Modelo Ridge

import matplotlib.pyplot as plt

plt.figure(figsize=(7, 7))
plt.scatter(y_test, y_pred_test, alpha=0.3, s=15, color='coral')
min_val = min(y_test.min(), y_pred_test.min())
max_val = max(y_test.max(), y_pred_test.max())
plt.plot([min_val, max_val], [min_val, max_val], "r--", label="Estimación exacta")
plt.xlabel("Valores reales SIMCE")
plt.ylabel("Valores estimados por el modelo")
plt.title("Modelo Ridge: valores reales vs estimados")
plt.legend()
plt.tight_layout()
plt.show()

# 5.1) iNTERPRET: Distribución de residuos - Modelo Ridge

residuals = y_test - y_pred_test

plt.figure(figsize=(8, 4))
plt.hist(residuals, bins=40, edgecolor="white", color='coral')
plt.axvline(0, color="black", linestyle="--")
plt.xlabel("Residuo (Real − Estimado)")
plt.ylabel("Frecuencia")
plt.title("Distribución de residuos — Modelo Ridge")
plt.tight_layout()
plt.show()

print(f"Media de residuos: {residuals.mean():.2f}")
print(f"Desviación estándar de residuos: {residuals.std():.2f}")

"""## Asociación ajustada de factores externos

El gráfico de coeficientes permite aproximar el "impacto" de los factores externos como una **asociación ajustada**: cada coeficiente representa la diferencia esperada en puntaje SIMCE asociada a una variable, manteniendo constantes las demás variables del modelo.

Para las variables categóricas, la interpretación siempre es relativa a una categoría base. Por eso se imprime la categoría base utilizada por `OneHotEncoder`.

En Ridge, los coeficientes son ligeramente más pequeños que en OLS (están encogidos hacia 0 por la penalización), pero la dirección e interpretación de cada asociación se mantiene igual.

## Importancia relativa de variables

A continuación se analizan los coeficientes del modelo Ridge. Estos coeficientes permiten observar qué variables presentan mayor asociación con el puntaje SIMCE dentro del modelo.

Los coeficientes positivos indican asociación con puntajes más altos, mientras que los negativos indican asociación con puntajes más bajos, manteniendo constantes las demás variables incluidas.

Como las variables numéricas fueron estandarizadas, sus coeficientes representan cambios asociados a una desviación estándar de la variable, no a un punto exacto del indicador.

Importante: los coeficientes deben interpretarse como asociaciones y no como efectos causales directos.
"""

# 5.2) iNTERPRET: Coeficientes del modelo Ridge

feature_names = (
    model_ridge.named_steps["preprocessor"]
    .named_transformers_["num"]
    .get_feature_names_out(features_num).tolist()
    +
    model_ridge.named_steps["preprocessor"]
    .named_transformers_["cat"]
    .get_feature_names_out(features_cat).tolist()
)

coefs = model_ridge.named_steps["regressor"].coef_

coef_df = pd.DataFrame({
    "Variable": feature_names,
    "Coeficiente": coefs
})

coef_df = coef_df.reindex(
    coef_df["Coeficiente"].abs().sort_values(ascending=False).index
)

display(coef_df.round(3).head(15))

plt.figure(figsize=(10, 6))
plt.barh(coef_df["Variable"].head(15), coef_df["Coeficiente"].head(15), color='coral')
plt.axvline(0, color="black", linewidth=0.8)
plt.xlabel("Coeficiente")
plt.title(f"Variables con mayor asociación — Modelo Ridge (alpha={alpha_seleccionado:.4f})")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

print("\nCategoría base usada por OneHotEncoder en variables categóricas:")
encoder_cat = model_ridge.named_steps["preprocessor"].named_transformers_["cat"]
for variable, categorias in zip(features_cat, encoder_cat.categories_):
    print(f"- {variable}: categoría base = {categorias[0]}")

"""## Síntesis del modelo

El modelo Ridge Regression se implementa con Matemática y Lectura integradas en una sola variable objetivo (`puntaje_simce`) y diferenciadas mediante la variable `tipo_prueba`, replicando exactamente la misma estructura que el modelo de regresión lineal múltiple.

La diferencia fundamental con OLS es la incorporación del parámetro `alpha`, seleccionado automáticamente por `RidgeCV`, que penaliza los coeficientes grandes y reduce la inestabilidad causada por multicolinealidad entre los IDPS.

Al igual que en el modelo base, el foco del análisis está en identificar qué variables socioemocionales y contextuales se asocian con mayores o menores puntajes SIMCE, sin afirmar causalidad directa ni predicción de resultados futuros.

## Síntesis de diferencias respecto al modelo de Regresión Lineal Múltiple

| Aspecto | Regresión Lineal Múltiple (OLS) | Ridge Regression (L2) |
|---|---|---|
| Penalización de coeficientes | No | Sí (L2, parámetro alpha) |
| Selección de alpha | N/A | Automática con RidgeCV (CV=5) |
| Manejo de multicolinealidad | Sensible | Más robusto |
| Interpretación de coeficientes | Igual | Igual (asociaciones ajustadas) |
| Variables eliminadas | No | No (Ridge encoge, no elimina) |
| Enfoque del proyecto | Descriptivo-explicativo | Descriptivo-explicativo |

Las métricas Train/Test y R² CV de ambos modelos pueden compararse directamente para justificar cuál es más adecuado para este proyecto.

"""